// Appended inside mountPhone; shares the original design's UI functions.
let liveState=null, activeRole=null, histories={}, unread={}, applying=false,typingStates={};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const extra=uiDocument.createElement('style');
extra.textContent=':host{display:block;color:#493126;font-family:Microsoft YaHei,sans-serif;--ink:#493126;--muted:#86746a;--screen:#f8f3df}.device{width:350px;margin:0}.screen{height:640px;min-height:640px}.chat-composer button{cursor:pointer}.chat-bubble{white-space:pre-wrap;overflow-wrap:anywhere}.jp-live-note{padding:8px;font-size:11px;color:#72574e}.jp-notify{position:absolute;z-index:99;top:42px;left:12px;right:12px;padding:10px;border-radius:14px;background:#fff3e8;box-shadow:0 4px 15px #55332244;display:none}.jp-notify.show{display:block}';uiRoot.append(extra);
const notice=uiDocument.createElement('div');notice.className='jp-notify';$('.screen').append(notice);
extra.textContent+='#chatApp{background-color:#59736b}.chat-message-time{opacity:.95}';
extra.textContent+=`#home .apps{row-gap:8px;margin-bottom:0}#home .apps .jp-settings-icon{display:grid;place-items:center}#home .apps .jp-settings-icon svg{width:48px;height:48px;filter:drop-shadow(0 3px 0 #523b3b55)}.jp-collapse{padding:0 2px;border:0;background:none;color:inherit;font-size:19px;cursor:pointer;line-height:14px}.status{touch-action:none;cursor:grab}.jp-home-key{position:absolute;z-index:110;bottom:5px;left:40%;width:20%;height:10px;padding:3px 0;border:0;background:none;cursor:pointer}.jp-home-key:after{content:'';display:block;height:4px;border-radius:4px;background:#bc8297;box-shadow:0 1px 2px #fff9}#jpSettingsApp{background:#fff5eb;color:#5c4547}#jpSettingsApp .app-head{background:#f9e1e7}#jpSettingsApp .app-head b{font-size:16px}#jpSettingsApp .jp-settings-status{font-size:11px;line-height:1.4;padding:8px 12px;background:#f4e8de;color:#775b56;overflow-wrap:anywhere}#jpSettingsApp .app-body{padding:0 12px 24px}#jpSettingsApp label{display:block;font-size:12px;line-height:1.5;margin:11px 0}#jpSettingsApp input:not([type=checkbox]),#jpSettingsApp textarea{display:block;box-sizing:border-box;width:100%;margin-top:5px;padding:9px;border:1px solid #e0bec1;border-radius:10px;background:#fffdfa;color:#533e3e;font:12px Microsoft YaHei,sans-serif}#jpSettingsApp input[type=checkbox]{margin-left:10px;accent-color:#ad718c}#jpSettingsApp textarea{min-height:120px;resize:vertical}#jpSettingsApp .app-body>button{display:block;width:100%;margin:8px 0;padding:10px;border:1px solid #e0b6bd;border-radius:11px;background:#f6dbe2;color:#69485c;font:12px Microsoft YaHei,sans-serif;cursor:pointer}#jpSettingsApp button:disabled{opacity:.5}#jpSettingsApp h3{font-size:16px;margin:12px 0 6px}#jpSettingsApp p{font-size:11px;line-height:1.7}.jp-lore-info{padding:9px;background:#ecedd8;border-radius:9px;color:#536448}`;
const settingsIcon=uiDocument.createElement('button');settingsIcon.type='button';settingsIcon.className='app-icon';settingsIcon.setAttribute('aria-label','设置');settingsIcon.innerHTML='<span class="icon-box jp-settings-icon"><svg viewBox="0 0 32 32" shape-rendering="crispEdges" aria-hidden="true"><path fill="#674b60" d="M12 1h8v5h5v5h5v10h-5v5h-5v5h-8v-5H7v-5H2V11h5V6h5z"/><path fill="#bd8f9e" d="M13 3h6v5h6v5h3v6h-5v6h-4v4h-6v-5H8v-5H4v-6h5V8h4z"/><path fill="#f7d5d8" d="M13 5h4v6h7v4h-5v8h-4v-5H9v-5h4z"/><path fill="#674b60" d="M12 11h9v11h-9z"/><path fill="#fff5ce" d="M14 13h5v6h-5z"/></svg></span><small>设置</small>';$('.apps').append(settingsIcon);settingsIcon.onclick=()=>bridge.openSettings();
const settingsApp=uiDocument.createElement('section');settingsApp.id='jpSettingsApp';settingsApp.className='app';settingsApp.innerHTML='<header class="app-head"><button class="back" aria-label="设置返回桌面">‹</button><b>设置</b><span>JUNIMO POCKET</span></header><div class="jp-settings-status" role="status">请设置 API，再启用正文同步</div><div class="app-body jp-settings-body"></div>';$('.screen').append(settingsApp);
function goHome(){$$('.app.active').forEach(e=>e.classList.remove('active'));$('#screen').classList.remove('app-open');$('#home').style.display='flex';}
settingsApp.querySelector('.back').onclick=goHome;
const collapse=uiDocument.createElement('button');collapse.className='jp-collapse';collapse.type='button';collapse.setAttribute('aria-label','收起手机');collapse.title='收起手机';collapse.textContent='⌄';collapse.onclick=()=>bridge.collapse();$('.device').append(collapse);
const homeKey=uiDocument.createElement('button');homeKey.type='button';homeKey.className='jp-home-key';homeKey.setAttribute('aria-label','返回手机桌面');homeKey.onclick=goHome;$('.screen').append(homeKey);
extra.textContent+='.jp-collapse{position:absolute;top:5px;right:22px;z-index:1000;width:25px;height:22px;border-radius:10px;background:#f3c5d7;color:#684052;pointer-events:auto}.speaker{z-index:999;pointer-events:auto;cursor:grab;touch-action:none}.device{touch-action:auto}.chat-composer{flex-wrap:wrap}.chat-composer .jp-real-send{width:auto;flex:0 0 auto;font-size:11px;padding:7px}.jp-delivery{display:block;text-align:right;font-size:9px;opacity:.65}';
const originalSync=sync;
cropDays=function(crop){const row=[...$$('.sale-row[data-kind="seed"]')].find(r=>r.dataset.name.replace(/种子$/,'')===crop);const days=Number(row?.dataset.days);return Number.isFinite(days)&&days>0?days:'';};
sync=function(){originalSync();if(liveState){$('#bagCapacity').textContent=liveState.inventory.length+' / '+liveState.capacity+' 格';}if(!applying)bridge.draftChanged?.(captureDraft());};
function capturePlots(){return [...$$('#field .soil')].map(s=>({crop:s.dataset.crop||'',days:s.dataset.days===''?null:Number(s.dataset.days),wet:s.classList.contains('wet'),fertilizer:s.dataset.fertilizer||''}));}
function captureDraft(){return {actions:[...actions],plots:capturePlots()};}
const initial={gold:0,capacity:24,calendar:{season:'未确认',day:0,year:0,time:'--:--',weather:'未确认',weekday:''},inventory:[],plots:Array.from({length:24},()=>({crop:'',days:null,wet:false,fertilizer:''})),relationships:Object.fromEntries(chatRoles.map(r=>[r.id,0])),locations:{},quests:[],animals:[],buildings:[],calendarEvents:[],notes:''};
function drawPlots(plots){$('#field').replaceChildren();plots.forEach(p=>{makeSoil(p.crop,p.wet,false,p.days);const s=$$('#field .soil')[$$('#field .soil').length-1];s.dataset.fertilizer=p.fertilizer||'';s.dataset.originalFertilizer=p.fertilizer||'';s.dataset.days=p.days==null?'':String(p.days);if(p.stage&&p.stage!=='mature'&&s.dataset.days==='0')s.dataset.days='';s.dataset.originalDays=s.dataset.days;renderSoil(s);});updateFieldInfo();}
function drawInventory(){
  $('#bagList').innerHTML=liveState.inventory.map(r=>'<div class="row sale-row" data-name="'+esc(r.name)+'" data-count="'+r.count+'" data-price="'+(r.price||0)+'" data-price-unknown="'+(r.priceUnknown?'1':'0')+'" data-kind="'+(r.kind||'item')+'" data-days="'+(r.days||0)+'" data-qty="1"><div class="main"><span class="bag-select"></span><div><h3>'+esc(r.name)+' <span class="item-count">×'+r.count+'</span></h3><div class="sub">'+(r.kind==='seed'?(r.days||'?')+' 天成熟 · ':'')+(r.priceUnknown?'价格未知':(r.price||0)+'g / 个')+'</div></div><div class="item-tools"><button class="qty-step" data-d="-1">−</button><span class="qty-num">1</span><button class="qty-step" data-d="1">＋</button><button class="btn sell-one">出售</button></div></div></div>').join('');
  $$('.qty-step').forEach(b=>b.onclick=()=>{const r=b.closest('.sale-row');const q=Math.max(1,Math.min(+r.dataset.count,+r.dataset.qty+ +b.dataset.d));r.dataset.qty=q;r.querySelector('.qty-num').textContent=q;});
  $$('.sell-one').forEach(b=>b.onclick=()=>{const r=b.closest('.sale-row');if(+r.dataset.count===0)return toast('物品数量为零');if(r.dataset.priceUnknown==='1')return toast('售价未知，请先确认价格');const a='出售'+r.dataset.name+'×'+r.dataset.qty+'（'+(+r.dataset.qty*+r.dataset.price)+'g）';if(r.dataset.saleAction){removeExactAction(r.dataset.saleAction);r.dataset.saleAction='';}else{actions.push(a);r.dataset.saleAction=a;}sync();});
  $$('.sale-row').forEach(r=>r.onclick=e=>{if(selecting&&!e.target.closest('button'))r.classList.toggle('batch-on');});
}
rebuildFieldState=function(){if(!liveState)return;drawPlots(liveState.plots);for(const a of actions){let m=a.match(/第(\d+)格/);if(!m)continue;const i=+m[1]-1;if(a.startsWith('扩充')){if(!$$('#field .soil')[i])makeSoil();continue;}const s=$$('#field .soil')[i];if(!s)continue;if(a.includes('播种')){s.dataset.crop=a.split('播种')[1];s.dataset.days=cropDays(s.dataset.crop);}if(a.includes('浇水'))s.classList.add('wet');if(a.includes('施用'))s.dataset.fertilizer=a.split('施用')[1];if(a.startsWith('收获')||a.startsWith('铲除')){s.dataset.crop='';s.dataset.days='';}renderSoil(s);}updateFieldInfo();};
$('#bagUpgrade').onclick=()=>{const capacity=liveState.capacity+12;if(actions.some(a=>a.startsWith('扩充背包')))return toast('本轮已安排扩充');if(finance().balance<2000)return toast('金币不足 2000g');toggle('扩充背包至'+capacity+'格（支出2000g）');};
normalizeBagUpgrades=function(){};
function messageMarkup(m){if(m.type!=='voice')return esc(m.text);const duration=m.duration||Math.max(1,Math.ceil(m.text.length/4));return '<button class="jp-voice" aria-label="模拟语音，点击展开或收起文字"><span class="jp-wave">▂ ▅ ▃ ▇ ▄ ▆ ▂</span><b>'+duration+'″</b><small>转文字</small></button><div class="jp-transcript">'+esc(m.text)+'</div>';}
renderChatRoom=function(role){activeRole=role;unread[role.id]=false;bridge.read?.(role.id);const body=$('#chatRoom .chat-room-body');$('#chatRoomName').textContent=role.name;const messages=histories[role.id]||[];body.classList.add('has-messages');body.innerHTML=messages.length?messages.map(m=>{const speaker=chatRoles.find(r=>r.id===m.speakerId)||role;return '<div class="chat-message '+(m.from==='me'?'outgoing':'incoming')+'">'+(m.from==='me'?'':'<span class="chat-avatar">'+threadPortrait(speaker)+'</span>')+'<div class="chat-message-content">'+(role.members&&m.from!=='me'?'<small class="jp-speaker">'+esc(speaker.name)+'</small>':'')+'<div class="chat-bubble">'+messageMarkup(m)+'</div><span class="chat-message-time">'+esc(m.time||'')+(m.from==='me'?' · '+({queued:'✓',sending:'···',failed:'!',sent:'✓✓'}[m.status]||'✓✓'):'')+'</span></div></div>';}).join(''):'<div class="jp-live-note">写下第一条消息，和'+esc(role.name)+'聊天吧。</div>';if(typingStates[role.id]){const tip=uiDocument.createElement('div');tip.className='jp-typing';tip.setAttribute('role','status');tip.innerHTML='<span>'+esc(typingStates[role.id])+'</span><i></i><i></i><i></i>';body.append(tip);}body.querySelectorAll('.jp-voice').forEach(b=>b.onclick=()=>{b.classList.add('playing');setTimeout(()=>b.classList.remove('playing'),1200);const transcript=b.nextElementSibling;transcript.hidden=!transcript.hidden;});body.scrollTop=body.scrollHeight;};
renderChatThreads=function(){const query=$('#chatSearch').value.trim();$('#chatThreads').innerHTML=threadRoles.filter(r=>(r.name+r.job).includes(query)).map(r=>{const last=histories[r.id]?.at(-1);return '<button class="chat-thread" data-role="'+r.id+'"><span class="chat-avatar">'+threadPortrait(r)+'</span><span class="chat-thread-main"><span class="chat-thread-name">'+r.name+(unread[r.id]?' ●':'')+'<em>'+r.job+'</em></span><span class="chat-thread-preview">'+esc(typingStates[r.id]||(last?.type==='voice'?'[语音] ':'' )+(last?.text?.slice(0,42)||'尚无消息'))+'</span></span><span class="chat-thread-end">›</span></button>';}).join('');$$('#chatThreads .chat-thread').forEach(b=>b.onclick=()=>{renderChatRoom(threadRoles.find(r=>r.id===b.dataset.role));showChatHelp();$('#chatListView').hidden=true;$('#chatRoom').hidden=false;$('#chatApp').classList.add('chat-room-open');});};
// Replace the previously captured search callback.
$('#chatSearch').addEventListener('input',()=>queueMicrotask(renderChatThreads));

const groupRoles=[{id:'group-all',name:'月亮谷邻里群',job:'全员群聊',members:chatRoles.map(r=>r.id)},{id:'group-twins',name:'莱恩 · 莱尔 · 我',job:'三人群聊',members:['11','10']}];
const threadRoles=[...groupRoles,...chatRoles];
function threadPortrait(role){return role.members?'<span class="jp-group-avatar">♧</span>':portraitMarkup(role);}
function showChatHelp(){if(localStorage.getItem('junimo_pocket_chat_help_v6'))return;const dialog=uiDocument.createElement('div');dialog.className='jp-review';dialog.innerHTML='<div class="jp-review-card"><h3>像手机一样聊天</h3><p>＋：先发一个气泡，不触发回复。可以连续发好几条。</p><p>➤：把当前输入一起发出，让对方回复前面累积的消息。</p><p>私聊只有选中的角色；群聊会在每条消息上显示发言人。</p><button>知道了</button></div>';$('.screen').append(dialog);dialog.querySelector('button').onclick=()=>{localStorage.setItem('junimo_pocket_chat_help_v6','1');dialog.remove();};}
const composer=$('.chat-composer input'),sendButton=$('.chat-composer button');composer.disabled=false;sendButton.disabled=false;sendButton.textContent='＋';sendButton.title='虚拟发送：只发气泡' ;sendButton.setAttribute('aria-label','虚拟发送');
const realSend=uiDocument.createElement('button');realSend.className='jp-real-send';realSend.textContent='➤';realSend.title='真正发送：触发回复';realSend.setAttribute('aria-label','真正发送');$('.chat-composer').append(realSend);
const voiceButton=uiDocument.createElement('button');voiceButton.className='jp-voice-compose';voiceButton.setAttribute('aria-label','发送模拟语音');voiceButton.title='模拟语音（文字输入）';voiceButton.innerHTML='<svg viewBox="0 0 24 24" width="19" height="19" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><rect x="8" y="2" width="8" height="13" rx="4"/><path d="M5 10v2a7 7 0 0 0 14 0v-2M12 19v3M8 22h8"/></svg>';$('.chat-composer').insertBefore(voiceButton,composer);
voiceButton.onclick=()=>{if(!activeRole)return;const role=activeRole,dialog=uiDocument.createElement('div');dialog.className='jp-review';dialog.innerHTML='<div class="jp-review-card"><h3>模拟语音</h3><p>输入想说的话，发出后显示语音气泡与转文字，不使用麦克风。</p><textarea aria-label="模拟语音内容" placeholder="想对TA说什么…"></textarea><div><button class="jp-voice-cancel">取消</button><button class="jp-voice-queue" title="先发气泡">＋</button><button class="jp-voice-send" title="发送并触发回复">➤</button></div><p class="jp-review-error"></p></div>';$('.screen').append(dialog);dialog.querySelector('.jp-voice-cancel').onclick=()=>dialog.remove();async function submit(real){const input=dialog.querySelector('textarea'),text=input.value.trim();if(!text)return;dialog.querySelectorAll('button').forEach(b=>b.disabled=true);try{await bridge.queueBubble(role,{type:'voice',text});dialog.remove();if(real)await bridge.send(role);}catch(e){if(dialog.isConnected){dialog.querySelector('.jp-review-error').textContent=e.message;dialog.querySelectorAll('button').forEach(b=>b.disabled=false);}else toast(e.message);}}dialog.querySelector('.jp-voice-queue').onclick=()=>submit(false);dialog.querySelector('.jp-voice-send').onclick=()=>submit(true);};
async function stageBubble(){if(!activeRole||!composer.value.trim())return;const text=composer.value.trim(),role=activeRole;composer.value='';try{await bridge.queueBubble(role,text);}catch(e){composer.value=text;toast(e.message);}}
sendButton.onclick=stageBubble;composer.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.isComposing){e.preventDefault();stageBubble();}});
realSend.onclick=async()=>{if(!activeRole)return;const role=activeRole;realSend.disabled=true;try{await stageBubble();await bridge.send(role);}catch(e){toast(e.message);}finally{realSend.disabled=false;}};
$('#send').textContent='放入酒馆输入框';$('#send').onclick=()=>{if(!actions.length)return toast('行动篮是空的');if(finance().balance<0)return toast('预计金币不足');try{bridge.compose('【今日农场行动】'+actions.join('；')+'。农田预览：'+fieldSummary()+'。请根据实际演绎结果更新农场状态。');$('#summaryModal').classList.remove('show');toast('已放入酒馆输入框，发送正文后结算');}catch(e){toast(e.message);}};
$('.chat-affection-head p').textContent='每颗心代表 250 点 · 随正文更新';
// Sample gift inventory is replaced with current inventory each time.
$$('.gift-open').forEach(b=>b.onclick=()=>{giftPerson=b.dataset.person;giftChoice='';$('#giftList').innerHTML=liveState.inventory.filter(x=>x.count>0).map(x=>'<button class="gift" data-gift="'+esc(x.name)+'">'+esc(x.name)+' ×'+x.count+'</button>').join('');$$('#giftList .gift').forEach(g=>g.onclick=()=>{giftChoice=g.dataset.gift;$$('#giftList .gift').forEach(x=>x.classList.toggle('selected',x===g));});$('#giftModal').classList.add('show');});

// Keep the original decorative shells. Only their data-bearing children change.
function bindGiftButtons(){$$('.gift-open').forEach(b=>b.onclick=()=>{giftPerson=b.dataset.person;giftChoice='';$('#giftList').innerHTML=liveState.inventory.filter(x=>x.count>0).map(x=>'<button class="gift" data-gift="'+esc(x.name)+'">'+esc(x.name)+' ×'+x.count+'</button>').join('');$$('#giftList .gift').forEach(g=>g.onclick=()=>{giftChoice=g.dataset.gift;$$('#giftList .gift').forEach(x=>x.classList.toggle('selected',x===g));});$('#giftModal').classList.add('show');});}
function update(state,threads,flags,draft){applying=true;try{
 liveState=structuredClone(state);baseFunds=state.gold;actions.splice(0,actions.length,...(draft?.actions||[]));drawInventory();drawPlots(draft?.plots||state.plots);
 const d=state.calendar,date=d.day?d.season+' '+d.day+' 日':'日期未确认';$('.home-title h1').textContent=d.time;$('.date-widget').textContent=[d.weather,date,d.weekday].filter(Boolean).join(' · ');$('.status span').textContent=d.time;$('.status .weather').textContent=date;
 $('#dateApp .app-head span').textContent=date;
 $('#dateApp .app-body').innerHTML='<div class="row calendar"><div class="date"><b>今天</b><strong>'+esc(d.day||'—')+'</strong></div><div><h3>'+esc(date)+'</h3><div class="sub">'+esc(d.weekday)+' · '+esc(d.time)+' · '+esc(d.weather)+'</div></div></div>'+(state.calendarEvents||[]).map(e=>'<div class="row calendar"><div class="date"><b>'+esc(e.season||d.season)+'</b><strong>'+e.day+'</strong></div><div><h3>'+esc(e.name)+'</h3><div class="sub">'+esc(e.detail||'')+'</div>'+(e.person?'<button class="btn gift-open" data-person="'+esc(e.person)+'">选择礼物</button>':'')+'</div></div>').join('')+'<p class="tip">生日、节日和日程随正文变量更新。</p>';bindGiftButtons();
 $('#quest .app-head span').textContent=state.quests.length+' 项';$('#quest .app-body .list').innerHTML=state.quests.map((q,i)=>'<div class="row quest" data-q="'+i+'"><div class="main"><div><h3>'+esc(q.name)+'</h3><div class="sub">'+esc(q.status)+'</div>'+(Number.isFinite(q.progress)?'<div class="progress"><i style="width:'+Math.max(0,Math.min(100,q.progress))+'%"></i></div>':'')+'</div><span class="tag pink">'+esc(q.deadline||'查看详情')+'</span></div></div>').join('')||'<p class="tip">尚无任务。</p>';
 $$('[data-q]').forEach(b=>b.onclick=()=>{const q=state.quests[+b.dataset.q];currentQuest='完成任务：'+q.name;$('#questTitle').textContent=q.name;$('#questDetail').textContent=[q.detail,q.goal?'目标：'+q.goal:'',q.status,q.deadline?'期限：'+q.deadline:''].filter(Boolean).join('\n\n');$('#questReward').textContent=q.reward||'奖励尚未确认';$('#questAdd').textContent=actions.includes(currentQuest)?'取消提交':'提交任务';$('#questModal').classList.add('show');});
 const count=name=>state.inventory.filter(x=>x.name===name).reduce((n,x)=>n+x.count,0);const buildings=state.buildings||[];const lists=$$('#farm .farm-text-list');lists[0].innerHTML=buildings.map(b=>'<div class="row"><div class="main"><div><h3>'+esc(b.name)+' <span class="farm-status">'+esc(b.status)+'</span></h3>'+(Number.isFinite(b.progress)?'<div class="progress"><i style="width:'+Math.max(0,Math.min(100,b.progress))+'%"></i></div>':'')+'</div></div></div>').join('')||'<p class="tip">尚无已确认建筑。</p>';
 lists[1].innerHTML=[{name:'畜棚',price:6000,needs:{木材:350,石头:150}},{name:'鱼塘',price:5000,needs:{石头:200,海草:5}}].map(b=>{const enough=state.gold>=b.price&&Object.entries(b.needs).every(([k,v])=>count(k)>=v);return '<div class="row"><div class="main"><div><h3>'+b.name+'</h3><p class="farm-description">为农场添点新东西。</p><div class="farm-materials">'+Object.entries(b.needs).map(([k,v])=>'<span class="'+(count(k)<v?'shortage':'')+'">'+k+' <b>'+count(k)+' / '+v+'</b></span>').join('')+'</div></div><span class="farm-price">'+b.price+'g</span><button class="btn" data-build="'+b.name+'" data-price="'+b.price+'" '+(enough?'':'disabled')+'>'+(enough?'购买':'材料不足')+'</button></div></div>';}).join('');$$('[data-build]').forEach(b=>b.onclick=()=>toggle('购买并建造'+b.dataset.build+'（支出'+b.dataset.price+'g）'));
 const recipes=[{name:'木箱',needs:{木材:50}},{name:'稻草人',needs:{木材:50,煤炭:1,纤维:20}},{name:'熔炉',needs:{铜矿石:20,石头:25}},{name:'蜂房',needs:{煤炭:8,铁锭:1}}];$('#craft .app-head span').textContent='材料来自背包';$('#craft .recipe-grid').innerHTML=recipes.map(r=>{const max=Math.min(...Object.entries(r.needs).map(([k,n])=>Math.floor(count(k)/n)));return '<div class="recipe '+(max?'':'locked')+'" data-recipe="'+r.name+'" data-max="'+max+'"><h3>'+r.name+'</h3><div class="materials">'+Object.entries(r.needs).map(([k,n])=>k+' '+count(k)+' / '+n).join(' · ')+'</div><div class="'+(max?'can':'no')+'">'+(max?'最多制作 '+max+' 个':'材料不足')+'</div></div>';}).join('');$$('[data-recipe]').forEach(r=>r.onclick=()=>{if(!+r.dataset.max)return;craftName=r.dataset.recipe;craftMax=+r.dataset.max;craftQty=1;$('#craftTitle').textContent='制作 '+craftName;$('#craftMaterials').textContent=r.querySelector('.materials').textContent;drawCraftQty();$('#craftModal').classList.add('show');});
 $('#animal .app-head span').textContent=state.animals.length+' 位伙伴';$('#animal .animal-scene').hidden=!state.animals.length;$('#animal .app-body > .list').innerHTML=state.animals.map(a=>'<div class="animal-unit"><div class="row"><div class="main"><div><h3>'+esc(a.name)+'</h3><div class="sub">'+esc(a.status)+'</div></div></div></div><div class="animal-actions"><button class="btn" data-animal="'+esc(a.name)+'">安排照料</button></div></div>').join('');$$('[data-animal]').forEach(b=>b.onclick=()=>toggle('照料'+b.dataset.animal));
 chatRoles.forEach(r=>r.friendship=state.relationships[r.id]||0);Object.keys(mapNpcLocations).forEach(k=>delete mapNpcLocations[k]);Object.assign(mapNpcLocations,state.locations);mapHasLiveLocations=true;renderMapNpcLocations();updateMapLocationCaption();
 histories=threads;unread=flags;renderChatThreads();if(activeRole&&!$('#chatRoom').hidden)renderChatRoom(activeRole);renderChatAffection();renderSeedToolbar();sync();
}finally{applying=false;}}
function reviewState(text,summary,onConfirm){const dialog=uiDocument.createElement('div');dialog.className='jp-review';dialog.innerHTML='<div class="jp-review-card"><h3>核对变量修改</h3><p class="jp-review-summary"></p><textarea aria-label="待确认的文字变量"></textarea><p class="jp-review-error" role="status"></p><div><button class="jp-review-cancel">取消</button><button class="jp-review-confirm">确认应用</button></div></div>';dialog.querySelector('.jp-review-summary').textContent=summary;dialog.querySelector('textarea').value=text;dialog.querySelector('.jp-review-cancel').onclick=()=>dialog.remove();dialog.querySelector('.jp-review-confirm').onclick=async()=>{const b=dialog.querySelector('.jp-review-confirm');b.disabled=true;try{await onConfirm(dialog.querySelector('textarea').value);dialog.remove();}catch(e){dialog.querySelector('.jp-review-error').textContent=e.message;}finally{b.disabled=false;}};$('.screen').append(dialog);}
extra.textContent+='.chat-composer{flex-wrap:nowrap;gap:8px}.chat-composer input{min-width:0;flex:1 1 0;width:0}.chat-composer button,.chat-composer .jp-real-send{box-sizing:border-box;width:34px;height:34px;min-width:34px;flex:0 0 34px;padding:0;font-size:21px;line-height:30px;white-space:nowrap;display:grid;place-items:center}.jp-group-avatar{display:grid;place-items:center;width:100%;height:100%;background:#baa1c7;color:white;font-size:30px}.jp-speaker{display:block;font-size:10px;margin-bottom:4px;color:#fff}.jp-review{position:absolute;inset:0;z-index:1500;background:#31293999;display:flex;align-items:center;padding:12px}.jp-review-card{box-sizing:border-box;width:100%;max-height:90%;overflow:auto;padding:15px;border-radius:20px;background:#fff2f5;color:#604a58;font-size:12px}.jp-review-card h3{margin:0 0 10px}.jp-review-card textarea{box-sizing:border-box;width:100%;height:280px;padding:9px;background:#fffdfb;color:#44323b;border:1px solid #d5afc1;border-radius:10px;font:12px Microsoft YaHei;white-space:pre;overflow:auto}.jp-review-card button{padding:9px 14px;margin:8px 5px 0 0;border:0;border-radius:12px;background:#e6bbcd;color:#513448}.jp-review-error{color:#ac344e}';
extra.textContent+='.chat-composer{gap:5px}.jp-voice{display:flex;align-items:center;gap:10px;min-width:135px;max-width:100%;padding:4px 0;border:0;background:none;color:inherit;cursor:pointer}.jp-voice small{font-size:9px;opacity:.7}.jp-wave{letter-spacing:2px}.jp-transcript{border-top:1px solid #ffffff40;padding-top:7px;margin-top:6px;font-size:12px;line-height:1.5;white-space:pre-wrap}.jp-typing{display:flex;align-items:center;gap:5px;margin:8px 0 12px;padding:10px 12px;color:#fff;background:#ffffff22;border-radius:16px;width:max-content;font-size:11px}.jp-typing i{width:4px;height:4px;border-radius:50%;background:currentColor;animation:jp-dot 1.1s infinite}.jp-typing i:nth-child(3){animation-delay:.18s}.jp-typing i:nth-child(4){animation-delay:.36s}.jp-voice.playing .jp-wave{animation:jp-dot .5s infinite}@keyframes jp-dot{0%,80%,100%{opacity:.35;transform:translateY(0)}40%{opacity:1;transform:translateY(-3px)}}@media(prefers-reduced-motion:reduce){.jp-typing i,.jp-voice.playing .jp-wave{animation:none}}';
return {setTyping(id,label){if(label)typingStates[id]=label;else delete typingStates[id];renderChatThreads();if(activeRole&&activeRole.id===id&&!$('#chatRoom').hidden)renderChatRoom(activeRole);},clearTyping(){typingStates={};renderChatThreads();if(activeRole&&!$('#chatRoom').hidden)renderChatRoom(activeRole);},reviewState,initial,mapAnchors:mapLocationAnchors,roles:chatRoles.map(({id,name,job})=>({id,name,job})),update,toast,home:goHome,settingsBody:settingsApp.querySelector('.jp-settings-body'),statusLine:settingsApp.querySelector('.jp-settings-status'),dragHandles:[$('.status'),$('.speaker'),$('.device')],showSettings(){goHome();$('#home').style.display='none';$('#screen').classList.add('app-open');settingsApp.classList.add('active');},setStatus(text){settingsApp.querySelector('.jp-settings-status').textContent=text;$('.home-title p').textContent=text;},setLoreStatus(text){const info=settingsApp.querySelector('.jp-lore-info');if(info)info.textContent=text;},notify(text){notice.textContent=text;notice.classList.add('show');setTimeout(()=>notice.classList.remove('show'),6000);},closeRoom(){activeRole=null;notice.classList.remove('show');$('#chatRoomBack').click();},getDraft:captureDraft};
