// Appended inside mountPhone; shares the original design's UI functions.
let liveState=null, activeRole=null, histories={}, unread={}, applying=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const extra=uiDocument.createElement('style');
extra.textContent=':host{display:block;color:#493126;font-family:Microsoft YaHei,sans-serif;--ink:#493126;--muted:#86746a;--screen:#f8f3df}.device{width:350px;margin:0}.screen{height:640px;min-height:640px}.chat-composer button{cursor:pointer}.chat-bubble{white-space:pre-wrap;overflow-wrap:anywhere}.jp-live-note{padding:8px;font-size:11px;color:#72574e}.jp-notify{position:absolute;z-index:99;top:42px;left:12px;right:12px;padding:10px;border-radius:14px;background:#fff3e8;box-shadow:0 4px 15px #55332244;display:none}.jp-notify.show{display:block}';uiRoot.append(extra);
const notice=uiDocument.createElement('div');notice.className='jp-notify';$('.screen').append(notice);
extra.textContent+='#chatApp{background-color:#59736b}.chat-message-time{opacity:.95}';
extra.textContent+=`#home .apps{row-gap:8px;margin-bottom:0}#home .apps .jp-settings-icon{display:grid;place-items:center}#home .apps .jp-settings-icon svg{width:48px;height:48px;filter:drop-shadow(0 3px 0 #523b3b55)}.jp-collapse{padding:0 2px;border:0;background:none;color:inherit;font-size:19px;cursor:pointer;line-height:14px}.status{touch-action:none;cursor:grab}.jp-home-key{position:absolute;z-index:110;bottom:5px;left:40%;width:20%;height:10px;padding:3px 0;border:0;background:none;cursor:pointer}.jp-home-key:after{content:'';display:block;height:4px;border-radius:4px;background:#bc8297;box-shadow:0 1px 2px #fff9}#jpSettingsApp{background:#fff5eb;color:#5c4547}#jpSettingsApp .app-head{background:#f9e1e7}#jpSettingsApp .app-head b{font-size:16px}#jpSettingsApp .jp-settings-status{font-size:11px;line-height:1.4;padding:8px 12px;background:#f4e8de;color:#775b56;overflow-wrap:anywhere}#jpSettingsApp .app-body{padding:0 12px 24px}#jpSettingsApp label{display:block;font-size:12px;line-height:1.5;margin:11px 0}#jpSettingsApp input:not([type=checkbox]),#jpSettingsApp textarea{display:block;box-sizing:border-box;width:100%;margin-top:5px;padding:9px;border:1px solid #e0bec1;border-radius:10px;background:#fffdfa;color:#533e3e;font:12px Microsoft YaHei,sans-serif}#jpSettingsApp input[type=checkbox]{margin-left:10px;accent-color:#ad718c}#jpSettingsApp textarea{min-height:120px;resize:vertical}#jpSettingsApp .app-body>button{display:block;width:100%;margin:8px 0;padding:10px;border:1px solid #e0b6bd;border-radius:11px;background:#f6dbe2;color:#69485c;font:12px Microsoft YaHei,sans-serif;cursor:pointer}#jpSettingsApp button:disabled{opacity:.5}#jpSettingsApp h3{font-size:16px;margin:12px 0 6px}#jpSettingsApp p{font-size:11px;line-height:1.7}.jp-lore-info{padding:9px;background:#ecedd8;border-radius:9px;color:#536448}`;
const settingsIcon=uiDocument.createElement('button');settingsIcon.type='button';settingsIcon.className='app-icon';settingsIcon.setAttribute('aria-label','设置');settingsIcon.innerHTML='<span class="icon-box jp-settings-icon"><svg viewBox="0 0 32 32" shape-rendering="crispEdges" aria-hidden="true"><path fill="#674b60" d="M12 1h8v5h5v5h5v10h-5v5h-5v5h-8v-5H7v-5H2V11h5V6h5z"/><path fill="#bd8f9e" d="M13 3h6v5h6v5h3v6h-5v6h-4v4h-6v-5H8v-5H4v-6h5V8h4z"/><path fill="#f7d5d8" d="M13 5h4v6h7v4h-5v8h-4v-5H9v-5h4z"/><path fill="#674b60" d="M12 11h9v11h-9z"/><path fill="#fff5ce" d="M14 13h5v6h-5z"/></svg></span><small>设置</small>';$('.apps').append(settingsIcon);settingsIcon.onclick=()=>bridge.openSettings();
const settingsApp=uiDocument.createElement('section');settingsApp.id='jpSettingsApp';settingsApp.className='app';settingsApp.innerHTML='<header class="app-head"><button class="back" aria-label="设置返回桌面">‹</button><b>设置</b><span>JUNIMO POCKET</span></header><div class="jp-settings-status" role="status">请设置 API，再启用正文同步</div><div class="app-body jp-settings-body"></div>';$('.screen').append(settingsApp);
function goHome(){$$('.app.active').forEach(e=>e.classList.remove('active'));$('#screen').classList.remove('app-open');$('#home').style.display='flex';}
settingsApp.querySelector('.back').onclick=goHome;
const collapse=uiDocument.createElement('button');collapse.className='jp-collapse';collapse.type='button';collapse.setAttribute('aria-label','收起手机');collapse.title='收起手机';collapse.textContent='⌄';collapse.onclick=()=>bridge.collapse();$('.status span:last-child').replaceChildren(collapse);
const homeKey=uiDocument.createElement('button');homeKey.type='button';homeKey.className='jp-home-key';homeKey.setAttribute('aria-label','返回手机桌面');homeKey.onclick=goHome;$('.screen').append(homeKey);
const originalSync=sync;
sync=function(){originalSync();if(liveState){$('#bagCapacity').textContent=liveState.inventory.length+' / '+liveState.capacity+' 格';}if(!applying)bridge.draftChanged?.(captureDraft());};
function capturePlots(){return [...$$('#field .soil')].map(s=>({crop:s.dataset.crop||'',days:s.dataset.days===''?null:Number(s.dataset.days),wet:s.classList.contains('wet'),fertilizer:s.dataset.fertilizer||''}));}
function captureDraft(){return {actions:[...actions],plots:capturePlots()};}
const initial={gold:0,capacity:24,calendar:{season:'未确认',day:0,year:0,time:'--:--',weather:'未确认',weekday:''},inventory:[],plots:Array.from({length:24},()=>({crop:'',days:null,wet:false,fertilizer:''})),relationships:Object.fromEntries(chatRoles.map(r=>[r.id,0])),locations:{},quests:[],animals:[],buildings:[],notes:''};
function drawPlots(plots){$('#field').replaceChildren();plots.forEach(p=>{makeSoil(p.crop,p.wet,false,p.days);const s=$$('#field .soil')[$$('#field .soil').length-1];s.dataset.fertilizer=p.fertilizer||'';s.dataset.originalFertilizer=p.fertilizer||'';renderSoil(s);});updateFieldInfo();}
function drawInventory(){
  $('#bagList').innerHTML=liveState.inventory.map(r=>'<div class="row sale-row" data-name="'+esc(r.name)+'" data-count="'+r.count+'" data-price="'+(r.price||0)+'" data-kind="'+(r.kind||'item')+'" data-days="'+(r.days||0)+'" data-qty="1"><div class="main"><span class="bag-select"></span><div><h3>'+esc(r.name)+' <span class="item-count">×'+r.count+'</span></h3><div class="sub">'+(r.kind==='seed'?(r.days||'?')+' 天成熟 · ':'')+(r.price||0)+'g / 个</div></div><div class="item-tools"><button class="qty-step" data-d="-1">−</button><span class="qty-num">1</span><button class="qty-step" data-d="1">＋</button><button class="btn sell-one">出售</button></div></div></div>').join('');
  $$('.qty-step').forEach(b=>b.onclick=()=>{const r=b.closest('.sale-row');const q=Math.max(1,Math.min(+r.dataset.count,+r.dataset.qty+ +b.dataset.d));r.dataset.qty=q;r.querySelector('.qty-num').textContent=q;});
  $$('.sell-one').forEach(b=>b.onclick=()=>{const r=b.closest('.sale-row');if(+r.dataset.count===0)return toast('物品数量为零');const a='出售'+r.dataset.name+'×'+r.dataset.qty+'（'+(+r.dataset.qty*+r.dataset.price)+'g）';if(r.dataset.saleAction){removeExactAction(r.dataset.saleAction);r.dataset.saleAction='';}else{actions.push(a);r.dataset.saleAction=a;}sync();});
  $$('.sale-row').forEach(r=>r.onclick=e=>{if(selecting&&!e.target.closest('button'))r.classList.toggle('batch-on');});
}
rebuildFieldState=function(){if(!liveState)return;drawPlots(liveState.plots);for(const a of actions){let m=a.match(/第(\d+)格/);if(!m)continue;const i=+m[1]-1;if(a.startsWith('扩充')){if(!$$('#field .soil')[i])makeSoil();continue;}const s=$$('#field .soil')[i];if(!s)continue;if(a.includes('播种')){s.dataset.crop=a.split('播种')[1];s.dataset.days=cropDays(s.dataset.crop);}if(a.includes('浇水'))s.classList.add('wet');if(a.includes('施用'))s.dataset.fertilizer=a.split('施用')[1];if(a.startsWith('收获')||a.startsWith('铲除')){s.dataset.crop='';s.dataset.days='';}renderSoil(s);}updateFieldInfo();};
$('#bagUpgrade').onclick=()=>{const capacity=liveState.capacity+12;if(actions.some(a=>a.startsWith('扩充背包')))return toast('本轮已安排扩充');if(finance().balance<2000)return toast('金币不足 2000g');toggle('扩充背包至'+capacity+'格（支出2000g）');};
normalizeBagUpgrades=function(){};
renderChatRoom=function(role){activeRole=role;unread[role.id]=false;bridge.read?.(role.id);const body=$('#chatRoom .chat-room-body');$('#chatRoomName').textContent=role.name;const messages=histories[role.id]||[];body.classList.add('has-messages');body.innerHTML=messages.length?messages.map(m=>'<div class="chat-message '+(m.from==='me'?'outgoing':'incoming')+'">'+(m.from==='me'?'':'<span class="chat-avatar">'+portraitMarkup(role)+'</span>')+'<div class="chat-message-content"><div class="chat-bubble">'+esc(m.text)+'</div><span class="chat-message-time">'+esc(m.time||'')+'</span></div></div>').join(''):'<div class="jp-live-note">写下第一条消息，和'+esc(role.name)+'聊天吧。</div>';body.scrollTop=body.scrollHeight;};
renderChatThreads=function(){const query=$('#chatSearch').value.trim();$('#chatThreads').innerHTML=chatRoles.filter(r=>(r.name+r.job).includes(query)).map(r=>{const last=histories[r.id]?.at(-1);return '<button class="chat-thread" data-role="'+r.id+'"><span class="chat-avatar">'+portraitMarkup(r)+'</span><span class="chat-thread-main"><span class="chat-thread-name">'+r.name+(unread[r.id]?' ●':'')+'<em>'+r.job+'</em></span><span class="chat-thread-preview">'+esc(last?.text?.slice(0,42)||'尚无消息')+'</span></span><span class="chat-thread-end">›</span></button>';}).join('');$$('#chatThreads .chat-thread').forEach(b=>b.onclick=()=>{renderChatRoom(chatRoles.find(r=>r.id===b.dataset.role));$('#chatListView').hidden=true;$('#chatRoom').hidden=false;$('#chatApp').classList.add('chat-room-open');});};
// Replace the previously captured search callback.
$('#chatSearch').addEventListener('input',()=>queueMicrotask(renderChatThreads));
const composer=$('.chat-composer input'),sendButton=$('.chat-composer button');composer.disabled=false;sendButton.disabled=false;
async function sendPhoneMessage(){if(!activeRole||!composer.value.trim())return;const text=composer.value.trim(),role=activeRole;sendButton.disabled=true;composer.disabled=true;try{await bridge.send(role,text);composer.value='';}catch(e){toast(e.message);}finally{sendButton.disabled=false;composer.disabled=false;composer.focus();}}
sendButton.onclick=sendPhoneMessage;composer.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.isComposing){e.preventDefault();sendPhoneMessage();}});
$('#send').textContent='放入酒馆输入框';$('#send').onclick=()=>{if(!actions.length)return toast('行动篮是空的');if(finance().balance<0)return toast('预计金币不足');try{bridge.compose('【今日农场行动】'+actions.join('；')+'。农田预览：'+fieldSummary()+'。请根据实际演绎结果更新农场状态。');$('#summaryModal').classList.remove('show');toast('已放入酒馆输入框，发送正文后结算');}catch(e){toast(e.message);}};
$('.chat-affection-head p').textContent='每颗心代表 250 点 · 随正文更新';
// Sample gift inventory is replaced with current inventory each time.
$$('.gift-open').forEach(b=>b.onclick=()=>{giftPerson=b.dataset.person;giftChoice='';$('#giftList').innerHTML=liveState.inventory.filter(x=>x.count>0).map(x=>'<button class="gift" data-gift="'+esc(x.name)+'">'+esc(x.name)+' ×'+x.count+'</button>').join('');$$('#giftList .gift').forEach(g=>g.onclick=()=>{giftChoice=g.dataset.gift;$$('#giftList .gift').forEach(x=>x.classList.toggle('selected',x===g));});$('#giftModal').classList.add('show');});
function update(state,threads,flags,draft){applying=true;try{liveState=structuredClone(state);baseFunds=state.gold;actions.splice(0,actions.length,...(draft?.actions||[]));drawInventory();drawPlots(draft?.plots||state.plots);const d=state.calendar;$('.home-title h1').textContent=d.time;$('.home-title p').textContent='月亮谷 · 随正文同步';$('.date-widget').textContent=[d.weather,d.season+' '+d.day+' 日',d.weekday].filter(Boolean).join(' · ');$('#dateApp .app-head span').textContent=d.season+' '+d.day+' 日';$('#dateApp .app-body').innerHTML='<div class="row"><h3>'+esc(d.season)+' '+d.day+' 日</h3><p>'+esc(d.weather)+' · '+esc(d.time)+'</p></div>'+state.quests.map(q=>'<div class="row"><h3>'+esc(q.name)+'</h3><div class="sub">'+esc(q.status)+'</div></div>').join('');chatRoles.forEach(r=>r.friendship=state.relationships[r.id]||0);Object.keys(mapNpcLocations).forEach(k=>delete mapNpcLocations[k]);Object.assign(mapNpcLocations,state.locations);mapHasLiveLocations=true;renderMapNpcLocations();updateMapLocationCaption();histories=threads;unread=flags;renderChatThreads();if(activeRole&&!$('#chatRoom').hidden)renderChatRoom(activeRole);renderChatAffection();renderSeedToolbar();sync();let info=$('#jp-world-info');if(!info){info=uiDocument.createElement('div');info.id='jp-world-info';info.className='jp-live-note';$('#animal .app-body')?.append(info);}info.textContent=state.animals.map(a=>a.name+'：'+a.status).join('；')||'动物状态尚未在正文中确认；上方为装饰动画。';}finally{applying=false;}}
const updateOriginal=update;
update=function(state,threads,flags,draft){updateOriginal(state,threads,flags,draft);$('.status span').textContent=state.calendar.time;$('.status .weather').textContent=state.calendar.weather+' '+state.calendar.season+' '+state.calendar.day+'日';$('#quest .app-head span').textContent=state.quests.length+' 项';$('#quest .app-body').innerHTML=state.quests.length?state.quests.map(q=>'<div class="row"><h3>'+esc(q.name)+'</h3><p class="sub">'+esc(q.status)+'</p><button class="btn" data-quest="'+esc(q.name)+'">安排提交</button></div>').join(''):'<p class="tip">正文确认任务后会显示在这里。</p>';$$('[data-quest]').forEach(b=>b.onclick=()=>toggle('提交任务：'+b.dataset.quest));$('#animal .app-head span').textContent=state.animals.length+' 位伙伴';$('#animal .app-body > .list').innerHTML=state.animals.map(a=>'<div class="row"><h3>'+esc(a.name)+'</h3><p class="sub">'+esc(a.status)+'</p><button class="btn" data-animal="'+esc(a.name)+'">安排照料</button></div>').join('');$$('[data-animal]').forEach(b=>b.onclick=()=>toggle('照料'+b.dataset.animal));let memo=$('#jp-farm-notes');if(!memo){memo=uiDocument.createElement('div');memo.id='jp-farm-notes';memo.className='row';$('#farm .app-body').prepend(memo);}memo.textContent=state.notes||'农场变化会随正文记录在此。下方建筑、配方为原设计的操作模板，结果以正文为准。';};
const updateLive=update;
update=function(state,threads,flags,draft){
  updateLive(state,threads,flags,draft);
  const count=name=>state.inventory.filter(x=>x.name===name).reduce((n,x)=>n+x.count,0);
  const buildings=state.buildings||[];
  $('#farm .app-body').innerHTML='<div class="farm-group-title">已有建筑</div>'+(buildings.length?buildings.map(b=>'<div class="row"><h3>'+esc(b.name)+'</h3><p>'+esc(b.status)+'</p></div>').join(''):'<p class="tip">尚无已确认建筑。</p>')+'<div class="row">'+esc(state.notes||'农场物品和建设进度会随正文更新。')+'</div><div class="farm-group-title">建筑计划</div>'+[{name:'畜棚',price:6000,needs:{木材:350,石头:150}},{name:'鱼塘',price:5000,needs:{石头:200,海草:5}}].map(b=>{const enough=state.gold>=b.price&&Object.entries(b.needs).every(([k,v])=>count(k)>=v);return '<div class="row"><h3>'+b.name+' · '+b.price+'g</h3><p>'+Object.entries(b.needs).map(([k,v])=>k+' '+count(k)+' / '+v).join(' · ')+'</p><button class="btn" data-build="'+b.name+'" data-price="'+b.price+'" '+(enough?'':'disabled')+'>'+(enough?'安排建设':'金币或材料不足')+'</button></div>';}).join('');
  $$('[data-build]').forEach(b=>b.onclick=()=>toggle('购买并建造'+b.dataset.build+'（支出'+b.dataset.price+'g）'));
  const recipes=[{name:'木箱',needs:{木材:50}},{name:'稻草人',needs:{木材:50,煤炭:1,纤维:20}},{name:'熔炉',needs:{铜矿石:20,石头:25}},{name:'蜂房',needs:{煤炭:8,铁锭:1}}];
  $('#craft .app-head span').textContent='材料来自当前背包';
  $('#craft .recipe-grid').innerHTML=recipes.map(r=>{const max=Math.min(...Object.entries(r.needs).map(([k,n])=>Math.floor(count(k)/n)));return '<button class="recipe '+(max?'':'locked')+'" data-recipe="'+r.name+'" data-max="'+max+'" '+(max?'':'disabled')+'><h3>'+r.name+'</h3><div class="materials">'+Object.entries(r.needs).map(([k,n])=>k+' '+count(k)+' / '+n).join(' · ')+'</div><div class="'+(max?'can':'no')+'">'+(max?'最多制作 '+max+' 个':'材料不足')+'</div></button>';}).join('');
  $$('[data-recipe]').forEach(r=>r.onclick=()=>{craftName=r.dataset.recipe;craftMax=+r.dataset.max;craftQty=1;$('#craftTitle').textContent='制作 '+craftName;$('#craftMaterials').textContent=r.querySelector('.materials').textContent;drawCraftQty();$('#craftModal').classList.add('show');});
  $('#animal .animal-scene').hidden=true;$('#jp-world-info').textContent=state.animals.length?'动物来自已同步正文。':'尚无已确认动物。';
  let positions=$('#jp-location-list');if(!positions){positions=uiDocument.createElement('div');positions.id='jp-location-list';$('#mapApp .app-body').append(positions);}positions.innerHTML=chatRoles.map(r=>{const p=state.locations[r.id];const place=p&&Object.entries(mapLocationAnchors).find(([,a])=>a.region===p.region&&Math.abs(a.x-p.x)<4&&Math.abs(a.y-p.y)<4)?.[0];return '<div class="jp-live-note">'+esc(r.name)+'：'+esc(place||(p?({west:'西部',center:'中心',north:'北部',south:'南部',east:'东部'}[p.region]):'位置未确认'))+'</div>';}).join('');
  $('#mapCaption').textContent='已确认 '+Object.keys(state.locations).length+' / '+chatRoles.length+' 位角色位置；切换区域查看标记。';
};
return {initial,mapAnchors:mapLocationAnchors,roles:chatRoles.map(({id,name,job})=>({id,name,job})),update,toast,home:goHome,settingsBody:settingsApp.querySelector('.jp-settings-body'),statusLine:settingsApp.querySelector('.jp-settings-status'),dragHandle:$('.status'),showSettings(){goHome();$('#home').style.display='none';$('#screen').classList.add('app-open');settingsApp.classList.add('active');},setStatus(text){settingsApp.querySelector('.jp-settings-status').textContent=text;$('.home-title p').textContent=text;},setLoreStatus(text){const info=settingsApp.querySelector('.jp-lore-info');if(info)info.textContent=text;},notify(text){notice.textContent=text;notice.classList.add('show');setTimeout(()=>notice.classList.remove('show'),6000);},closeRoom(){activeRole=null;notice.classList.remove('show');$('#chatRoomBack').click();},getDraft:captureDraft};
