// Farm time, not browser time, drives this ledger. All random rolls are stable per animal/day.
export const animalPresets={
 chicken:{label:'鸡',icon:'🐔',grow:3,interval:1,product:'鸡蛋',large:'大鸡蛋',house:'coop'},
 duck:{label:'鸭',icon:'🦆',grow:5,interval:2,product:'鸭蛋',rare:'鸭毛',house:'coop'},
 rabbit:{label:'兔子',icon:'🐇',grow:6,interval:4,product:'羊毛',rare:'兔脚',house:'coop'},
 cow:{label:'牛',icon:'🐄',grow:5,interval:1,product:'牛奶',large:'大牛奶',house:'barn',method:'milk'},
 goat:{label:'山羊',icon:'🐐',grow:5,interval:2,product:'山羊奶',large:'大山羊奶',house:'barn',method:'milk'},
 sheep:{label:'绵羊',icon:'🐑',grow:4,interval:3,product:'羊毛',house:'barn',method:'shear'},
 pig:{label:'猪',icon:'🐖',grow:10,interval:1,product:'松露',house:'barn',method:'forage'},
 custom:{label:'自定义动物',icon:'✧',grow:3,interval:1,product:'',house:'coop'}
};
const cp=x=>structuredClone(x),clamp=(n,max)=>Math.max(0,Math.min(max,n));
const clean=(s,max=80)=>typeof s==='string'&&s.trim()&&s.length<=max&&!/[<>"'`\\]/.test(s);
const integer=(n,min,max)=>Number.isInteger(n)&&n>=min&&n<=max;
export function farmClock(c={}){const season=['春','夏','秋','冬'].findIndex(x=>String(c.season).includes(x)),day=Number(c.day),year=Number(c.year);if(season<0||!integer(day,1,28)||!integer(year,1,9999))return null;const m=String(c.time||'06:00').match(/(\d{1,2})[:：](\d{2})/);let minute=m?Number(m[1])*60+Number(m[2]):360;if(minute<360)minute+=1440;return {day:(year-1)*112+season*28+day-1,minute:clamp(minute,1560),winter:season===3,rain:/雨|雪|雷/.test(c.weather||''),weather:c.weather||''};}
function roll(id,day,salt){let h=2166136261;for(const c of id+':'+day+':'+salt){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return (h>>>0)/4294967296;}
export function moodText(m){return m>=200?'今天看起来非常高兴！':m>=30?'看起来心情不错。':'看起来悲伤。';}
export function speciesOf(a){const text=a.species||a.name||'';return Object.keys(animalPresets).find(k=>k!=='custom'&&(text===k||text.includes(animalPresets[k].label)))||(/羊/.test(text)?'sheep':'custom');}
export function newAnimal(input,clock,id){if(!clock)throw Error('请先同步正文中的年份、季节和日期');const species=input.species||'custom',p=animalPresets[species];if(!p||!clean(input.name)||!clean(id))throw Error('请填写有效的动物名字与种类');const grow=species==='custom'?Number(input.grow):p.grow,interval=species==='custom'?Number(input.interval):p.interval,product=species==='custom'?input.product?.trim():p.product,quantity=species==='custom'?Number(input.quantity??1):1;if(!clean(product)||!integer(grow,0,112)||!integer(interval,1,112)||!integer(quantity,1,99))throw Error('产物不能为空；成长0–112天，间隔1–112天，每次1–99份');return {id,name:input.name.trim(),species,product,grow,interval,quantity,house:species==='custom'?(input.house==='barn'?'barn':'coop'):p.house,method:species==='custom'?(['milk','shear'].includes(input.method)?input.method:'collect'):p.method||'collect',age:input.adult?grow:0,friendship:0,mood:180,fed:true,pet:false,grass:false,outside:false,everPet:false,arrival:clock.day,lastProduct:null,ready:[],registered:true};}
function professional(a,h){return (a.house==='coop'&&h.profession==='coopmaster')||(a.house==='barn'&&h.profession==='shepherd');}
// Deterministic species coefficients within the ranges used by the animal rules.
function stats(a){return a.house==='coop'?{pet:32,feed:4,tick:4,cold:8,miss:20}:{pet:36,feed:16,tick:8,cold:10,miss:40};}
export function moodTicks(a,h,from,to,env){const c=stats(a);for(let t=Math.floor(from/10)*10+10;t<=to;t+=10){let delta=0;if(env.winter&&h.heater&&!a.outside&&a.mood>=150&&t>=1080)delta=c.tick;else if(a.outside&&(env.winter||env.rain))delta=-c.cold;else if(a.outside&&t>=1140)delta=-c.tick;else if(a.outside&&t>=1080&&a.mood<150)delta=c.tick;a.mood=clamp(a.mood+delta,255);}}
export function produce(a,h,day,env){if(a.age<a.grow||!a.fed)return;const p=animalPresets[a.species],r=s=>roll(a.id,day,s);let interval=a.interval;if(a.species==='sheep')interval=Math.max(1,3-(a.friendship>=900&&a.everPet?1:0)-(h.profession==='shepherd'?1:0));if(a.lastProduct!==null&&day-a.lastProduct<interval)return;if(['milk','shear'].includes(a.method)&&a.ready.length)return;if(a.method==='forage'&&(!a.outside||env.winter||env.rain))return;if(a.lastAttempt===day)return;a.lastAttempt=day;if(r('produce')>=a.mood/70)return;const qualityAllowed=r('qualityAllowed')<a.mood/150,modifier=a.mood>200?1.5:a.mood<=100?a.mood-100:0;let name=a.product,quality='普通';if(qualityAllowed){if(p.large&&a.friendship>=200&&r('large')<(a.friendship+a.mood*modifier)/1200)name=p.large;if(p.rare&&r('rare')<(a.friendship+a.mood*modifier)/(a.species==='duck'?4750:5000))name=p.rare;const score=a.friendship/1000-(1-a.mood/225)+(professional(a,h)?.333:0);quality=score>.95&&r('iridium')<score/2?'铱星':r('gold')<score/2?'金星':r('silver')<score?'银星':'普通';}if(a.method==='forage')quality='普通';a.ready.push({id:a.id+':'+day,name,quality,count:a.quantity});if(qualityAllowed)a.lastProduct=day;}
function overnight(a,h,day,env){const c=stats(a);if(!a.pet){a.friendship-=10-a.friendship/200;a.mood-=c.miss;}if(!a.fed){a.friendship-=20;a.mood-=100;}else{a.mood+=c.feed;a.age=Math.min(a.grow,a.age+1);}if(a.outside){a.friendship-=20;a.mood/=2;}a.friendship=clamp(a.friendship,1000);a.mood=clamp(a.mood,255);a.productionFed=a.fed;a.productionMood=a.mood;a.productionFriendship=a.friendship;if(a.method!=='forage')produce(a,h,day+1,env);a.fed=false;a.pet=false;a.grass=false;}
export function syncAnimals(s,state){const clock=farmClock(state.calendar);if(!clock)return false;const before=JSON.stringify(s.herd);s.herd??={day:clock.day,minute:clock.minute,env:clock,profession:'none',heater:false,bedtime:1320,animals:[]};const h=s.herd;
 // A backwards calendar edit cannot farm rewards. Normal narrative rerolls restore the checkpoint.
 if(clock.day>=h.day){let elapsed=0;while(h.day<clock.day){if(elapsed++>=112){h.day=clock.day;break;}for(const a of h.animals){if(!a.registered)continue;moodTicks(a,h,h.minute,Math.max(h.minute,h.bedtime),h.env);overnight(a,h,h.day,h.env);}h.day++;h.minute=360;h.env={...clock,day:h.day};}if(clock.minute>=h.minute){for(const a of h.animals)if(a.registered)moodTicks(a,h,h.minute,clock.minute,h.env);h.minute=clock.minute;}h.env=clock;}
 for(const row of state.animals||[]){if(h.animals.some(a=>a.id===row.id||a.name===row.name))continue;const species=speciesOf(row);if(species==='custom'){h.animals.push({id:'legacy-'+h.animals.length+'-'+clock.day,name:row.name,species,registered:false,status:row.status||''});continue;}const a=newAnimal({name:row.name,species,adult:/成年/.test(row.status||'')},clock,'story-'+clock.day+'-'+h.animals.length);a.fed=/已喂|吃饱|已吃/.test(row.status||'')||a.arrival===clock.day;h.animals.push(a);}
 return before!==JSON.stringify(h);}
export function animalView(s){return (s.herd?.animals||[]).map(a=>a.registered?{...a,status:(a.age<a.grow?'幼崽 · 成长 '+a.age+'/'+a.grow+' 天':'成年')+' · '+(a.fed?'已喂食':'待喂食')+' · 友谊 '+Math.round(a.friendship)+'/1000 · 心情 '+Math.round(a.mood)+'/255'}:{...a,status:'待登记种类与产物'});}
export function animalMemory(s){if(!s.herd)return '';return '\n【牧场实况·已结算】\n'+JSON.stringify({date:s.herd.day,animals:animalView(s).map(({name,species,product,age,grow,friendship,mood,fed,pet,outside,ready,status})=>({name,species,product,age,grow,friendship,mood,fed,pet,outside,ready,status})),rule:'此记录是手机已执行的养殖操作。正文据此演绎，不再重复扣饲料、重复增加友谊或发放产物。未收集的ready仍在牧场，只有收集才进入背包；幼崽不生产。改写动物名称不会自动认作同一只；不得凭空改名、删除或增加动物。年龄按吃饱后的过夜推进，不按回复次数。'});}
// Returns a complete replacement and transaction for the caller to commit atomically.
export function animalAction(s,state,action,id,input={}){const copy=cp(s);syncAnimals(copy,state);const h=copy.herd,clock=farmClock(state.calendar);if(!h||!clock)throw Error('请先同步正文日期');if(clock.day<h.day)throw Error('正文日期倒退，请恢复对应楼层或修正日期后再照料');let a=h.animals.find(x=>x.id===id),items=[],description='';
 if(action==='add'||action==='register'){if(h.animals.length>=100&&action==='add')throw Error('最多登记100只动物');const added=newAnimal(input,clock,action==='register'?id:input.id);if(h.animals.some(x=>x.name===added.name&&x.id!==id))throw Error('动物名字已使用，请给它起一个独立名字');if(action==='register'){if(!a||a.registered)throw Error('这只动物已经登记');Object.assign(a,added);}else h.animals.push(added);description='登记动物：'+added.name+'，'+(added.age<added.grow?'幼崽':'成年')+'，产物'+added.product;}
 else if(action==='settings'){if(!['none','coopmaster','shepherd'].includes(input.profession)||!integer(input.bedtime,1200,1560))throw Error('牧场设置无效');h.profession=input.profession;h.heater=!!input.heater;h.bedtime=input.bedtime;description='更新牧场照料设置';}
 else {if(!a?.registered)throw Error('请先登记动物的种类和产物');const c=stats(a);if(action==='pet'){if(a.pet)throw Error('今天已经抚摸过了');a.pet=true;a.everPet=true;a.friendship=clamp(a.friendship+(professional(a,h)?30:15),1000);a.mood=clamp(a.mood+c.pet*(professional(a,h)?2:1),255);description='抚摸'+a.name;}
 else if(action==='feed'){if(a.fed)throw Error('今天已经吃饱了');if(!(state.inventory||[]).some(i=>i.name==='干草'&&i.count>=1))throw Error('背包没有干草');items=[{name:'干草',count:-1}];a.fed=true;description='喂食'+a.name+'，消耗干草×1';}
 else if(action==='grass'){if(a.grass)throw Error('今天已经吃过青草了');if(clock.winter||clock.rain||clock.minute>=1080)throw Error('冬季、雨雪天或18点以后不能放牧吃草');a.grass=true;a.fed=true;a.outside=true;a.friendship=clamp(a.friendship+8,1000);a.mood=255;description=a.name+'在户外吃到青草';}
 else if(action==='inside'||action==='outside'){a.outside=action==='outside';description=(a.outside?'放出':'带回')+a.name;}
 else if(action==='collect'){if(!a.ready.length)throw Error('目前没有可收集的产物');items=a.ready.map(p=>({name:(p.quality==='普通'?'':p.quality)+p.name,count:p.count,kind:'item',price:0,days:0}));if(['milk','shear'].includes(a.method))a.friendship=clamp(a.friendship+5,1000);description='收集'+a.name+'的'+items.map(x=>x.name+'×'+x.count).join('、');a.ready=[];}
 else throw Error('未知的牧场操作');}
 if(a?.method==='forage'&&a.outside&&clock.minute<1080&&['grass','outside'].includes(action)){const morning={...a,fed:!!a.productionFed,mood:a.productionMood??a.mood,friendship:a.productionFriendship??a.friendship};const count=a.ready.length;produce(morning,h,clock.day,clock);if(a.ready.length>count)a.lastProduct=clock.day;a.lastAttempt=morning.lastAttempt;}
 return {herd:h,items,description};}
