import test from 'node:test';import assert from 'node:assert/strict';
import {farmClock,newAnimal,syncAnimals,animalAction,moodTicks,produce,animalView,animalMemory} from './animals.js';
import {checkpoint,rollback} from './round-sync.js';import {world} from './core.js';import {appendTransaction} from './social.js';
const calendar=(day=1,time='06:00',season='春季')=>({year:1,season,day,time,weather:'晴'});
const state=(day=1)=>({calendar:calendar(day),animals:[],inventory:[{name:'干草',count:20,kind:'item'}],capacity:20,gold:0});
function setup(species='chicken',adult=false){const s={base:state(),turns:[]};syncAnimals(s,s.base);s.herd.animals.push(newAnimal({name:'团子',species,adult},farmClock(s.base.calendar),'a-1'));return s;}
function act(s,action,input={}){const r=animalAction(s,world(s),action,'a-1',input);if(r.items.length)appendTransaction(s,world(s),{id:crypto.randomUUID(),items:r.items});s.herd=r.herd;return r;}
function next(s,day){s.base.calendar=calendar(day);syncAnimals(s,world(s));}
test('juveniles grow only after fed nights, no production before third night',()=>{const s=setup();act(s,'pet');next(s,2);assert.equal(s.herd.animals[0].age,1);assert.equal(s.herd.animals[0].ready.length,0);next(s,3);assert.equal(s.herd.animals[0].age,1);act(s,'feed');act(s,'pet');next(s,4);act(s,'feed');act(s,'pet');next(s,5);assert.equal(s.herd.animals[0].age,3);assert.equal(s.herd.animals[0].ready.length,1);});
test('pet and grass once daily, feed debits exactly one hay',()=>{const s=setup();act(s,'pet');assert.equal(s.herd.animals[0].friendship,15);assert.throws(()=>act(s,'pet'));act(s,'grass');assert.equal(s.herd.animals[0].friendship,23);assert.equal(s.herd.animals[0].mood,255);assert.throws(()=>act(s,'grass'));act(s,'inside');next(s,2);act(s,'feed');assert.equal(world(s).inventory[0].count,19);assert.throws(()=>act(s,'feed'));});
test('unfed and unpetted penalties, sleeping outside and mood boundaries',()=>{const s=setup();const a=s.herd.animals[0];a.friendship=1000;a.mood=255;a.fed=false;next(s,2);assert.equal(a.friendship,975);assert.equal(a.mood,135);assert.equal(a.ready.length,0);});
test('profession doubles petting, milk/shear adds five only when collected',()=>{const s=setup('cow',true);s.herd.profession='shepherd';act(s,'pet');assert.equal(s.herd.animals[0].friendship,30);next(s,2);assert.equal(s.herd.animals[0].ready[0].name,'牛奶');const before=s.herd.animals[0].friendship;act(s,'collect');assert.equal(s.herd.animals[0].friendship,before+5);assert.throws(()=>act(s,'collect'));assert.ok(world(s).inventory.some(x=>x.name.endsWith('牛奶')&&x.count===1));});
test('winter heater and time effects do not stack; reload does not repeat ticks',()=>{const s=setup();const a=s.herd.animals[0];a.mood=160;const h=s.herd;h.heater=true;moodTicks(a,h,1080,1090,{winter:true,rain:true});assert.equal(a.mood,164);a.outside=true;a.mood=140;h.heater=false;moodTicks(a,h,1080,1090,{winter:true,rain:true});assert.equal(a.mood,132);s.base.calendar.time='18:20';syncAnimals(s,world(s));const saved=JSON.stringify(s.herd);syncAnimals(s,world(s));assert.equal(JSON.stringify(s.herd),saved);});
test('goat production is every two days and uncollected milk does not stack',()=>{const s=setup('goat',true);for(let day=2;day<=4;day++){act(s,'pet');next(s,day);if(day<4)act(s,'feed');}assert.equal(s.herd.animals[0].ready.length,1);act(s,'collect');act(s,'feed');act(s,'pet');next(s,5);assert.equal(s.herd.animals[0].ready.length,1);});
test('custom animal validates parameters and follows same lifecycle',()=>{const s=setup();const r=animalAction(s,world(s),'add',null,{id:'pika',name:'皮卡丘',species:'custom',product:'电晶石',grow:2,interval:3,quantity:2});s.herd=r.herd;assert.equal(s.herd.animals[1].friendship,0);assert.equal(s.herd.animals[1].mood,180);assert.throws(()=>animalAction(s,world(s),'add',null,{id:'bad',name:'坏参数',species:'custom',product:'蛋',grow:-1,interval:0}));assert.match(animalMemory(s),/电晶石/);});
test('full friendship and mood can produce large products; low friendship cannot',()=>{const s=setup('cow',true),a=s.herd.animals[0];a.friendship=1000;a.mood=255;produce(a,s.herd,1,{winter:false,rain:false});assert.equal(a.ready[0].name,'大牛奶');const low=setup('cow',true);low.herd.animals[0].mood=255;produce(low.herd.animals[0],low.herd,1,{});assert.equal(low.herd.animals[0].ready[0].name,'牛奶');});
test('reroll restores herd and transactions, new chat has no inherited herd',()=>{const s=setup('cow',true),before=checkpoint(s);act(s,'pet');next(s,2);act(s,'collect');s.turns.push({before,state:state(2)});rollback(s,0);assert.equal(s.herd.animals[0].friendship,0);assert.equal(s.herd.animals[0].ready.length,0);assert.equal(s.socialEvents,undefined);assert.equal(animalView({base:state(),turns:[]}).length,0);});
test('legacy records retain identity, unknown animal requires registration',()=>{const s=setup();s.base.animals=[{name:'鸡',status:'幼崽'},{name:'小火龙',status:'可爱'}];syncAnimals(s,world(s));assert.equal(s.herd.animals.length,3);syncAnimals(s,world(s));assert.equal(s.herd.animals.length,3);assert.equal(s.herd.animals[2].registered,false);assert.equal(s.herd.animals[1].age,0);});
test('pig finds truffle outdoors after a fed night, bringing home preserves it',()=>{const s=setup('pig',true);act(s,'pet');next(s,2);act(s,'grass');assert.equal(s.herd.animals[0].ready.length,1);act(s,'inside');act(s,'outside');assert.equal(s.herd.animals[0].ready.length,1);});
test('grass unavailable during rain, winter or night; backwards date cannot be exploited',()=>{const s=setup();s.base.calendar.weather='雨';assert.throws(()=>act(s,'grass'));s.base.calendar=calendar(1,'19:00');assert.throws(()=>act(s,'grass'));next(s,3);s.base.calendar=calendar(2);assert.throws(()=>act(s,'pet'));});
