import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {execFileSync} from 'node:child_process';import vm from 'node:vm';
const root=new URL('./',import.meta.url);execFileSync(process.execPath,['build.mjs'],{cwd:root});const phone=readFileSync(new URL('phone.js',root),'utf8');
test('build inserts every UI fragment verbatim, preserving dollar selectors and replacement-like text',()=>{for(const file of ['transfer-ui.js','group-social-ui.js','customization-ui.js','collection-ui.js','animal-ui.js','progression-ui.js','community-ui.js'])assert(phone.includes(readFileSync(new URL(file,root),'utf8')),file+' changed during build');});
test('generated startup collects icons using multi-element selection and keeps existing icon markup',()=>{const start=phone.indexOf('const appearanceStyle='),end=phone.indexOf('const beforeCustomThreads=',start),box={innerHTML:'<svg>default</svg>'},button={dataset:{open:'chatApp'},querySelector:s=>s==='small'?{textContent:'聊天'}:box};const context={uiDocument:{createElement:()=>({})},uiRoot:{append(){}},$$:()=>[button],$:()=>button};vm.createContext(context);vm.runInContext(phone.slice(start,end)+'\nglobalThis.icons=iconEntries;globalThis.defaults=defaultIcons;',context);assert.equal(context.icons.length,1);assert.equal(context.icons[0].id,'chatApp');assert.equal(context.defaults.get('chatApp'),'<svg>default</svg>');});

test('generated private and group settings expose wallpaper and CSS buttons without NodeList.at',()=>{
 const a=phone.indexOf('const roomSettings=smallButton'),b=phone.indexOf('function openPromptPresets()',a),source=phone.slice(a,b);
 for(const group of [false,true]){const calls=[],pages=[],roles=[{id:'01',name:'阿德里安'},{id:'02',name:'哈兰'}],role=group?{id:'g',name:'群聊',members:['01','02']}:roles[0];const node=()=>({dataset:{},addEventListener(){},setAttribute(){},textContent:''});
 const sandbox={activeRole:role,chatRoles:roles,uiCommunity:()=>({chatId:'x',userName:'玩家',chatNames:{}}),displayName:r=>r.name,userPortrait:()=>'',threadPortrait:()=>'',memberPortrait:()=>'',esc:String,smallButton:(label,text,callback)=>({onclick:callback}),$:()=>({append(){}}),openAppearance:(...args)=>calls.push(args),renderChatThreads(){},renderChatRoom(){},sheet(title,html){const nodes=new Map(),page={html,isConnected:true,querySelector(key){if(!nodes.has(key))nodes.set(key,node());return nodes.get(key);},querySelectorAll(){return {length:0,forEach(){},*[Symbol.iterator](){}};}};pages.push(page);return page;}};
 vm.createContext(sandbox);vm.runInContext(source+'\nroomSettings.onclick();',sandbox);assert(pages[0].html.includes('data-room-css'));assert(pages[0].html.includes('data-room-wallpaper'));pages[0].querySelector('[data-room-css]').onclick();pages[0].querySelector('[data-room-wallpaper]').onclick();assert.equal(calls[0][0],'css');assert.equal(calls[0][1].id,role.id);assert.equal(calls[1][0],'thread');}
});
test('generated chat app settings exposes the default CSS entry directly',()=>{const a=phone.indexOf('function chatSettings()'),b=phone.indexOf('const mailSettings=',a),calls=[],nodes=new Map();const page={querySelector(key){if(!nodes.has(key))nodes.set(key,{});return nodes.get(key);}};const sandbox={sheet(title,html){assert(html.includes('data-default-css'));return page;},promptHint:'',promptFields:()=>'',bindPromptFields(){},openAppearance:(...args)=>calls.push(args)};vm.createContext(sandbox);vm.runInContext(phone.slice(a,b)+'\nchatSettings();',sandbox);page.querySelector('[data-default-css]').onclick();assert.equal(calls[0][0],'css');assert.equal(calls[0].length,1);});

test('global chat style remains active on the list and local overrides are independent',()=>{const a=phone.indexOf('function updateAppearance()'),b=phone.indexOf('function appearanceError',a);const data={appearance:{defaultCssPresetId:'global',cssPresets:[{id:'global',css:'.chat-thread{color:red}'},{id:'local',css:'.chat-bubble{color:blue}'}]},chatAppearance:{one:{cssPresetId:'local'}}};const sandbox={uiCommunity:()=>data,activeRole:null,bridge:{getImage:()=>null,scopedChatCss:(css,kind)=>kind+':'+css},appearanceStyle:{},chatCssStyle:{},threadCssStyle:{},iconEntries:[],iconSources:new Map(),compiledStyles:new Map(),defaultIcons:new Map()};vm.createContext(sandbox);vm.runInContext(phone.slice(a,b)+'\nupdateAppearance();',sandbox);assert(sandbox.chatCssStyle.textContent.startsWith('global:'));assert.equal(sandbox.threadCssStyle.textContent,'');sandbox.activeRole={id:'one'};vm.runInContext('updateAppearance();',sandbox);assert(sandbox.chatCssStyle.textContent.startsWith('global:'));assert(sandbox.threadCssStyle.textContent.startsWith('thread:'));data.chatAppearance.one.cssPresetId=null;vm.runInContext('updateAppearance();',sandbox);assert.equal(sandbox.threadCssStyle.textContent,'');assert(sandbox.chatCssStyle.textContent.startsWith('global:'));});
