import { readFile, writeFile } from 'node:fs/promises';
const base = new URL('./', import.meta.url);
const html = await readFile(new URL('source.html', base), 'utf8');
let script = html.match(/<script>([\s\S]*?)<\/script>/)[1];
script = script.replace(/let uiRoot=document,uiDocument=document;[\s\S]*?const actions=/, 'let uiDocument=document;\nconst actions=');
script = script.replace('baseFunds=12580,', 'upgradeBaseFunds=12580,');
script = 'let baseFunds=12580;\n' + script;
script = script.split('\n').filter(line => !line.startsWith('window.JunimoMap=') && !line.startsWith('try{const stRoot=')).join('\n');
const css = html.match(/<style[^>]*>([\s\S]*?)<\/style>/)[1];
const body = html.match(/<body[^>]*>([\s\S]*?)<script>/)[1];
const adapter = await readFile(new URL('adapter.js', base), 'utf8');
await writeFile(new URL('phone.js', base), `// Generated by tools/build.mjs from the supplied design and adapter.js.\nexport function mountPhone(uiRoot, bridge) {\nuiRoot.innerHTML = ${JSON.stringify('<style>'+css+'</style>'+body)};\n${script}\n${adapter}\n}\n`);
console.log('Built phone.js');

