// Included in mountPhone after the chat and mail apps.
const uiCommunity=()=>bridge.communityData?.()||{posts:[],avatars:{},profile:{},mailPreferences:{},userName:'我'};
function avatarMarkup(threadId,who,fallback){const id=uiCommunity().avatars?.[threadId]?.[who],image=id&&bridge.getImage(id);return image?'<img class="jp-custom-avatar" src="'+esc(image.dataUrl)+'" alt="头像" referrerpolicy="no-referrer">':fallback;}
function userPortrait(threadId){return avatarMarkup(threadId,'me',profileAvatar());}
function memberPortrait(role,thread){return thread?.members?avatarMarkup(thread.id,role.id,threadPortrait(role)):threadPortrait(role);}
function smallButton(label,text,callback){const b=uiDocument.createElement('button');b.type='button';b.className='jp-icon-button';b.setAttribute('aria-label',label);b.title=label;b.textContent=text;b.onclick=callback;return b;}
function sheet(title,body,kind=''){const dialog=uiDocument.createElement('div');dialog.className='jp-review jp-modern-sheet '+kind;dialog.setAttribute('role','dialog');dialog.setAttribute('aria-label',title);dialog.innerHTML='<section class="jp-review-card"><header class="jp-sheet-head"><h3>'+esc(title)+'</h3></header>'+body+'<p class="jp-review-error" role="status"></p></section>';const close=smallButton('关闭'+title,kind.includes('jp-page')?'‹':'×',()=>dialog.remove());dialog.querySelector('header').append(close);dialog.addEventListener('keydown',e=>{if(e.key==='Escape')dialog.remove();});$('.screen').append(dialog);return dialog;}
function promptFields(app){const data=uiCommunity();return '<div class="jp-prompt-fields">'+(data.promptDefinitions||[]).filter(p=>p.app===app).map(p=>'<details class="jp-prompt-item"><summary>'+esc(p.label)+'</summary><textarea data-prompt="'+p.id+'" aria-label="'+esc(p.label)+'提示词" maxlength="24000">'+esc(data.appPrompts?.[p.id]??p.text)+'</textarea><button class="jp-text-action" data-default="'+p.id+'">恢复此项默认</button></details>').join('')+'</div>';}
function bindPromptFields(d){d.querySelectorAll('[data-default]').forEach(b=>b.onclick=()=>{const p=uiCommunity().promptDefinitions.find(p=>p.id===b.dataset.default);d.querySelector('[data-prompt="'+p.id+'"]').value=p.text;});}
function promptValues(d){return Object.fromEntries([...d.querySelectorAll('[data-prompt]')].map(t=>[t.dataset.prompt,t.value]));}
const promptHint='<p class="jp-sheet-caption">展开即可编辑完整默认提示词。{{变量}} 会自动填入当前角色和存档；保存后用于下一次生成。回复格式需与现有功能兼容。</p>';
function chatSettings(){const d=sheet('聊天 App 设置','<div class="jp-page-intro"><small>MAKE IT YOURS</small><h2>聊天，也有你的语气。</h2></div>'+promptHint+promptFields('chat')+'<p class="jp-sheet-caption">信件、赠礼与红包的共用提示词在信件 App 设置中。</p><button class="jp-primary" data-save>保存聊天提示词</button>','jp-page');bindPromptFields(d);d.querySelector('[data-save]').onclick=async()=>{try{await bridge.saveCommunitySettings({appPrompts:promptValues(d)});d.remove();toast('聊天提示词已保存');}catch(e){d.querySelector('.jp-review-error').textContent=e.message;}};}
const mailSettings=smallButton('邮件设置','⚙',()=>{const data=uiCommunity(),labels={flirt:'暧昧来信',admirer:'匿名爱慕者',spam:'虚构小广告',harassment:'无礼来信'};const d=sheet('邮件设置','<div class="jp-page-intro"><small>LETTERS TO YOU</small><h2>等一封，喜欢的信。</h2></div><div class="jp-setting-list">'+Object.entries(labels).map(([k,v])=>'<label class="jp-toggle-row"><span>'+v+'</span><input type="checkbox" data-category="'+k+'" '+(data.mailPreferences[k]!==false?'checked':'')+' aria-label="接收'+v+'"></label>').join('')+'</div>'+promptHint+promptFields('mail')+'<details class="jp-prompt-item"><summary>额外来信偏好（保留旧设置）</summary><textarea aria-label="自定义来信规则内容" maxlength="3000">'+esc(data.mailCustomRules||'')+'</textarea></details><button class="jp-primary" data-save>保存邮件设置</button>','jp-page jp-mail-settings');bindPromptFields(d);d.querySelector('[data-save]').onclick=async()=>{try{await bridge.saveCommunitySettings({appPrompts:promptValues(d),mailCustomRules:d.querySelector('[aria-label="自定义来信规则内容"]').value,mailPreferences:Object.fromEntries([...d.querySelectorAll('[data-category]')].map(el=>[el.dataset.category,el.checked]))});d.remove();toast('邮件设置已保存');}catch(e){d.querySelector('.jp-review-error').textContent=e.message;}};});mailApp.querySelector('.app-head').append(mailSettings);
$('#chatApp .app-head').append(smallButton('聊天 App 设置','⚙',chatSettings));
const letterOpenBase=openLetter;openLetter=function(id){letterOpenBase(id);const dialog=$('.jp-letter');if(!dialog)return;dialog.setAttribute('role','dialog');dialog.setAttribute('aria-label','阅读信件');const close=smallButton('关闭信件','×',()=>dialog.remove());close.classList.add('jp-letter-x');dialog.append(close);dialog.addEventListener('keydown',e=>{if(e.key==='Escape')dialog.remove();});};
const feed=uiDocument.createElement('section');feed.id='jpFeedApp';feed.className='app';feed.innerHTML='<header class="app-head"><button class="back" aria-label="动态返回聊天">‹</button><b>朋友圈</b><div class="jp-feed-actions"></div></header><div class="app-body jp-feed-scroll"><div class="jp-feed-cover"><button class="jp-cover-edit" aria-label="更换朋友圈封面"><small>MOON VALLEY · MOMENTS</small><span>把日子，写成小事。</span><em>轻触更换封面</em></button><div class="jp-feed-self"><button class="jp-profile-id" aria-label="修改朋友圈ID"></button><button class="chat-avatar jp-self-avatar" aria-label="更换朋友圈头像"></button></div></div><div class="jp-feed-list"></div></div>';$('.screen').append(feed);
function openFeed(){goHome();$('#home').style.display='none';$('#screen').classList.add('app-open');feed.classList.add('active');drawFeed();}
function closeFeed(){feed.classList.remove('active');$('#chatApp').classList.add('active');$('#chatListView').hidden=false;$('#chatRoom').hidden=true;$('#chatApp').classList.remove('chat-room-open');}
feed.querySelector('.back').onclick=closeFeed;
const navIcon={chat:'<svg viewBox="0 0 24 24"><path d="M5 4h14a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2h-8l-6 3v-3a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2Z"/><path d="M7 9h10M7 13h6"/></svg>',feed:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="m15 8-2 5-5 3 2-6 5-2Z"/></svg>'};
function socialNav(selected){const nav=uiDocument.createElement('nav');nav.className='jp-social-nav';nav.setAttribute('aria-label','聊天与朋友圈');nav.innerHTML=[['chat','消息'],['feed','朋友圈']].map(([id,label])=>'<button aria-label="切换到'+label+'" '+(selected===id?'aria-current="page"':'')+' data-tab="'+id+'">'+navIcon[id]+'<span>'+label+'</span></button>').join('');nav.querySelector('[data-tab="chat"]').onclick=closeFeed;nav.querySelector('[data-tab="feed"]').onclick=openFeed;return nav;}
$('#chatListView').append(socialNav('chat'));feed.append(socialNav('feed'));
function profileAvatar(){const data=uiCommunity(),item=bridge.getImage(data.profile?.avatar);return item?'<img class="jp-custom-avatar" src="'+esc(item.dataUrl)+'" alt="我的朋友圈头像">':'<span class="jp-user-initial">'+esc((data.profile?.id||data.userName||'我').slice(0,1))+'</span>';}
function editProfile(field){const data=uiCommunity(),labels={id:'朋友圈 ID',avatar:'朋友圈头像',cover:'朋友圈封面'};const d=sheet('修改'+labels[field],field==='id'?'<p class="jp-sheet-caption">这是你的公开昵称。改名后，朋友们仍然知道是你。</p><input aria-label="朋友圈ID" maxlength="32" value="'+esc(data.profile?.id||data.userName)+'"><button class="jp-primary" data-save>保存 ID</button>':'<p class="jp-sheet-caption">选择一张自己的图片，装点这片小天地。</p><label class="jp-profile-upload">＋ 从本地选择图片<input aria-label="上传'+labels[field]+'" type="file" accept="image/png,image/jpeg,image/webp,image/gif"></label><button class="jp-text-action" data-reset>恢复默认'+(field==='avatar'?'头像':'封面')+'</button>','jp-profile-sheet');const run=data.chatId;async function save(value){if(run!==uiCommunity().chatId)throw Error('对话已切换，请重新打开设置');await bridge.saveFeedProfile({[field]:value});d.remove();drawFeed();}if(field==='id')d.querySelector('[data-save]').onclick=()=>save(d.querySelector('input').value).catch(e=>d.querySelector('.jp-review-error').textContent=e.message);else{d.querySelector('input').onchange=async e=>{const input=e.target;if(!input.files[0])return;input.disabled=true;try{const source=await bridge.prepareSticker(input.files[0]);if(d.isConnected)await save(source);}catch(err){d.querySelector('.jp-review-error').textContent=err.message;}finally{input.disabled=false;}};d.querySelector('[data-reset]').onclick=()=>save(null).catch(e=>d.querySelector('.jp-review-error').textContent=e.message);}}
feed.querySelector('.jp-profile-id').onclick=()=>editProfile('id');feed.querySelector('.jp-self-avatar').onclick=()=>editProfile('avatar');feed.querySelector('.jp-cover-edit').onclick=()=>editProfile('cover');
function composePost(){const d=sheet('发说说','<p class="jp-sheet-caption">分享给月亮谷的朋友们</p><textarea class="jp-post-text" aria-label="说说内容" maxlength="600" placeholder="这一刻，想说点什么…"></textarea><label class="jp-form-label">模拟配图（选填）<textarea class="jp-post-image" aria-label="动态配图描述" maxlength="1000" placeholder="描述画面，例如：傍晚的田野，刚浇完水的幼苗泛着光"></textarea></label><p class="jp-sheet-caption">配图显示为可点击的虚拟照片。</p><button class="jp-primary" data-publish>发布</button>');d.querySelector('[data-publish]').onclick=async e=>{e.currentTarget.disabled=true;try{await bridge.publishPost(d.querySelector('.jp-post-text').value,d.querySelector('.jp-post-image').value);d.remove();drawFeed();}catch(err){d.querySelector('.jp-review-error').textContent=err.message;e.currentTarget.disabled=false;}};}
function commentAuthor(id,data){return id==='me'?(data.profile?.id||data.userName):chatRoles.find(r=>r.id===id)?.name||'村民';}
function commentMarkup(post,data){if(!post.comments?.length)return '';return '<div class="jp-comments">'+post.comments.map(c=>{const parent=post.comments.find(x=>x.id===c.replyTo);return '<div class="jp-comment"><button data-reply-comment="'+esc(c.id)+'" data-post="'+esc(post.id)+'" aria-label="回复'+esc(commentAuthor(c.authorId,data))+'的评论"><b>'+esc(commentAuthor(c.authorId,data))+'</b>'+(parent?' 回复 <b>'+esc(commentAuthor(parent.authorId,data))+'</b>':'')+'：'+esc(c.text)+'</button><button class="jp-comment-delete" data-delete-comment="'+esc(c.id)+'" aria-label="删除评论">×</button></div>';}).join('')+'</div>';}
function commentComposer(postId,replyTo){feed.querySelector('.jp-comment-composer')?.remove();const anchor=Array.from(feed.querySelectorAll('[data-comment-post]')).find(b=>b.dataset.commentPost===postId);if(!anchor)return;const wrap=uiDocument.createElement('div');wrap.className='jp-comment-composer';wrap.innerHTML='<textarea aria-label="动态评论内容" maxlength="500" placeholder="'+(replyTo?'回复这条评论…':'说点什么…')+'"></textarea><div><button data-cancel>取消</button><button data-send>发送评论</button></div><small role="status"></small>';anchor.closest('.jp-post-main').append(wrap);wrap.querySelector('[data-cancel]').onclick=()=>wrap.remove();wrap.querySelector('[data-send]').onclick=async e=>{e.currentTarget.disabled=true;try{await bridge.publishComment(postId,wrap.querySelector('textarea').value,replyTo);wrap.remove();}catch(err){wrap.querySelector('small').textContent=err.message;e.currentTarget.disabled=false;}};wrap.querySelector('textarea').focus();}
function feedSettings(){const d=sheet('动态设置','<p class="jp-sheet-caption">正文推进或聊天回复后，有机会出现新的角色动态。</p><label class="jp-form-label">发布频率<select aria-label="角色动态频率">'+[['off','关闭'],['low','偶尔 · 15%'],['normal','正常 · 35%'],['high','频繁 · 70%']].map(([k,v])=>'<option value="'+k+'" '+(uiCommunity().feedFrequency===k?'selected':'')+'>'+v+'</option>').join('')+'</select></label><label class="jp-form-label">角色评论频率<select aria-label="角色评论频率">'+[['off','关闭'],['low','偶尔 · 15%'],['normal','正常 · 35%'],['high','频繁 · 70%']].map(([k,v])=>'<option value="'+k+'" '+((uiCommunity().commentFrequency||'normal')===k?'selected':'')+'>'+v+'</option>').join('')+'</select></label>'+promptFields('feed')+'<p class="jp-sheet-caption">角色可以评论你、自己和其他角色的动态，也会互相回复；概率独立于发说说。触发时使用手机当前 API；关闭不影响你自己发说说。</p><button class="jp-primary" data-save>保存设置</button>');bindPromptFields(d);d.querySelector('[data-save]').onclick=async()=>{try{await bridge.saveCommunitySettings({feedFrequency:d.querySelector('[aria-label="角色动态频率"]').value,commentFrequency:d.querySelector('[aria-label="角色评论频率"]').value,appPrompts:Object.fromEntries(Array.from(d.querySelectorAll('[data-prompt]')).map(x=>[x.dataset.prompt,x.value]))});d.remove();toast('动态频率已保存');}catch(e){d.querySelector('.jp-review-error').textContent=e.message;}};}
feed.querySelector('.jp-feed-actions').append(smallButton('动态设置','⚙',feedSettings),smallButton('发说说','＋',composePost));
function drawFeed(){const data=uiCommunity(),name=data.profile?.id||data.userName,cover=bridge.getImage(data.profile?.cover),coverEl=feed.querySelector('.jp-feed-cover');coverEl.style.backgroundImage=cover?'linear-gradient(0deg,#282c3844,transparent 65%),url("'+cover.dataUrl.replaceAll('"','%22')+'")':'';coverEl.classList.toggle('has-cover',!!cover);feed.querySelector('.jp-profile-id').textContent=name;feed.querySelector('.jp-self-avatar').innerHTML=profileAvatar();feed.querySelector('.jp-feed-list').innerHTML=data.posts.length?data.posts.map(p=>{const role=chatRoles.find(r=>r.id===p.authorId),author=p.authorId==='me'?name:role?.name||'村民';return '<article class="jp-post"><span class="chat-avatar">'+(p.authorId==='me'?profileAvatar():role?threadPortrait(role):'<span class="jp-user-initial">'+esc(author.slice(0,1))+'</span>')+'</span><div class="jp-post-main"><b>'+esc(author)+'</b><p>'+esc(p.text)+'</p>'+(p.imageDescription?'<button class="jp-virtual-photo" data-photo="'+esc(p.id)+'" aria-label="查看'+esc(author)+'的动态配图"><span>▧</span><small>一帧日常</small><em>点击查看画面</em></button>':'')+'<footer>'+esc([p.storyDate,p.time].filter(Boolean).join(' · ')||'刚刚')+'<button class="jp-post-delete" data-comment-post="'+esc(p.id)+'" aria-label="评论'+esc(author)+'的动态">评论</button><button class="jp-post-delete" data-delete-post="'+esc(p.id)+'" aria-label="删除'+esc(author)+'的动态">删除</button></footer>'+commentMarkup(p,data)+'</div></article>';}).join(''):'<div class="jp-feed-empty"><span>✧</span><h3>故事还在发生</h3><p>发一条说说，留住今天的小事。<br>朋友们的动态也会出现在这里。</p><button class="jp-primary" data-first-post>写第一条说说</button></div>';feed.querySelectorAll('[data-comment-post]').forEach(b=>b.onclick=()=>commentComposer(b.dataset.commentPost));feed.querySelectorAll('[data-reply-comment]').forEach(b=>b.onclick=()=>commentComposer(b.dataset.post,b.dataset.replyComment));feed.querySelectorAll('[data-delete-comment]').forEach(b=>b.onclick=()=>bridge.deleteFeedComment(b.dataset.deleteComment).catch(e=>toast(e.message)));feed.querySelectorAll('[data-delete-post]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await bridge.deleteFeedPost(b.dataset.deletePost);}catch(e){toast(e.message);b.disabled=false;}});feed.querySelector('[data-first-post]')?.addEventListener('click',composePost);feed.querySelectorAll('[data-photo]').forEach(b=>b.onclick=()=>{const p=data.posts.find(x=>x.id===b.dataset.photo);sheet('照片里的这一刻','<div class="jp-photo-illustration">▧</div><p class="jp-photo-description">'+esc(p.imageDescription)+'</p>');});}
const roomSettings=smallButton('聊天设置','⋯',()=>{const role=activeRole;if(!role)return;const entries=[['me','我的头像',userPortrait(role.id)],...(role.members?role.members.map(id=>{const r=chatRoles.find(r=>r.id===id);return [id,r.name,memberPortrait(r,role)];}):[['role',role.name,threadPortrait(role)]])];const d=sheet(role.members?'群聊设置':'聊天设置','<div class="jp-room-profile"><span class="chat-avatar">'+threadPortrait(role)+'</span><h2>'+esc(role.name)+'</h2><p>'+(role.members?'一起分享月亮谷的小日常':'你们的专属聊天空间')+'</p></div><h4 class="jp-section-label">'+(role.members?'群成员头像':'聊天头像')+'</h4><div class="jp-avatar-settings">'+entries.map(([who,title,markup])=>'<div class="jp-avatar-setting"><span class="chat-avatar" data-preview="'+who+'">'+markup+'</span><div class="jp-avatar-name"><strong>'+esc(title)+'</strong><button class="jp-avatar-reset" data-reset="'+who+'">'+(who==='me'?'跟随朋友圈头像':role.members?'跟随私聊头像':'恢复默认')+'</button></div><label class="jp-avatar-pick">更换<input type="file" accept="image/png,image/jpeg,image/webp,image/gif" data-avatar="'+who+'" aria-label="更换'+esc(title)+'头像"></label></div>').join('')+'</div>'+(role.members?'<button class="jp-text-action" data-follow-all>所有成员跟随私聊头像</button>':'')+'<p class="jp-sheet-caption">我的头像默认跟随朋友圈；在此单独更换后，本聊天保留独立头像。点击“跟随朋友圈头像”可重新同步。群成员未单独设置时跟随私聊头像。</p><details class="jp-avatar-url"><summary>使用图片直链</summary><select aria-label="直链头像对象">'+entries.map(([who,title])=>'<option value="'+who+'">'+esc(title)+'</option>').join('')+'</select><input type="url" aria-label="头像图片直链" placeholder="https://…"><button class="jp-primary" data-avatar-url>应用头像</button></details>','jp-page jp-room-settings');const run=uiCommunity().chatId;
 function refresh(){for(const [who] of entries){const markup=who==='me'?userPortrait(role.id):who==='role'?threadPortrait(role):memberPortrait(chatRoles.find(r=>r.id===who),role);d.querySelector('[data-preview="'+who+'"]').innerHTML=markup;}renderChatThreads();if(activeRole?.id===role.id)renderChatRoom(role);}
 async function save(who,source){if(run!==uiCommunity().chatId)throw Error('对话已切换，请重新打开头像设置');await bridge.saveAvatar(role.id,who,source);refresh();}
 d.querySelectorAll('[data-avatar]').forEach(input=>input.onchange=async()=>{if(!input.files[0])return;input.disabled=true;try{const source=await bridge.prepareSticker(input.files[0]);if(d.isConnected)await save(input.dataset.avatar,source);}catch(e){d.querySelector('.jp-review-error').textContent=e.message;}finally{input.disabled=false;}});
 d.querySelectorAll('[data-reset]').forEach(b=>b.onclick=()=>save(b.dataset.reset,null).catch(e=>d.querySelector('.jp-review-error').textContent=e.message));
 d.querySelector('[data-follow-all]')?.addEventListener('click',async e=>{e.currentTarget.disabled=true;try{for(const id of role.members)await save(id,null);toast('所有群成员已跟随私聊头像');}catch(err){d.querySelector('.jp-review-error').textContent=err.message;}finally{e.currentTarget.disabled=false;}});
 d.querySelector('[data-avatar-url]').onclick=async()=>{try{await save(d.querySelector('select').value,bridge.validateImageSource(d.querySelector('[type=url]').value));}catch(e){d.querySelector('.jp-review-error').textContent=e.message;}};
});$('#chatRoom .chat-room-bar').append(roomSettings);
function updateCommunity(){drawFeed();roomSettings.hidden=false;}
