// Included in mountPhone after the chat and mail apps.
const uiCommunity=()=>bridge.communityData?.()||{posts:[],avatars:{},profile:{},mailPreferences:{},userName:'我'};
function avatarMarkup(threadId,who,fallback){const id=uiCommunity().avatars?.[threadId]?.[who],image=id&&bridge.getImage(id);return image?'<img class="jp-custom-avatar" src="'+esc(image.dataUrl)+'" alt="头像" referrerpolicy="no-referrer">':fallback;}
function userPortrait(threadId){return avatarMarkup(threadId,'me',profileAvatar());}
function memberPortrait(role,thread){return thread?.members?avatarMarkup(thread.id,role.id,threadPortrait(role)):threadPortrait(role);}
function smallButton(label,text,callback){const b=uiDocument.createElement('button');b.type='button';b.className='jp-icon-button';b.setAttribute('aria-label',label);b.title=label;b.textContent=text;b.onclick=callback;return b;}
function sheet(title,body,kind=''){const dialog=uiDocument.createElement('div');dialog.className='jp-review jp-modern-sheet '+kind;dialog.setAttribute('role','dialog');dialog.setAttribute('aria-label',title);dialog.innerHTML='<section class="jp-review-card"><header class="jp-sheet-head"><h3>'+esc(title)+'</h3></header>'+body+'<p class="jp-review-error" role="status"></p></section>';const close=smallButton('关闭'+title,kind.includes('jp-page')?'‹':'×',()=>dialog.remove());dialog.querySelector('header').append(close);dialog.addEventListener('keydown',e=>{if(e.key==='Escape')dialog.remove();});$('.screen').append(dialog);return dialog;}
function promptFields(app){const data=uiCommunity();return '<div class="jp-prompt-fields">'+(data.promptDefinitions||[]).filter(p=>app==='all'||p.app===app).map(p=>'<details class="jp-prompt-item"><summary>'+esc(p.label)+'</summary><textarea data-prompt="'+p.id+'" aria-label="'+esc(p.label)+'提示词" maxlength="24000" placeholder="留空使用内置'+esc(p.label)+'">'+esc(data.appPrompts?.[p.id]||'')+'</textarea><p class="jp-sheet-caption">内置：'+esc(p.text)+'</p><button class="jp-text-action" data-default="'+p.id+'">删除自定义 · 使用内置</button></details>').join('')+'</div>';}
function bindPromptFields(d){d.querySelectorAll('[data-default]').forEach(b=>b.onclick=()=>{d.querySelector('[data-prompt="'+b.dataset.default+'"]').value='';});}
function promptValues(d){return Object.fromEntries([...d.querySelectorAll('[data-prompt]')].map(t=>[t.dataset.prompt,t.value]));}
const promptHint='<p class="jp-sheet-caption">自定义文字优先使用，留空或删除后恢复内置。回复格式与字段规则由手机管理。</p>';
function chatSettings(){const d=sheet('聊天 App 设置','<div class="jp-page-intro"><small>MAKE IT YOURS</small><h2>聊天，也有你的语气。</h2></div>'+promptHint+promptFields('chat')+'<p class="jp-sheet-caption">信件风格可在邮件设置中修改；总预设与JSON导入在总设置中。</p><button class="jp-primary" data-save>保存聊天提示词</button>','jp-page');bindPromptFields(d);d.querySelector('[data-save]').onclick=async()=>{try{await bridge.saveCommunitySettings({appPrompts:promptValues(d)});d.remove();toast('聊天提示词已保存');}catch(e){d.querySelector('.jp-review-error').textContent=e.message;}};}
const mailSettings=smallButton('邮件设置','⚙',()=>{const data=uiCommunity(),labels={flirt:'暧昧来信',admirer:'匿名爱慕者',spam:'虚构小广告',harassment:'无礼来信'};const d=sheet('邮件设置','<div class="jp-page-intro"><small>LETTERS TO YOU</small><h2>等一封，喜欢的信。</h2></div><div class="jp-setting-list">'+Object.entries(labels).map(([k,v])=>'<label class="jp-toggle-row"><span>'+v+'</span><input type="checkbox" data-category="'+k+'" '+(data.mailPreferences[k]!==false?'checked':'')+' aria-label="接收'+v+'"></label>').join('')+'</div>'+promptHint+promptFields('mail')+'<details class="jp-prompt-item"><summary>额外来信偏好（保留旧设置）</summary><textarea aria-label="自定义来信规则内容" maxlength="3000">'+esc(data.mailCustomRules||'')+'</textarea></details><button class="jp-primary" data-save>保存邮件设置</button>','jp-page jp-mail-settings');bindPromptFields(d);d.querySelector('[data-save]').onclick=async()=>{try{await bridge.saveCommunitySettings({appPrompts:promptValues(d),mailCustomRules:d.querySelector('[aria-label="自定义来信规则内容"]').value,mailPreferences:Object.fromEntries([...d.querySelectorAll('[data-category]')].map(el=>[el.dataset.category,el.checked]))});d.remove();toast('邮件设置已保存');}catch(e){d.querySelector('.jp-review-error').textContent=e.message;}};});mailApp.querySelector('.app-head').append(mailSettings);
$('#chatApp .app-head').append(smallButton('聊天 App 设置','⚙',chatSettings));
const letterOpenBase=openLetter;openLetter=function(id){letterOpenBase(id);const dialog=$('.jp-letter');if(!dialog)return;dialog.setAttribute('role','dialog');dialog.setAttribute('aria-label','阅读信件');const close=smallButton('关闭信件','×',()=>dialog.remove());close.classList.add('jp-letter-x');dialog.append(close);dialog.addEventListener('keydown',e=>{if(e.key==='Escape')dialog.remove();});};
const feed=uiDocument.createElement('section');feed.id='jpFeedApp';feed.className='app';feed.innerHTML='<header class="app-head"><button class="back" aria-label="动态返回聊天">‹</button><b>朋友圈</b><div class="jp-feed-actions"></div></header><div class="app-body jp-feed-scroll"><div class="jp-feed-cover"><button class="jp-cover-edit" aria-label="更换朋友圈封面"><small>MOON VALLEY · MOMENTS</small><span>把日子，写成小事。</span><em>轻触更换封面</em></button><div class="jp-feed-self"><button class="jp-profile-id" aria-label="修改朋友圈ID"></button><button class="chat-avatar jp-self-avatar" aria-label="更换朋友圈头像"></button></div></div><div class="jp-feed-list"></div></div>';$('.screen').append(feed);
function openFeed(){goHome();$('#home').style.display='none';$('#screen').classList.add('app-open');feed.classList.add('active');drawFeed();}
function closeFeed(){feed.classList.remove('active');$('#chatApp').classList.add('active');$('#chatListView').hidden=false;$('#chatRoom').hidden=true;$('#chatApp').classList.remove('chat-room-open');}
feed.querySelector('.back').onclick=closeFeed;
const navIcon={chat:'<svg viewBox="0 0 24 24"><path d="M5 4h14a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2h-8l-6 3v-3a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2Z"/><path d="M7 9h10M7 13h6"/></svg>',feed:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="m15 8-2 5-5 3 2-6 5-2Z"/></svg>'};
function socialNav(selected){const nav=uiDocument.createElement('nav');nav.className='jp-social-nav';nav.setAttribute('aria-label','聊天与朋友圈');nav.innerHTML=[['chat','消息'],['feed','朋友圈']].map(([id,label])=>'<button aria-label="切换到'+label+'" '+(selected===id?'aria-current="page"':'')+' data-tab="'+id+'">'+navIcon[id]+'<span>'+label+'</span></button>').join('');nav.querySelector('[data-tab="chat"]').onclick=closeFeed;nav.querySelector('[data-tab="feed"]').onclick=openFeed;return nav;}
$('#chatListView').append(socialNav('chat'));feed.append(socialNav('feed'));
function profileAvatar(){const data=uiCommunity(),item=bridge.getImage(data.profile?.avatar);return item?'<img class="jp-custom-avatar" src="'+esc(item.dataUrl)+'" alt="我的朋友圈头像">':'<span class="jp-user-initial">'+esc((data.profile?.id||data.userName||'我').slice(0,1))+'</span>';}
function editProfile(field){const data=uiCommunity(),labels={id:'朋友圈 ID',avatar:'朋友圈头像',cover:'朋友圈封面'};const d=sheet('修改'+labels[field],field==='id'?'<p class="jp-sheet-caption">这是你的公开昵称。改名后，朋友们仍然知道是你。</p><input aria-label="朋友圈ID" maxlength="32" value="'+esc(data.profile?.id||data.userName)+'"><button class="jp-primary" data-save>保存 ID</button>':'<p class="jp-sheet-caption">选择一张自己的图片，装点这片小天地。</p><label class="jp-profile-upload">＋ 从本地选择图片<input aria-label="上传'+labels[field]+'" type="file" accept="image/png,image/jpeg,image/webp,image/gif"></label><button class="jp-text-action" data-reset>恢复默认'+(field==='avatar'?'头像':'封面')+'</button>','jp-profile-sheet');const run=data.chatId;async function save(value){if(run!==uiCommunity().chatId)throw Error('对话已切换，请重新打开设置');await bridge.saveFeedProfile({[field]:value});d.remove();drawFeed();}if(field==='id')d.querySelector('[data-save]').onclick=()=>save(d.querySelector('input').value).catch(e=>d.querySelector('.jp-review-error').textContent=e.message);else{d.querySelector('input').onchange=async e=>{const input=e.target;if(!input.files[0])return;input.disabled=true;try{let source=await bridge.prepareSticker(input.files[0]);if(field==='avatar'&&d.isConnected)source=await bridge.cropAvatar(source,d);if(source&&d.isConnected)await save(source);}catch(err){d.querySelector('.jp-review-error').textContent=err.message;}finally{input.disabled=false;input.value='';}};d.querySelector('[data-reset]').onclick=()=>save(null).catch(e=>d.querySelector('.jp-review-error').textContent=e.message);}}
feed.querySelector('.jp-profile-id').onclick=()=>editProfile('id');feed.querySelector('.jp-self-avatar').onclick=()=>editProfile('avatar');feed.querySelector('.jp-cover-edit').onclick=()=>editProfile('cover');
function composePost(){const d=sheet('发说说','<p class="jp-sheet-caption">分享给月亮谷的朋友们</p><textarea class="jp-post-text" aria-label="说说内容" maxlength="600" placeholder="这一刻，想说点什么…"></textarea><label class="jp-form-label">模拟配图（选填）<textarea class="jp-post-image" aria-label="动态配图描述" maxlength="1000" placeholder="描述画面，例如：傍晚的田野，刚浇完水的幼苗泛着光"></textarea></label><p class="jp-sheet-caption">配图显示为可点击的虚拟照片。</p><button class="jp-primary" data-publish>发布</button>');d.querySelector('[data-publish]').onclick=async e=>{e.currentTarget.disabled=true;try{await bridge.publishPost(d.querySelector('.jp-post-text').value,d.querySelector('.jp-post-image').value);d.remove();drawFeed();}catch(err){d.querySelector('.jp-review-error').textContent=err.message;e.currentTarget.disabled=false;}};}
function commentAuthor(id,data){return id==='me'?(data.profile?.id||data.userName):chatRoles.find(r=>r.id===id)?.name||'村民';}
function commentMarkup(post,data){if(!post.comments?.length)return '';return '<div class="jp-comments">'+post.comments.map(c=>{const parent=post.comments.find(x=>x.id===c.replyTo);return '<div class="jp-comment"><button data-reply-comment="'+esc(c.id)+'" data-post="'+esc(post.id)+'" aria-label="回复'+esc(commentAuthor(c.authorId,data))+'的评论"><b>'+esc(commentAuthor(c.authorId,data))+'</b>'+(parent?' 回复 <b>'+esc(commentAuthor(parent.authorId,data))+'</b>':'')+'：'+esc(c.text)+'</button><button class="jp-comment-delete" data-delete-comment="'+esc(c.id)+'" aria-label="删除评论">×</button></div>';}).join('')+'</div>';}
function commentComposer(postId,replyTo){feed.querySelector('.jp-comment-composer')?.remove();const anchor=Array.from(feed.querySelectorAll('[data-comment-post]')).find(b=>b.dataset.commentPost===postId);if(!anchor)return;const wrap=uiDocument.createElement('div');wrap.className='jp-comment-composer';wrap.innerHTML='<textarea aria-label="动态评论内容" maxlength="500" placeholder="'+(replyTo?'回复这条评论…':'说点什么…')+'"></textarea><div><button data-cancel>取消</button><button data-send>发送评论</button></div><small role="status"></small>';anchor.closest('.jp-post-main').append(wrap);wrap.querySelector('[data-cancel]').onclick=()=>wrap.remove();wrap.querySelector('[data-send]').onclick=async e=>{e.currentTarget.disabled=true;try{await bridge.publishComment(postId,wrap.querySelector('textarea').value,replyTo);wrap.remove();}catch(err){wrap.querySelector('small').textContent=err.message;e.currentTarget.disabled=false;}};wrap.querySelector('textarea').focus();}
function feedSettings(){const d=sheet('动态设置','<p class="jp-sheet-caption">正文推进或聊天回复后，有机会出现新的角色动态。</p><label class="jp-form-label">发布频率<select aria-label="角色动态频率">'+[['off','关闭'],['low','偶尔 · 15%'],['normal','正常 · 35%'],['high','频繁 · 70%']].map(([k,v])=>'<option value="'+k+'" '+(uiCommunity().feedFrequency===k?'selected':'')+'>'+v+'</option>').join('')+'</select></label><label class="jp-form-label">角色评论频率<select aria-label="角色评论频率">'+[['off','关闭'],['low','偶尔 · 15%'],['normal','正常 · 35%'],['high','频繁 · 70%']].map(([k,v])=>'<option value="'+k+'" '+((uiCommunity().commentFrequency||'normal')===k?'selected':'')+'>'+v+'</option>').join('')+'</select></label>'+promptFields('feed')+'<p class="jp-sheet-caption">角色可以评论你、自己和其他角色的动态，也会互相回复；概率独立于发说说。触发时使用手机当前 API；关闭不影响你自己发说说。</p><button class="jp-primary" data-save>保存设置</button>');bindPromptFields(d);d.querySelector('[data-save]').onclick=async()=>{try{await bridge.saveCommunitySettings({feedFrequency:d.querySelector('[aria-label="角色动态频率"]').value,commentFrequency:d.querySelector('[aria-label="角色评论频率"]').value,appPrompts:Object.fromEntries(Array.from(d.querySelectorAll('[data-prompt]')).map(x=>[x.dataset.prompt,x.value]))});d.remove();toast('动态频率已保存');}catch(e){d.querySelector('.jp-review-error').textContent=e.message;}};}
feed.querySelector('.jp-feed-actions').append(smallButton('动态设置','⚙',feedSettings),smallButton('发说说','＋',composePost));
function drawFeed(){const data=uiCommunity(),name=data.profile?.id||data.userName,cover=bridge.getImage(data.profile?.cover),coverEl=feed.querySelector('.jp-feed-cover');coverEl.style.backgroundImage=cover?'linear-gradient(0deg,#282c3844,transparent 65%),url("'+cover.dataUrl.replaceAll('"','%22')+'")':'';coverEl.classList.toggle('has-cover',!!cover);feed.querySelector('.jp-profile-id').textContent=name;feed.querySelector('.jp-self-avatar').innerHTML=profileAvatar();feed.querySelector('.jp-feed-list').innerHTML=data.posts.length?data.posts.map(p=>{const role=chatRoles.find(r=>r.id===p.authorId),author=p.authorId==='me'?name:role?.name||'村民';return '<article class="jp-post"><span class="chat-avatar">'+(p.authorId==='me'?profileAvatar():role?threadPortrait(role):'<span class="jp-user-initial">'+esc(author.slice(0,1))+'</span>')+'</span><div class="jp-post-main"><b>'+esc(author)+'</b><p>'+esc(p.text)+'</p>'+(p.imageDescription?'<button class="jp-virtual-photo" data-photo="'+esc(p.id)+'" aria-label="查看'+esc(author)+'的动态配图"><span>▧</span><small>一帧日常</small><em>点击查看画面</em></button>':'')+'<footer>'+esc([p.storyDate,p.time].filter(Boolean).join(' · ')||'刚刚')+'<button class="jp-post-delete" data-comment-post="'+esc(p.id)+'" aria-label="评论'+esc(author)+'的动态">评论</button><button class="jp-post-delete" data-delete-post="'+esc(p.id)+'" aria-label="删除'+esc(author)+'的动态">删除</button></footer>'+commentMarkup(p,data)+'</div></article>';}).join(''):'<div class="jp-feed-empty"><span>✧</span><h3>故事还在发生</h3><p>发一条说说，留住今天的小事。<br>朋友们的动态也会出现在这里。</p><button class="jp-primary" data-first-post>写第一条说说</button></div>';feed.querySelectorAll('[data-comment-post]').forEach(b=>b.onclick=()=>commentComposer(b.dataset.commentPost));feed.querySelectorAll('[data-reply-comment]').forEach(b=>b.onclick=()=>commentComposer(b.dataset.post,b.dataset.replyComment));feed.querySelectorAll('[data-delete-comment]').forEach(b=>b.onclick=()=>bridge.deleteFeedComment(b.dataset.deleteComment).catch(e=>toast(e.message)));feed.querySelectorAll('[data-delete-post]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await bridge.deleteFeedPost(b.dataset.deletePost);}catch(e){toast(e.message);b.disabled=false;}});feed.querySelector('[data-first-post]')?.addEventListener('click',composePost);feed.querySelectorAll('[data-photo]').forEach(b=>b.onclick=()=>{const p=data.posts.find(x=>x.id===b.dataset.photo);sheet('照片里的这一刻','<div class="jp-photo-illustration">▧</div><p class="jp-photo-description">'+esc(p.imageDescription)+'</p>');});}
const roomSettings=smallButton('聊天设置','⋯',()=>{
 const role=activeRole;if(!role)return;const run=uiCommunity().chatId,isGroup=!!role.members;
 const entries=[...(isGroup?[['group','群聊头像']]:[]),['me','我的头像'],...(isGroup?role.members.map(id=>[id,chatRoles.find(r=>r.id===id)?.name||'成员']):[['role',role.name]])];
 const avatar=who=>who==='me'?userPortrait(role.id):['role','group'].includes(who)?threadPortrait(role):memberPortrait(chatRoles.find(r=>r.id===who),role);
 const memberName=id=>displayName(chatRoles.find(r=>r.id===id),role);
 const row=(label,value,action)=>'<button type="button" class="jp-info-row" data-info="'+action+'"><span>'+label+'</span><em data-info-value="'+action+'">'+esc(value)+'</em><i>›</i></button>';
 const face=(who,title)=>'<button type="button" class="chat-avatar jp-info-avatar" data-face="'+who+'" aria-label="更换'+esc(title)+'">'+avatar(who)+'</button>';
 const members=isGroup?'<section class="jp-info-card jp-info-members"><div class="jp-info-section-head"><b>群成员</b><small>'+ (role.members.length+1)+' 人</small></div><div class="jp-member-grid"><div class="jp-member-tile">'+face('me','我的头像')+'<span>我</span></div>'+role.members.map(id=>'<div class="jp-member-tile">'+face(id,memberName(id)+'的头像')+'<button type="button" class="jp-member-name" data-member-name="'+id+'" aria-label="修改'+esc(memberName(id))+'的群内备注">'+esc(memberName(id))+'</button></div>').join('')+'</div></section>':'';
 const d=sheet(isGroup?'聊天信息':'聊天设置','<section class="jp-info-card jp-contact-card">'+face(isGroup?'group':'role',isGroup?'群聊头像':role.name+'的头像')+'<div><button type="button" class="jp-contact-name" data-info="name">'+esc(displayName(role))+'</button><small>'+esc(isGroup?'点头像换图片 · 点名字改群名称':role.name+' · 点名字改备注')+'</small></div></section>'+members+'<section class="jp-info-card">'+row(isGroup?'群名称':'备注',displayName(role),'name')+(!isGroup?'<div class="jp-info-self"><span>我的头像</span>'+face('me','我的头像')+'<small>轻触更换</small></div>':'')+'</section><section class="jp-info-card">'+(isGroup?row('成员头像','跟随私聊头像','follow'):row('我的头像','跟随朋友圈头像','follow-me'))+'</section><p class="jp-info-hint">'+(isGroup?'轻触成员头像换图片，轻触名字改备注。群内备注留空时跟随私聊备注。':'头像和备注仅用于当前聊天。我的头像默认跟随朋友圈，单独更换后保留独立头像。')+'</p>','jp-page jp-room-settings jp-info-page');
 const ensureCurrent=()=>{if(run!==uiCommunity().chatId||!d.isConnected)throw Error('对话已切换，请重新打开聊天设置');};
 function refresh(){if(!d.isConnected)return;d.querySelectorAll('[data-face]').forEach(el=>el.innerHTML=avatar(el.dataset.face));d.querySelector('.jp-contact-name').textContent=displayName(role);d.querySelector('[data-info-value="name"]').textContent=displayName(role);d.querySelectorAll('[data-member-name]').forEach(el=>{el.textContent=memberName(el.dataset.memberName);el.setAttribute('aria-label','修改'+el.textContent+'的群内备注');});const custom=uiCommunity().avatars?.[role.id]||{};const follow=d.querySelector('[data-info-value="follow-me"]');if(follow)follow.textContent=custom.me?'已使用独立头像':'跟随朋友圈头像';renderChatThreads();if(activeRole?.id===role.id)renderChatRoom(role);}
 async function save(who,source){ensureCurrent();await bridge.saveAvatar(role.id,who,source);refresh();}
 function editName(memberId){ensureCurrent();const names=uiCommunity().chatNames?.[role.id]||{},title=memberId?'成员备注':isGroup?'群名称':'角色备注',fallback=memberId?displayName(chatRoles.find(r=>r.id===memberId)):role.name,value=memberId?names.members?.[memberId]||'':names.name||'';
 const editor=sheet('修改'+title,'<p class="jp-sheet-caption">'+(memberId?'仅用于这个群聊，留空跟随私聊备注。':'留空恢复原名，角色身份不会改变。')+'</p><label class="jp-form-label">'+title+'<input class="jp-name-input" aria-label="'+title+'" maxlength="32" value="'+esc(value)+'" placeholder="'+esc(fallback)+'"></label><button type="button" class="jp-primary" data-save-name>保存</button>','jp-contact-editor');
 editor.querySelector('[data-save-name]').onclick=async e=>{e.currentTarget.disabled=true;try{ensureCurrent();const input=editor.querySelector('input').value;await bridge.saveChatNames(role.id,memberId?{members:{[memberId]:input}}:{name:input});refresh();editor.remove();}catch(err){editor.querySelector('.jp-review-error').textContent=err.message;}finally{e.currentTarget.disabled=false;}};
 }
 function editAvatar(who){ensureCurrent();const title=entries.find(e=>e[0]===who)[1],reset=who==='me'?'跟随朋友圈头像':who==='group'?'恢复默认头像':isGroup?'跟随私聊头像':'恢复默认头像';
 const editor=sheet(title,'<div class="jp-avatar-editor-preview"><span class="chat-avatar">'+avatar(who)+'</span></div><label class="jp-avatar-pick jp-editor-upload">选择图片并裁剪<input type="file" accept="image/png,image/jpeg,image/webp,image/gif" aria-label="上传'+esc(title)+'"></label><button type="button" class="jp-text-action jp-editor-reset" data-reset-avatar>'+reset+'</button><details class="jp-avatar-url"><summary>使用图片直链</summary><input type="url" aria-label="头像图片直链" placeholder="https://…"><button type="button" class="jp-primary" data-save-url>应用头像</button></details>','jp-contact-editor');
 const file=editor.querySelector('[type=file]');file.onchange=async()=>{if(!file.files[0])return;file.disabled=true;try{const prepared=await bridge.prepareSticker(file.files[0]);if(!editor.isConnected)return;const cropped=await bridge.cropAvatar(prepared,editor);if(cropped&&editor.isConnected){await save(who,cropped);editor.remove();}}catch(err){editor.querySelector('.jp-review-error').textContent=err.message;}finally{file.disabled=false;file.value='';}};
 editor.querySelector('[data-reset-avatar]').onclick=async e=>{e.currentTarget.disabled=true;try{await save(who,null);editor.remove();}catch(err){editor.querySelector('.jp-review-error').textContent=err.message;e.currentTarget.disabled=false;}};
 editor.querySelector('[data-save-url]').onclick=async e=>{e.currentTarget.disabled=true;try{await save(who,bridge.validateImageSource(editor.querySelector('[type=url]').value));editor.remove();}catch(err){editor.querySelector('.jp-review-error').textContent=err.message;e.currentTarget.disabled=false;}};
 }
 d.querySelectorAll('[data-face]').forEach(el=>el.onclick=()=>editAvatar(el.dataset.face));d.querySelectorAll('[data-member-name]').forEach(el=>el.onclick=()=>editName(el.dataset.memberName));
 d.querySelectorAll('[data-info="name"]').forEach(el=>el.onclick=()=>editName());d.querySelector('[data-info="follow-me"]')?.addEventListener('click',()=>editAvatar('me'));
 d.querySelector('[data-info="follow"]')?.addEventListener('click',()=>{const editor=sheet('成员头像','<p class="jp-sheet-caption">所有角色成员恢复跟随各自的私聊头像。你的头像仍由你单独设置。</p><button type="button" class="jp-primary" data-follow-all>全部跟随私聊头像</button>','jp-contact-editor');editor.querySelector('[data-follow-all]').onclick=async e=>{e.currentTarget.disabled=true;try{for(const id of role.members){ensureCurrent();await save(id,null);}editor.remove();toast('成员头像已跟随私聊');}catch(err){editor.querySelector('.jp-review-error').textContent=err.message;e.currentTarget.disabled=false;}};});refresh();
});$('#chatRoom .chat-room-bar').append(roomSettings);
function openPromptPresets(){
 const d=sheet('预设提示词','<div class="jp-page-intro"><small>YOUR PHONE · YOUR WORDS</small><h2>写下你的聊天风格。</h2></div>'+promptHint+'<div class="jp-preset-tools"><label class="jp-form-label">预设名称<input data-preset-name aria-label="预设名称" maxlength="80" value="'+esc(uiCommunity().presetName||'我的手机预设')+'"></label><label class="jp-avatar-pick">导入 JSON<input type="file" accept=".json,application/json" data-import aria-label="导入JSON预设"></label><button class="jp-text-action" data-export>导出 JSON</button><button class="jp-text-action" data-clear>删除全部自定义</button><p data-import-status role="status"></p></div>'+promptFields('all')+'<button class="jp-primary" data-save>保存预设</button>','jp-page jp-preset-settings');
 bindPromptFields(d);d.querySelector('[data-save]').onclick=async()=>{try{await bridge.saveCommunitySettings({appPrompts:promptValues(d),replacePrompts:true,presetName:d.querySelector('[data-preset-name]').value});toast('预设已保存，下次生成生效');d.remove();}catch(e){d.querySelector('.jp-review-error').textContent=e.message;}};
 d.querySelector('[data-clear]').onclick=()=>{d.querySelectorAll('[data-prompt]').forEach(el=>el.value='');d.querySelector('[data-import-status]').textContent='已清空自定义；保存后全部使用内置预设。';};
 d.querySelector('[data-import]').onchange=async e=>{const input=e.currentTarget,file=input.files[0];if(!file)return;try{if(file.size>1024*1024)throw Error('预设文件最多1MB');const preset=bridge.importPromptPreset(await file.text());d.querySelectorAll('[data-prompt]').forEach(el=>el.value=preset.prompts[el.dataset.prompt]||'');d.querySelector('[data-preset-name]').value=preset.name;d.querySelector('[data-import-status]').textContent='已载入 '+preset.name+'；保存后生效，未填写的项目使用内置。';d.querySelector('.jp-review-error').textContent='';}catch(err){d.querySelector('.jp-review-error').textContent=err.message;}finally{input.value='';}};
 d.querySelector('[data-export]').onclick=()=>{const text=bridge.exportPromptPreset(promptValues(d),d.querySelector('[data-preset-name]').value||'我的手机预设'),url=URL.createObjectURL(new Blob([text],{type:'application/json;charset=utf-8'})),a=uiDocument.createElement('a');a.href=url;a.download='月亮谷手机-预设.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
}
function updateCommunity(){drawFeed();roomSettings.hidden=false;}
