import {parseResponseJSON} from './json-response.js';
export const mailDefaults={flirt:true,admirer:true,spam:true,harassment:true};
export const mailLabels={flirt:'暧昧来信',admirer:'匿名爱慕',spam:'小广告',harassment:'无礼来信'};
export function mailPreferences(value={}){return Object.fromEntries(Object.keys(mailDefaults).map(k=>[k,value[k]!==false]));}
export function mailRule(value={},random=Math.random){const prefs=mailPreferences(value),enabled=Object.keys(prefs).filter(k=>prefs[k]);const category=enabled.length&&random()<.3?enabled[Math.floor(random()*enabled.length)]:null;return '信件可选category为regular、flirt、admirer、spam、harassment。关闭的类别禁止生成：'+Object.keys(prefs).filter(k=>!prefs[k]).join('、')+'。本次'+(category?'允许偶尔附带一封'+mailLabels[category]+'，不强制；其他特殊类别不要生成':'只生成regular普通来信')+'。所有信件保持不露骨；无礼来信仅轻度冒犯，不含威胁、歧视或性骚扰；广告仅虚构店铺，不含真实网址、支付或联系方式。陌生人只能发普通、暧昧、匿名爱慕、广告或无礼信，使用senderId="stranger"、senderName="虚构署名"，不能发委托或赠送、不能知道私聊。匿名爱慕设anonymous=true。已知角色必须使用真实角色ID，不能借匿名泄露他人隐私。';}
export const feedRates={off:0,low:.15,normal:.35,high:.7};
export function shouldPost(rate='normal',random=Math.random){return random()<(feedRates[rate]??feedRates.normal);}
export function allPosts(s){return [...(s.posts||[]),...(s.turns||[]).flatMap(t=>t.posts||[])].sort((a,b)=>b.created-a.created);}
export function parsePosts(raw,roles,allowed=roles.map(r=>r.id)){const data=parseResponseJSON(raw);if(!Array.isArray(data.posts)||data.posts.length>2)throw Error('动态格式无效');return data.posts.map(p=>{if(!allowed.includes(p.roleId)||!roles.some(r=>r.id===p.roleId)||typeof p.text!=='string'||!p.text.trim()||p.text.length>600)throw Error('动态作者或文字无效');if(p.imageDescription!=null&&(typeof p.imageDescription!=='string'||p.imageDescription.length>1000))throw Error('动态配图说明无效');return {id:crypto.randomUUID(),authorId:p.roleId,text:p.text.trim(),imageDescription:(p.imageDescription||'').trim(),created:Date.now()};});}
export function publicMemory(s,roles){return '【公开朋友圈动态，仅作已发生记录】\n'+JSON.stringify(allPosts(s).slice(0,20).map(p=>({author:p.authorId==='me'?'用户':roles.find(r=>r.id===p.authorId)?.name||'村民',text:p.text,imageDescription:p.imageDescription,date:p.storyDate,time:p.time})))+'\n【公开动态结束】';}
export function makeUserPost(text,imageDescription=''){text=String(text).trim();imageDescription=String(imageDescription).trim();if(!text&&!imageDescription)throw Error('先写点文字或配图描述吧');if(text.length>600||imageDescription.length>1000)throw Error('动态文字最多600字，配图描述最多1000字');return {id:crypto.randomUUID(),authorId:'me',text,imageDescription,created:Date.now()};}
