import test from 'node:test';import assert from 'node:assert/strict';import {customGroup,saveCssPreset,scopedChatCss,effectiveCssPresetId} from './customization.js';import {groups,phoneTimeline,participants} from './phone-memory.js';import {pendingThreads,parseBatch} from './round-sync.js';import {parseFollowups} from './chat-protocol.js';import {narrativeMemory} from './social.js';
const roles=[{id:'01',name:'阿德里安'},{id:'02',name:'哈兰'},{id:'03',name:'艾利安'}];
test('custom groups require two distinct known roles and stable unique group IDs',()=>{assert.throws(()=>customGroup('group-custom-x','',['01'],roles));assert.throws(()=>customGroup('group-custom-x','',['01','01'],roles));assert.throws(()=>customGroup('group-custom-x','',['01','bad'],roles));const group=customGroup('group-custom-x','朋友们',['01','02','01'],roles);assert.deepEqual(group.members,['01','02']);assert.throws(()=>customGroup('group-custom-x','',['01','02'],roles,[group]));assert.equal(groups(roles,[group]).at(-1).id,group.id);assert.deepEqual(groups(roles).map(g=>g.id),['group-all','group-twins']);});
test('new groups participate in batched replies with strict member validation and shared memory visibility',()=>{const group=customGroup('group-custom-x','朋友们',['01','02'],roles),s={customGroups:[group],manual:[{id:'u',roleId:group.id,from:'me',created:1,text:'早安',status:'queued'}],turns:[],socialEvents:[]};const pending=pendingThreads(s,roles);assert.equal(pending[0].role.id,group.id);const parsed=parseBatch(JSON.stringify({replies:[{threadId:group.id,messages:[{roleId:'01',text:'早安'}]}]}),pending,roles);assert.equal(parsed[0].bubbles[0].speakerId,'01');assert.throws(()=>parseBatch(JSON.stringify({replies:[{threadId:group.id,messages:[{roleId:'03',text:'偷听'}]}]}),pending,roles));assert.deepEqual(participants(group.id,roles,s.customGroups),['01','02']);assert.equal(phoneTimeline(s,roles[2],roles).length,0);assert.deepEqual(phoneTimeline(s,roles[0],roles)[0].visibleTo,['01','02']);assert(narrativeMemory(s,roles).includes('阿德里安'));assert(narrativeMemory(s,roles).includes('哈兰'));assert(!narrativeMemory(s,roles).includes('艾利安'));});
test('followups may target new groups only when the speaker belongs to that group',()=>{const group=customGroup('group-custom-x','朋友们',['01','02'],roles),raw=JSON.stringify({bubbles:['好'],followups:[{threadId:group.id,speakerId:'01',type:'text',text:'群里说吧'}]});assert.equal(parseFollowups(raw,roles[0],roles,[],[group])[0].roleId,group.id);assert.throws(()=>parseFollowups(raw,roles[0],roles));assert.throws(()=>parseFollowups(raw.replaceAll('01','03'),roles[2],roles,[],[group]));});
test('CSS library stores independent named presets and rejects HTML and imports without mutating the original',()=>{const original=[{id:'a',name:'玻璃',css:'.chat-bubble{opacity:.8}'}],next=saveCssPreset(original,{id:'b',name:'纸张',css:'.chat-bubble{background:white}'});assert.equal(next.length,2);assert.equal(original.length,1);const revised=saveCssPreset(next,{id:'a',name:'玻璃2',css:'.chat-bubble{opacity:.9}'});assert.equal(revised.length,2);assert.throws(()=>saveCssPreset(original,{id:'b',name:'x',css:'<style>x</style>'}));assert.throws(()=>saveCssPreset(original,{id:'b',name:'x',css:'@import "https://example.com/a.css";'}));});
test('CSS scopes selectors and nested media rules to an open chat, overrides defaults and cleans its parser',()=>{const declaration={0:'color',length:1,getPropertyValue:()=> 'red'},rule={selectorText:'.chat-bubble, :is(.incoming,.outgoing)',style:declaration},media={cssText:'@media(max-width:500px){x}',cssRules:[{selectorText:':root',style:declaration}]};let removed=false;const style={sheet:{cssRules:[rule,media]},remove(){removed=true;}},document={createElement:()=>style,head:{append(node){assert.equal(node.media,'not all');}}};const result=scopedChatCss('.chat-bubble{color:red}',document);assert(result.includes('#chatApp.chat-room-open .chat-bubble'));assert(result.includes('#chatApp.chat-room-open :is(.incoming,.outgoing)'));assert(result.includes('@media(max-width:500px){#chatApp.chat-room-open{color:red !important;}'));assert.equal(removed,true);assert.throws(()=>scopedChatCss('@import "x";',document));});

test('global default CSS applies only to chats without their own override, and null restores built-in appearance',()=>{const appearance={defaultCssPresetId:'blue',cssPresets:[{id:'blue',css:'x'}]};assert.equal(effectiveCssPresetId(appearance,{}),'blue');assert.equal(effectiveCssPresetId(appearance,{cssPresetId:'green'}),'green');assert.equal(effectiveCssPresetId(appearance,{cssPresetId:null}),null);assert.equal(effectiveCssPresetId({},{}),null);assert.equal(appearance.cssPresets.length,1);});

test('global CSS covers app list and dialog roots, without nesting explicit app selectors twice',()=>{const style={0:'background',length:1,getPropertyValue:()=> 'white'},rules=['.chat-thread','.jp-info-page',':root','#chatApp .app-head'].map(selectorText=>({selectorText,style}));const document={head:{append(){}},createElement:()=>({sheet:{cssRules:rules},remove(){}})};const css=scopedChatCss('x',document,'global');assert(css.includes(':is(#chatApp,.jp-chat-surface) .chat-thread'));assert(css.includes(':is(#chatApp,.jp-chat-surface).jp-info-page'));assert(css.includes(':is(#chatApp,.jp-chat-surface){'));assert(css.includes('#chatApp .app-head{'));assert(!css.includes('#chatApp #chatApp'));assert(!css.includes('chat-room-open'));});
