const appearanceStyle=uiDocument.createElement('style'),chatCssStyle=uiDocument.createElement('style');uiRoot.append(appearanceStyle,chatCssStyle);
const iconEntries=[...$$('#home .app-icon')].map((button,i)=>({button,id:button.dataset.open||button.id||button.querySelector('small')?.textContent||String(i),label:button.querySelector('small')?.textContent||'APP',box:button.querySelector('.icon-box')})).filter(e=>e.box);const defaultIcons=new Map(iconEntries.map(e=>[e.id,e.box.innerHTML]));
const iconSources=new Map();let compiledSource='',compiledCss='';
const beforeCustomThreads=renderChatThreads;renderChatThreads=function(){threadRoles=[...groupRoles,...(uiCommunity().customGroups||[]),...chatRoles];beforeCustomThreads();};
const beforeAppearanceRoom=renderChatRoom;renderChatRoom=function(role){beforeAppearanceRoom(role);updateAppearance();};
const beforeCommunityAppearance=updateCommunity;updateCommunity=function(){beforeCommunityAppearance();renderChatThreads();updateAppearance();};
function updateAppearance(){const data=uiCommunity(),appearance=data.appearance||{},thread=data.chatAppearance?.[activeRole?.id]||{},image=id=>bridge.getImage(id)?.dataUrl;
 const wallpaper=(selector,id)=>{const source=image(id);return source?selector+'{background-image:url("'+source.replaceAll('"','%22')+'")!important;background-size:cover!important;background-position:center!important;background-repeat:no-repeat!important}':'';};
 appearanceStyle.textContent=wallpaper('#home',appearance.homeWallpaper)+wallpaper('#chatApp #chatListView',appearance.listWallpaper)+wallpaper('#chatApp.chat-room-open .chat-room-body',thread.wallpaper);
 for(const entry of iconEntries){const source=image(appearance.icons?.[entry.id])||'';if(iconSources.get(entry.id)===source)continue;iconSources.set(entry.id,source);if(source){entry.box.innerHTML='<img class="jp-custom-app-icon" alt="'+esc(entry.label)+'" src="'+esc(source)+'">';}else entry.box.innerHTML=defaultIcons.get(entry.id);}
 const preset=appearance.cssPresets?.find(p=>p.id===thread.cssPresetId);try{if(preset&&preset.css!==compiledSource){compiledCss=bridge.scopedChatCss(preset.css);compiledSource=preset.css;}chatCssStyle.textContent=preset?compiledCss:'';}catch{chatCssStyle.textContent='';}
}
function appearanceError(dialog,e){dialog.querySelector('.jp-review-error').textContent=e.message;}
function openAppearance(kind,thread){const data=uiCommunity(),run=data.chatId;const check=()=>{if(thread&&run!==uiCommunity().chatId)throw Error('对话已切换，请重新打开外观设置');};
 if(kind==='css')return openChatCss(thread);
 const title=kind==='phone'?'手机外观':kind==='list'?'聊天列表壁纸':'聊天壁纸',scope=kind==='phone'?'home':kind==='list'?'list':'thread';
 const dialog=sheet(title,'<div class="jp-wallpaper-preview" data-wall-preview></div><label class="jp-profile-upload">选择壁纸<input type="file" accept="image/png,image/jpeg,image/webp,image/gif" data-wall-file></label><button type="button" class="jp-text-action" data-wall-reset>恢复默认壁纸</button>'+(kind==='phone'?'<h4>APP图标</h4><p class="jp-sheet-caption">点击图标更换，上传后可裁剪。</p><div class="jp-icon-custom-grid">'+iconEntries.map(e=>'<button type="button" data-custom-icon="'+esc(e.id)+'"><span class="icon-box">'+e.box.innerHTML+'</span><span>'+esc(e.label)+'</span></button>').join('')+'</div>':'') ,'jp-contact-editor jp-appearance-editor');
 function preview(){const current=uiCommunity(),id=scope==='home'?current.appearance?.homeWallpaper:scope==='list'?current.appearance?.listWallpaper:current.chatAppearance?.[thread.id]?.wallpaper,source=bridge.getImage(id)?.dataUrl;dialog.querySelector('[data-wall-preview]').style.backgroundImage=source?'url("'+source.replaceAll('"','%22')+'")':'';}
 const input=dialog.querySelector('[data-wall-file]');input.onchange=async()=>{if(!input.files[0])return;input.disabled=true;try{check();const source=await bridge.prepareSticker(input.files[0]);if(!dialog.isConnected)return;check();await bridge.saveAppearance(scope,{wallpaper:source},thread?.id);preview();}catch(e){appearanceError(dialog,e);}finally{input.disabled=false;input.value='';}};
 dialog.querySelector('[data-wall-reset]').onclick=async()=>{try{check();await bridge.saveAppearance(scope,{wallpaper:null},thread?.id);preview();}catch(e){appearanceError(dialog,e);}};
 dialog.querySelectorAll('[data-custom-icon]').forEach(button=>button.onclick=()=>{const entry=iconEntries.find(e=>e.id===button.dataset.customIcon),editor=sheet(entry.label+'图标','<label class="jp-profile-upload">选择图片并裁剪<input type="file" accept="image/png,image/jpeg,image/webp,image/gif"></label><button type="button" class="jp-text-action" data-reset-icon>恢复默认图标</button>','jp-contact-editor');const file=editor.querySelector('input');file.onchange=async()=>{if(!file.files[0])return;file.disabled=true;try{const source=await bridge.prepareSticker(file.files[0]),cropped=editor.isConnected?await bridge.cropAvatar(source,editor):null;if(cropped&&editor.isConnected){await bridge.saveAppearance('icon',{appId:entry.id,icon:cropped});button.querySelector('.icon-box').innerHTML=entry.box.innerHTML;editor.remove();}}catch(e){appearanceError(editor,e);}finally{file.disabled=false;file.value='';}};editor.querySelector('[data-reset-icon]').onclick=async()=>{try{await bridge.saveAppearance('icon',{appId:entry.id,icon:null});button.querySelector('.icon-box').innerHTML=entry.box.innerHTML;editor.remove();}catch(e){appearanceError(editor,e);}};});preview();
}
function openChatCss(thread){const run=uiCommunity().chatId,dialog=sheet('气泡与界面外观','<label class="jp-form-label">已保存的预设<select data-style-choice></select></label><label class="jp-form-label">预设名称<input data-style-name maxlength="40" placeholder="例如：清透玻璃气泡"></label><label class="jp-profile-upload">导入 CSS 文件<input type="file" accept=".css,.txt,text/css,text/plain" data-css-file></label><textarea class="jp-css-editor" aria-label="聊天CSS" spellcheck="false" placeholder=".chat-bubble { background: #fff; color: #333; border-radius: 16px; }"></textarea><p class="jp-sheet-caption">填写纯CSS，可使用 .chat-bubble、.incoming、.outgoing、.chat-room-body、.chat-room-bar、.chat-composer。仅用于当前聊天。</p><button type="button" class="jp-primary" data-css-save>保存并应用</button><button type="button" class="jp-text-action" data-css-apply>使用选中的预设</button><button type="button" class="jp-text-action" data-css-reset>一键恢复默认外观</button>','jp-page jp-css-settings');
 const choice=dialog.querySelector('select'),name=dialog.querySelector('[data-style-name]'),text=dialog.querySelector('textarea');
 const check=()=>{if(run!==uiCommunity().chatId)throw Error('对话已切换，请重新打开CSS设置');};
 function list(selected){choice.innerHTML='<option value="">默认外观</option><option value="__new__">新建预设</option>'+(uiCommunity().appearance?.cssPresets||[]).map(p=>'<option value="'+esc(p.id)+'">'+esc(p.name)+'</option>').join('');choice.value=selected||'';load();}
 function load(){const preset=uiCommunity().appearance?.cssPresets?.find(p=>p.id===choice.value);name.value=preset?.name||'';text.value=preset?.css||'';}choice.onchange=load;
 dialog.querySelector('[data-css-file]').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>240000)throw Error('CSS文件过大');text.value=(await file.text()).replace(/^\uFEFF/,'');choice.value='__new__';name.value=file.name.replace(/\.(css|txt)$/i,'').slice(0,40);}catch(err){appearanceError(dialog,err);}finally{e.target.value='';}};
 dialog.querySelector('[data-css-save]').onclick=async e=>{e.currentTarget.disabled=true;try{check();bridge.scopedChatCss(text.value);const id=choice.value&&choice.value!=='__new__'?choice.value:'style-'+bridge.newId();await bridge.saveChatCss({id,name:name.value,css:text.value},thread.id);list(id);toast('外观已保存并应用');}catch(err){appearanceError(dialog,err);}finally{e.currentTarget.disabled=false;}};
 dialog.querySelector('[data-css-apply]').onclick=async()=>{try{check();if(choice.value==='__new__')throw Error('请先保存这套预设');await bridge.saveAppearance('thread',{cssPresetId:choice.value||null},thread.id);toast('外观已应用');}catch(e){appearanceError(dialog,e);}};
 dialog.querySelector('[data-css-reset]').onclick=async()=>{try{check();await bridge.saveAppearance('thread',{cssPresetId:null},thread.id);list('');toast('已恢复默认外观，保存的预设仍可再选');}catch(e){appearanceError(dialog,e);}};list(uiCommunity().chatAppearance?.[thread.id]?.cssPresetId);
}
const createGroupButton=smallButton('创建群聊','＋',()=>{const run=uiCommunity().chatId,dialog=sheet('创建群聊','<label class="jp-form-label">群名称<input data-new-group-name maxlength="32" placeholder="给小群取个名字"></label><p class="jp-sheet-caption">选择至少两位角色，你也会加入群聊。</p><div class="jp-invite-list">'+chatRoles.map(r=>'<label><span class="chat-avatar">'+threadPortrait(r)+'</span><span>'+esc(displayName(r))+'</span><input type="checkbox" value="'+r.id+'"></label>').join('')+'</div><button type="button" class="jp-primary" data-create-group>创建群聊</button>','jp-contact-editor');dialog.querySelector('[data-create-group]').onclick=async e=>{e.currentTarget.disabled=true;try{if(run!==uiCommunity().chatId)throw Error('对话已切换');const ids=[...dialog.querySelectorAll('input[type=checkbox]:checked')].map(x=>x.value);const group=await bridge.createGroup(dialog.querySelector('[data-new-group-name]').value,ids);dialog.remove();renderChatRoom(group);$('#chatListView').hidden=true;$('#chatRoom').hidden=false;$('#chatApp').classList.add('chat-room-open');}catch(err){appearanceError(dialog,err);e.currentTarget.disabled=false;}};});$('#chatApp .app-head').append(createGroupButton);
const listWallpaperButton=smallButton('聊天列表壁纸','▧',()=>openAppearance('list'));$('#chatApp .app-head').append(listWallpaperButton);
const beforeRoomAppearance=roomSettings.onclick;roomSettings.onclick=e=>{beforeRoomAppearance(e);const page=$$('.jp-info-page').at(-1),role=activeRole;if(!page||!role)return;const card=uiDocument.createElement('section');card.className='jp-info-card';card.innerHTML='<button type="button" class="jp-info-row" data-room-wallpaper><span>聊天壁纸</span><em>更换壁纸</em><i>›</i></button><button type="button" class="jp-info-row" data-room-css><span>气泡与界面</span><em>CSS 外观预设</em><i>›</i></button>';page.querySelector('.jp-info-hint').before(card);card.querySelector('[data-room-wallpaper]').onclick=()=>openAppearance('thread',role);card.querySelector('[data-room-css]').onclick=()=>openAppearance('css',role);};
extra.textContent+='.jp-wallpaper-preview{height:120px;background:linear-gradient(150deg,#f0eaf0,#dce9e3);background-size:cover;background-position:center;border-radius:12px;margin:12px 0}.jp-icon-custom-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.jp-contact-editor .jp-icon-custom-grid button{display:flex;flex-direction:column;align-items:center;gap:5px;background:transparent!important;font-size:11px;padding:7px!important;margin:0!important}.jp-icon-custom-grid .icon-box{width:45px;height:45px}.jp-icon-custom-grid .icon-box img{width:100%;height:100%;object-fit:contain}.jp-invite-list{max-height:320px;overflow:auto}.jp-invite-list label{display:flex;align-items:center;gap:10px;padding:8px 0}.jp-invite-list .chat-avatar{width:34px;height:34px;border-radius:50%;overflow:hidden}.jp-invite-list label>span:nth-child(2){flex:1;min-width:0;overflow-wrap:anywhere}.jp-invite-list input{accent-color:#9b7f95}.jp-css-settings .jp-css-editor{height:230px!important;white-space:pre;font:12px monospace;line-height:1.6}.jp-css-settings .jp-primary,.jp-css-settings .jp-text-action{display:block;width:100%;box-sizing:border-box;margin:12px 0 0}#home .apps .icon-box img.jp-custom-app-icon{transform:none!important;image-rendering:auto!important;width:100%!important;height:100%!important;object-fit:contain!important}';updateAppearance();
