import test from 'node:test';import assert from 'node:assert/strict';
import {checkpoint,rollback,reconcileRounds,pendingThreads,parseBatch,withoutRound,assertRerollable,compactActions,actionMemory} from './round-sync.js';
import {world} from './core.js';import {removeMessage,recallMessage,visibleMessages} from './phone-records.js';
const roles=[{id:'06',name:'西拉斯'},{id:'11',name:'莱恩'},{id:'10',name:'莱尔'}];
const base={gold:500,inventory:[],plots:[],capacity:24,quests:[]};
test('reroll restores all progress before changed floor but preserves settings and profile',()=>{const s={base,turns:[],manual:[],unread:{},feedProfile:{id:'自己'},avatars:{'06':'avatar'}};const before=checkpoint(s);s.turns.push({signature:'old',before,state:{...base,gold:600},socialRevision:0,messages:[{text:'old'}]});s.manual.push({text:'after floor'});s.posts=[{text:'after'}];s.socialEvents=[{id:'claim',revision:1,gold:20,items:[]}];assert.equal(reconcileRounds(s,['new']),0);assert.equal(world(s).gold,500);assert.deepEqual(s.manual,[]);assert.equal(s.posts,undefined);assert.equal(s.feedProfile.id,'自己');assert.equal(s.avatars['06'],'avatar');});
test('same footer/signature can still be explicitly regenerated and reread',()=>{const s={turns:[{signature:'same',state:base,before:checkpoint({})}],manual:[]};assert(rollback(s,0));assert.equal(s.turns.length,0);});
test('unchanged floor retains generated phone content and paid transactions',()=>{const s={turns:[{signature:'a'}],manual:[{text:'keep'}],socialEvents:[{gold:20}]};assert.equal(reconcileRounds(s,['a','b']),1);assert.equal(s.manual.length,1);assert.equal(s.socialEvents.length,1);});
test('all pending private and group threads are selected once, sent bubbles excluded',()=>{const s={manual:[{id:'a',roleId:'06',from:'me',status:'queued'},{id:'b',roleId:'11',from:'me',status:'failed'},{id:'c',roleId:'group-all',from:'me',status:'queued'},{id:'d',roleId:'10',from:'me',status:'sent'}]};assert.equal(pendingThreads(s,roles).length,3);assert.equal(pendingThreads(s,roles,['d']).length,1);});
test('batch validates all replies before acceptance including group membership',()=>{const threads=[{role:roles[0]},{role:{id:'group-twins',members:['11','10']}}];const good={replies:[{threadId:'06',bubbles:['博物馆见']},{threadId:'group-twins',messages:[{roleId:'11',text:'明天见'}]}]};assert.equal(parseBatch(JSON.stringify(good),threads,roles).length,2);assert.throws(()=>parseBatch(JSON.stringify({replies:[good.replies[0]]}),threads,roles));good.replies[1].messages[0].roleId='06';assert.throws(()=>parseBatch(JSON.stringify(good),threads,roles));});
test('duplicate thread replies and unrequested threads are rejected',()=>{const t=[{role:roles[0]},{role:roles[1]}];assert.throws(()=>parseBatch(JSON.stringify({replies:[{threadId:'06',bubbles:['a']},{threadId:'06',bubbles:['b']}]}),t,roles));});
test('reroll memory excludes prior output but retains user inputs and unrelated history',()=>{const s={manual:[{id:'u'},{id:'r',batchId:'batch'},{id:'old',batchId:'earlier'}],letters:[{batchId:'batch'}]};const m=withoutRound(s,{id:'batch'});assert.deepEqual(m.manual.map(m=>m.id),['u','old']);assert.equal(m.letters.length,0);assert.equal(s.manual.length,3);});
test('reroll cannot erase a redeemed transfer, accepted quest or narrated round',()=>{const round={id:'x',floor:1};assert.throws(()=>assertRerollable({turns:[{}],manual:[{batchId:'x',claimed:true}]},round));assert.throws(()=>assertRerollable({turns:[{}],letters:[{id:'l',batchId:'x'}],mailQuests:[{id:'l'}]},round));assert.throws(()=>assertRerollable({turns:[{},{}]},round));assert.doesNotThrow(()=>assertRerollable({turns:[{}]},round));});
test('farm actions are compact ranges while quantities and settlement remain clear',()=>{const actions=['在第1格农田播种草莓','在第2格农田播种草莓','在第3格农田播种草莓','在第5格农田播种草莓','【手机已结算，请勿重复扣增】领取20金币'];assert.deepEqual(compactActions(actions),['在第1-3,5格农田播种草莓','【手机已结算，请勿重复扣增】领取20金币']);const text=actionMemory({draft:{actions,plots:[{crop:'草莓'},{crop:'草莓'}]}},{plots:[]});assert(text.includes('1-2'));assert(text.includes('禁止重复扣增'));assert(text.includes('待演绎计划'));});
test('rollback preserves already accounted prior transactions exactly once',()=>{const s={base,manual:[],socialEvents:[{id:'prior',revision:1,gold:20,items:[]}],turns:[]};s.turns.push({signature:'a',before:checkpoint(s),socialRevision:1,state:{...base,gold:520}});s.socialEvents.push({id:'later',revision:2,gold:30,items:[]});rollback(s,0);assert.equal(world(s).gold,520);});

test('farm action compaction preserves operation order and repeated actions',()=>{const a=['在第1格播种','收获第1格','在第1格播种'];assert.deepEqual(compactActions(a),a);});
test('deleted and recalled messages cannot reappear through floor checkpoints',()=>{const s={manual:[{id:'secret',from:'me',roleId:'06',text:'secret',status:'queued'}],turns:[]};s.turns=[{before:checkpoint(s)}];recallMessage(s,'secret',()=>.99);rollback(s,0);assert(!visibleMessages(s)[0].text.includes('secret'));s.turns=[{before:checkpoint(s)}];removeMessage(s,'secret');rollback(s,0);assert.equal(visibleMessages(s).length,0);});
