import test from 'node:test';import assert from 'node:assert/strict';
import {readStateBlock} from './protocol.js';import {storyKey,storyText,farmMismatch,reviewedFarmState,formatFarmReview,networkFailure} from './story-sync.js';import {actionMemory} from './round-sync.js';
const empty=()=>({crop:'',days:null,wet:false,fertilizer:'',stage:'empty'});
const base={gold:500,capacity:24,calendar:{season:'春季',day:1,year:1,time:'06:00',weather:'晴'},inventory:[{name:'防风草种子',count:15,kind:'seed',price:0,days:4}],plots:Array.from({length:24},empty),relationships:{},locations:{},quests:[],animals:[],buildings:[],calendarEvents:[],notes:''};
const wrap=x=>'【手机状态】\n'+x+'\n【状态结束】';
test('mobile screenshot task format can omit progress without shifting reward/deadline',()=>{const p=readStateBlock(wrap('任务：春日劳动|进行中|保持巡查至12:00\n（约135/330分钟）|600金币+精品种子包|今天|巡查任务\n任务：酒馆之夜|可接取|前往酒馆并保持至午夜|1000金币+好感+10|今晚18:00前接取|聚会任务'),base);assert.equal(p.state.quests.length,2);assert.equal(p.state.quests[0].goal,'保持巡查至12:00（约135/330分钟）');assert.equal(p.state.quests[0].reward,'600金币+精品种子包');assert.equal(p.state.quests[1].deadline,'今晚18:00前接取');assert.equal(p.warnings.length,0);});
test('numeric, unknown and fractional progress remain compatible',()=>{const p=readStateBlock(wrap('任务：甲|进行中|50|种地|100金币|今天|详情\n任务：乙|进行中|未知|浇水|20金币|今天|详情\n任务：丙|进行中|135/330分钟|巡查|50金币|今天|详情'),base);assert.equal(p.state.quests[0].progress,50);assert.equal(p.state.quests[1].goal,'浇水');assert.equal(Math.round(p.state.quests[2].progress),41);});
test('BaiBai image tag insertion, replacement, delivery and ordinary image nodes keep story key',()=>{const m={name:'角色',mes:'第一段\n第二段\n'+wrap('金币：500')};const key=storyKey(m);for(const mes of [m.mes.replace('第一段','第一段\n<bbi_image><tag>new prompt</tag></bbi_image>'),m.mes+'\n<bbi_image>newer prompt</bbi_image>',m.mes+'\n<img src="/user/images/result.png">',m.mes+'\n![生成图片](/image.png)'])assert.equal(storyKey({...m,mes,extra:{bbiImage:{path:'new'}}}),key);});
test('real story edits, variable edits and actual swipe still change key',()=>{const m={mes:'story\n'+wrap('金币：500')};assert.notEqual(storyKey(m),storyKey({...m,mes:m.mes.replace('500','550')}));assert.notEqual(storyKey(m),storyKey({...m,mes:'different '+m.mes}));assert.notEqual(storyKey(m),storyKey({...m,swipe_id:1}));assert.equal(storyKey(m),storyKey({...m,swipe_id:0}));});
test('orphan BaiBai tags do not swallow intervening story text',()=>{assert.equal(storyText('甲<bbi_image>乙\n<bbi_image>prompt</bbi_image>丙'),'甲乙\n丙');});
test('phone plan sends only changed cells, not every empty cell because stage is absent',()=>{const plots=base.plots.map(({stage,...p})=>p);plots[0]={crop:'防风草',days:4,wet:false,fertilizer:''};const text=actionMemory({draft:{actions:['在第1格农田播种防风草'],plots}},base);assert(text.includes('"plots":"1"'));assert(!text.includes('"plots":"2-24"'));});
test('plant five but story plants ten raises conflict and preserves a correct review candidate',()=>{const plots=base.plots.map((p,i)=>i<5?{crop:'防风草',days:4,wet:false,fertilizer:''}:p),draft={actions:Array.from({length:5},(_,i)=>'在第'+(i+1)+'格农田播种防风草'),plots};const after=structuredClone(base);after.plots=after.plots.map((p,i)=>i<10?{crop:'防风草',days:4,wet:false,fertilizer:'',stage:'seeded'}:p);after.inventory[0].count=5;assert.deepEqual(farmMismatch(draft,base,after),[6,7,8,9,10]);const candidate=reviewedFarmState(draft,base,after);assert.equal(candidate.plots.filter(p=>p.crop).length,5);assert.equal(candidate.inventory[0].count,10);assert.equal(after.inventory[0].count,5);const applied=readStateBlock(formatFarmReview(candidate,after),after).state;assert.equal(applied.plots.filter(p=>p.crop).length,5);assert.equal(applied.inventory[0].count,10);});
test('growth duration does not falsely conflict with the same chosen farm cells',()=>{const before=structuredClone(base);before.plots[0]={crop:'防风草',days:4,wet:false,fertilizer:'',stage:'seeded'};const draft={actions:['给第1格农田浇水'],plots:structuredClone(before.plots)};draft.plots[0].wet=true;const after=structuredClone(before);after.plots[0]={...draft.plots[0],days:3,stage:'growing'};assert.deepEqual(farmMismatch(draft,before,after),[]);});
test('mobile abort reported as TypeError is not mislabeled CORS',()=>{assert.equal(networkFailure(new TypeError('Load failed'),{aborted:true}).name,'AbortError');assert(networkFailure(new TypeError('Load failed'),{lastSuccess:true,chars:10000,elapsed:30000}).message.includes('不能据此认定是 CORS'));assert(networkFailure(new DOMException('aborted','AbortError'),{timedOut:true,elapsed:180000}).message.includes('180 秒'));});

test('unresolved farm conflict is not submitted as a fresh planting command',()=>{const text=actionMemory({draft:{actions:['在第1格农田播种防风草'],plots:base.plots,conflicts:[1]}},base);assert(text.includes('不是本轮新操作'));assert(!text.includes('应在本轮执行'));});
