import test from 'node:test';import assert from 'node:assert/strict';
import {narrativeLetters} from './narrative-mail.js';import {recallMessage,quotedMessage} from './phone-records.js';import {phoneTimeline} from './phone-memory.js';import {narrativeMemory,appendTransaction,applySocialEvents} from './social.js';import {commentsFor,newComment,parseComments,deleteComment} from './feed-comments.js';import {publicMemory,parsePosts} from './community.js';import {discoverItems,validateOfferings,offeringProgress,offeringSubmission} from './collection.js';
const roles=[{id:'06',name:'西拉斯',job:'博物馆馆长'},{id:'11',name:'莱恩',job:'服装店'}];
test('structured narrative letter retains full body and a deterministic source ID',()=>{const text='【手机来信】\n发信人：西拉斯\n标题：邀请\n正文：第一段\n第二段\n【来信结束】';const a=narrativeLetters(text,roles,'turn1');assert.equal(a[0].senderId,'06');assert.equal(a[0].body,'第一段\n第二段');assert.equal(a[0].id,narrativeLetters(text,roles,'turn1')[0].id);assert.notEqual(a[0].id,narrativeLetters(text,roles,'turn2')[0].id);});
test('legacy received letters sync as honest excerpts without inventing body',()=>{const a=narrativeLetters('林娇收到西拉斯寄来的一封信。\n纸上写着展览邀请。',roles,'1','林娇');assert.equal(a.length,1);assert.equal(a[0].senderId,'06');assert(a[0].excerpt);assert(a[0].body.includes('未提供的完整信文不会自动补写'));});
test('plans and hypothetical letters do not become received letters',()=>{for(const p of ['如果你收到一封信，请告诉我。','你明天可能收到一封信。','你没有收到一封信。','西拉斯打算寄信给你。'])assert.equal(narrativeLetters(p,roles,'1').length,0,p);});
function store(){return {manual:[{id:'m',roleId:'06',from:'me',text:'SECRET',type:'image',mediaId:'image',status:'queued',created:1},{id:'q',roleId:'06',from:'role',text:'回复',quoteId:'m',created:2}],turns:[]};}
test('unseen recall strips original content, media and quotes from all model memory',()=>{const s=store();recallMessage(s,'m',()=>.9);assert(!JSON.stringify(phoneTimeline(s,roles[0],roles)).includes('SECRET'));assert(!narrativeMemory(s,roles).includes('SECRET'));assert.equal(s.manual[0].mediaId,undefined);assert.equal(quotedMessage(s,s.manual[1]),undefined);assert(s.manual[0].text.includes('没来得及'));assert.throws(()=>recallMessage(s,'m'));});
test('seen recall retains event and content, already answered messages stay seen',()=>{const s=store();s.manual[0].status='sent';recallMessage(s,'m',()=>.99);assert(s.manual[0].recalled.seen);assert(narrativeMemory(s,roles).includes('SECRET'));assert.equal(s.manual[0].status,'queued');});
test('user can comment on both authors; AI reply targets must belong to same post',()=>{const s={posts:[{id:'p',authorId:'me',text:'自拍'},{id:'r',authorId:'06',text:'展览'}],turns:[],comments:[newComment('p','me','自己的评论')]};const parent=s.comments[0];const parsed=parseComments(JSON.stringify({comments:[{postId:'p',authorId:'06',text:'不错',replyTo:parent.id}]}),s.posts,roles,s.comments);s.comments.push(...parsed);assert.equal(commentsFor(s,'p').length,2);assert(publicMemory(s,roles).includes('不错'));assert.throws(()=>parseComments(JSON.stringify({comments:[{postId:'r',authorId:'06',text:'串线',replyTo:parent.id}]}),s.posts,roles,s.comments));deleteComment(s,parent.id);assert(!publicMemory(s,roles).includes('自己的评论'));});
test('AI cannot impersonate user or add comments to missing posts',()=>{assert.throws(()=>parseComments('{"comments":[{"postId":"p","authorId":"me","text":"x"}]}',[{id:'p'}],roles));assert.throws(()=>parseComments('{"comments":[{"postId":"missing","authorId":"06","text":"x"}]}',[{id:'p'}],roles));});
test('museum curator cannot publish a clothing-shop self promotion',()=>{assert.throws(()=>parsePosts(JSON.stringify({posts:[{roleId:'06',text:'展现魅力的衣服都在我的店里哦！随时欢迎新朋友来试穿。'}]}),roles));assert.equal(parsePosts(JSON.stringify({posts:[{roleId:'06',text:'今天整理了馆藏中的古代服装。'}]}),roles).length,1);});
const state=()=>({inventory:[{name:'木材',kind:'item',count:5,price:2}],gold:100,capacity:24});
test('discovery survives spending inventory and starts independently in a new chat',()=>{const s={turns:[]};assert(discoverItems(s,state()));assert.equal(s.catalog.木材.category,'矿石与材料');assert(!discoverItems(s,{inventory:[]}));assert.equal(Object.keys(s.catalog).length,1);const fresh={turns:[]};discoverItems(fresh,{inventory:[]});assert.equal(Object.keys(fresh.catalog).length,0);});
test('empty offerings have no invented requirements, input validates strictly',()=>{assert.deepEqual(validateOfferings([]),[]);assert.throws(()=>validateOfferings([{id:'a',section:'鱼缸',bundle:'鱼',item:'鲤鱼',count:-1}]));});
test('offering debits inventory once, records partial progress, refuses over-submission',()=>{const s={offerings:[],socialEvents:[]},row={id:'a',section:'工艺室',bundle:'木材包',item:'木材',count:3},initial=state();const sub=offeringSubmission(s,initial,row,2);appendTransaction(s,initial,{id:sub.id,...sub.transaction});s.offerings.push(sub);assert.equal(offeringProgress(s,row),2);const next=applySocialEvents(initial,s.socialEvents);assert.equal(next.inventory[0].count,3);assert.throws(()=>offeringSubmission(s,next,row,2));assert.throws(()=>offeringSubmission(s,next,row,0));assert.equal(appendTransaction(s,next,{id:sub.id,...sub.transaction}),false);});
test('undiscovered offering requirements remain available; no phantom inventory submission',()=>{const s={offerings:[]},row={id:'f',section:'鱼缸',bundle:'河鱼',item:'鲤鱼',count:1};assert.equal(validateOfferings([row]).length,1);assert.throws(()=>offeringSubmission(s,state(),row,1));});

test('multiple signed letters taken out of a mailbox import separately',()=>{const text='你拉开了邮箱的小门。\n你把那几封信拿了出来。最上面的一封，是用正式信纸书写的：\n“欢迎来到小镇，祝你生活愉快。\n——居民委员会 敬上”\n第二封信显得简短，纸张上有木材香：\n“如果需要修缮，来找我。\n——塞勒斯”';const found=narrativeLetters(text,[...roles,{id:'02',name:'塞勒斯'}],'mailbox');assert.equal(found.length,2);assert.equal(found[0].senderName,'居民委员会');assert.equal(found[1].senderId,'02');assert(found[1].body.includes('修缮'));assert(!found[1].excerpt);});
test('a signed letter quoted in a future plan is not delivered',()=>{assert.equal(narrativeLetters('如果你明天打开邮箱收到一封信，信上可能写着：\n“欢迎你。\n——西拉斯”',roles,'future').length,0);});
