import {recoverQuestHistory} from './quest-state.js';
import {createDevicePreferences,clampBadgePosition} from './floating-position.js';
import {taskBatchInstruction,parseTaskBatch,applyTaskBatch} from './task-batch.js';
import {directActionPrompt} from './action-injection.js';
import {questRows,questCompleted,repairPatch,settleActionDraft} from './round-settlement.js';
import {customGroup,saveCssPreset,scopedChatCss,effectiveCssPresetId} from './customization.js';
import {knowledgeBoundary,publicGroupCards,groupCardMemory,validateMentionIds,selectedMentionIds} from './group-social.js';
import {openAvatarCrop} from './avatar-crop.js';
import {createPluginSwitch,mountExtensionSwitch} from './extension-switch.js';
import {newId} from './browser-compat.js';
import {recoveryCandidates,applyRecoveredMessages} from './message-recovery.js';
import {phoneLayout,phoneTop,deepActiveElement} from './mobile-layout.js';
import {characterBirthdays,calendarWithBirthdays,birthdaysToday,birthdayMemory} from './birthdays.js';
import {chatDisplayName,updateChatNames,shouldMarkChatRead,migrateOutputLimits} from './chat-settings.js';
import {correctionPatch} from './correction.js';
import {historyReference,bootstrapPrompt} from './history-bootstrap.js';
import {craftTransaction,projectTransaction,letterRecipes,letterAttachments} from './progression.js';
import {defaultOfferings,offeringBundles,roomRewards,offeringMemory} from './offering-data.js';
import {syncAnimals,animalAction,animalView,animalPresets,animalMemory} from './animals.js';
import {storyText,storyKey,farmMismatch,reviewedFarmState,formatFarmReview,networkFailure} from './story-sync.js';
import {checkpoint,rollback,reconcileRounds,reconcileForSync,pendingThreads,parseBatch,withoutRound,assertRerollable,actionMemory,watchStateBlocks} from './round-sync.js';
import {narrativeLetters,mailSyncInstruction} from './narrative-mail.js';
import {commentsFor,newComment,parseComments,deleteComment,identityInstruction,identityConflict} from './feed-comments.js';
import {itemCategories,offeringSections,discoverItems,validateOfferings,offeringProgress,offeringSubmission,offeringOwned} from './collection.js';
import {removeMessage,removePost,quotedMessage,recallMessage,editMessage,messageEditGuidance} from './phone-records.js';
import {editablePromptDefinitions,normalizePromptOverrides,renderAppPrompt,mergeUserPrompts,userPromptOverrides,importPromptPreset,exportPromptPreset} from './app-prompts.js';
import {groups} from './phone-memory.js';
import {allPosts,parsePosts,publicMemory,makeUserPost,shouldPost,customMailInstruction,normalizeMailRules,mailRule,mailPreferences,feedRates} from './community.js';
import {parseResponseJSON,decodeCompletion} from './json-response.js';
import {socialRevision,applySocialEvents,appendTransaction,eligibleItems,parseSocial,socialInstruction,allLetters,narrativeMemory} from './social.js';
import {loadStickers,stickerCatalog,getSticker,saveSticker,prepareSticker,stickerPrompt,withStickerImages,getImage,saveImage,validateImageSource,imageInstruction} from './stickers.js';
import {allPhoneMessages,phoneTimeline,followupInstruction} from './phone-memory.js';
import {formatState} from './text-state.js';
import {chatInstruction,parseChatReply,parseFollowups,textingStyle} from './chat-protocol.js';
import {readStateBlock,statePrompt,promptBaseline,parseBubbles} from './protocol.js';
import {mountPhone} from './phone.js';
import {readBoundLore,resolveBinding,selectLore} from './lore.js';
import {clone,applyPatch,validatePatch,parseResult,fingerprint,reconcile,world,endpoint,migrateDemo} from './core.js';
const KEY='junimo_pocket_v1';
function prompt(id,values={}){const text=renderAppPrompt(id,config().appPrompts||{},values);if(id==='style')return prompt('messageRules')+'\n'+text;if(id==='social')return prompt('mailStyle')+'\n'+text;if(id==='feed'||id==='comments')return prompt('feedStyle')+'\n'+text;return text;}
function promptStickers(){return prompt('stickers',{stickers:JSON.stringify(stickerCatalog())});}
function promptSocial(state,letterLimit=2){return prompt('recipes')+'\n'+prompt('social',{letterLimit,items:JSON.stringify(eligibleItems(state)),cap:Math.min(500,Math.max(100,Math.floor(state.gold/2)))});}
function promptIdentity(){return prompt('identity',{roles:JSON.stringify(ui.roles.map(({id,name,job})=>({id,name,job})))});}
function promptCategories(){const prefs=mailPreferences(config().mailPreferences),enabled=Object.keys(prefs).filter(k=>prefs[k]);const chosen=enabled.length&&Math.random()<.3?enabled[Math.floor(Math.random()*enabled.length)]:null;return prompt('categories',{disabled:Object.keys(prefs).filter(k=>!prefs[k]).join('、')||'无',category:chosen?'允许偶尔附带一封'+chosen+'，不强制；其他特殊类别不要生成':'只生成regular普通来信'});}

function publicPostsData(s,limit=20){return allPosts(s).slice(0,limit).map(p=>({...p,comments:commentsFor(s,p.id)}));}
function communityData(){try{const s=store();return {customGroups:s.customGroups||[],appearance:config().appearance||{},chatAppearance:s.chatAppearance||{},chatId:currentId(),posts:allPosts(s).map(p=>({...p,comments:commentsFor(s,p.id)})),commentFrequency:config().commentFrequency||'normal',avatars:s.avatars||{},chatNames:s.chatNames||{},profile:s.feedProfile||{},promptDefinitions:editablePromptDefinitions,appPrompts:userPromptOverrides(config().appPrompts),presetName:config().presetName||'我的手机预设',mailCustomRules:config().mailCustomRules||'',mailPreferences:mailPreferences(config().mailPreferences),feedFrequency:config().feedFrequency||'normal',userName:context().name1};}catch{return {appearance:config().appearance||{},customGroups:[],chatAppearance:{},posts:[],avatars:{},promptDefinitions:editablePromptDefinitions,appPrompts:userPromptOverrides(config().appPrompts),presetName:config().presetName||'我的手机预设',mailCustomRules:config().mailCustomRules||'',mailPreferences:mailPreferences(config().mailPreferences),feedFrequency:config().feedFrequency||'normal',userName:'我'};}}
async function publishPost(text,description){const s=store();(s.posts??=[]).push({...makeUserPost(text,description),...stamp(s)});await persist();render();await standaloneComments(s);}
async function saveCommunitySettings(value){if(value.presetName!==undefined&&(typeof value.presetName!=='string'||value.presetName.trim().length>80))throw Error('预设名称最多80字');const prompts=value.appPrompts===undefined?undefined:normalizePromptOverrides(value.appPrompts),rules=value.mailCustomRules===undefined?undefined:normalizeMailRules(value.mailCustomRules);if(value.commentFrequency!==undefined&&!(value.commentFrequency in feedRates))throw Error('评论频率无效');if(value.commentFrequency!==undefined)config().commentFrequency=value.commentFrequency;if(value.feedFrequency!==undefined&&!(value.feedFrequency in feedRates))throw Error('动态频率无效');if(value.presetName!==undefined)config().presetName=value.presetName.trim()||'我的手机预设';if(prompts)config().appPrompts=mergeUserPrompts(config().appPrompts,prompts,{replace:!!value.replacePrompts});if(value.feedFrequency!==undefined)config().feedFrequency=value.feedFrequency;if(rules!==undefined)config().mailCustomRules=rules;if(value.mailPreferences)config().mailPreferences=mailPreferences(value.mailPreferences);context().saveSettingsDebounced();installStatePrompt();render();}
async function saveAvatar(threadId,who,source){const s=store(),run=epoch;const group=groups(ui.roles,store().customGroups||[]).find(g=>g.id===threadId);if(!(group||ui.roles.some(r=>r.id===threadId))||!(['me','role'].includes(who)||(who==='group'&&group)||group?.members.includes(who)))throw Error('头像所属聊天无效');let id=null;if(source){const media=await saveImage({dataUrl:source,description:'聊天头像'});id=media.id;}if(run!==epoch||s!==store())throw Error('对话已切换，请重新设置头像');((s.avatars??={})[threadId]??={})[who]=id;await persist();render();}
async function createGroup(name,members){requireSocialIdle();const s=store();const group=customGroup('group-custom-'+newId(),name,members,ui.roles,s.customGroups||[]);(s.customGroups??=[]).push(group);await persist();render();return group;}
async function saveAppearance(scope,value,threadId){requireActive();const run=epoch,s=scope==='thread'?store():null;const next={...value};if(value.wallpaper!==undefined)next.wallpaper=value.wallpaper?(await saveImage({dataUrl:validateImageSource(value.wallpaper),description:'自定义壁纸'})).id:null;if(value.icon!==undefined)next.icon=value.icon?(await saveImage({dataUrl:validateImageSource(value.icon),description:'自定义APP图标'})).id:null;if(run!==epoch)throw Error('对话已切换，请重新设置外观');const appearance=config().appearance??={};if(scope==='thread'){if(![...ui.roles,...groups(ui.roles,s.customGroups||[])].some(r=>r.id===threadId))throw Error('聊天不存在');s.chatAppearance??={};s.chatAppearance[threadId]={...s.chatAppearance[threadId],...next};await persist();}else if(scope==='home'){appearance.homeWallpaper=next.wallpaper;context().saveSettingsDebounced();}else if(scope==='list'){appearance.listWallpaper=next.wallpaper;context().saveSettingsDebounced();}else if(scope==='chatCss'){appearance.defaultCssPresetId=next.cssPresetId||null;context().saveSettingsDebounced();}else if(scope==='icon'){if(typeof value.appId!=='string'||value.appId.length>50)throw Error('图标无效');(appearance.icons??={})[value.appId]=next.icon;context().saveSettingsDebounced();}else throw Error('外观设置范围无效');ui.updateAppearance?.();render();}
async function saveChatCss(value,threadId){requireActive();if(threadId){const s=store();if(![...ui.roles,...groups(ui.roles,s.customGroups||[])].some(r=>r.id===threadId))throw Error('聊天不存在');}const appearance=config().appearance??={};appearance.cssPresets=saveCssPreset(appearance.cssPresets,value);context().saveSettingsDebounced();await saveAppearance(threadId?'thread':'chatCss',{cssPresetId:value.id},threadId);}
async function saveChatNames(threadId,value){const s=store(),thread=groups(ui.roles,store().customGroups||[]).find(r=>r.id===threadId)||ui.roles.find(r=>r.id===threadId);s.chatNames=updateChatNames(s.chatNames,thread,value,ui.roles);await persist();render();}
async function saveFeedProfile(value){const s=store(),run=epoch;const next={...s.feedProfile};if(value.id!==undefined){if(typeof value.id!=='string'||value.id.trim().length>32||!value.id.trim())throw Error('朋友圈 ID 请填写1到32字');next.id=value.id.trim();}for(const key of ['avatar','cover'])if(value[key]!==undefined)next[key]=value[key]?(await saveImage({dataUrl:validateImageSource(value[key]),description:'朋友圈'+key})).id:null;if(run!==epoch||s!==store())throw Error('对话已切换，请重新设置');s.feedProfile=next;await persist();render();}
async function generatePostsOnly(s,turn,signal,run,role){
 if(!sessionKey||!config().url||!shouldPost(config().feedFrequency||'normal'))return;
 try{const candidates=role?(role.members||[role.id]):ui.roles.map(r=>r.id),allowed=role?candidates:[candidates[Math.floor(Math.random()*candidates.length)]],narrative=recentNarrative(),background=await roleContext(ui.roles.filter(r=>allowed.includes(r.id)).map(r=>r.name).join('、'),narrative,signal);
 const raw=await completion([{role:'system',content:prompt('feed')+'\n'+promptIdentity()}, {role:'user',content:JSON.stringify({allowed,roles:ui.roles,background,narrative,publicPosts:publicPostsData(s,15),trigger:role?'刚结束与用户的聊天':'正文推进',privateContext:role?phoneTimeline(s,role,ui.roles,20):[]})}],signal,config().maxTokens);
 if(run!==epoch||s!==store())return;const posts=parsePosts(raw,ui.roles,allowed).map(p=>({...p,...stamp(s)}));if(turn)turn.posts=posts;else(s.posts??=[]).push(...posts);if(posts.length){render();await persist();ui.notify('朋友圈有 '+posts.length+' 条新动态');}
 }catch(e){if(e.name!=='AbortError')status('动态暂未生成：'+e.message);}
}

function syncTurnMail(s,turn,m){if(!m||m.is_user||m.is_system||turn.mailSyncVersion===1)return;const letters=narrativeLetters(extractNarrative(m.mes||''),ui.roles,turn.signature,context().name1),existing=allLetters(s);const added=letters.filter(l=>!existing.some(x=>x.id===l.id||(x.subject===l.subject&&x.body===l.body)));(turn.letters??=[]).push(...added.map(l=>({...l,time:turn.state?.calendar?.time||''})));turn.mailSyncVersion=1;if(added.length)ui.notify('正文中的 '+added.length+' 封来信已放进信箱');}
async function generatePosts(s,turn,signal,run,role){await generatePostsOnly(s,turn,signal,run,role);if(run===epoch)await generateComments(s,turn,signal,run);}
async function generateComments(s,turn,signal,run){const posts=allPosts(s).slice(0,12);if(!posts.length||!sessionKey||!config().url||!shouldPost(config().commentFrequency||'normal'))return;try{const picked=ui.roles[Math.floor(Math.random()*ui.roles.length)],background=await roleContext(picked.name,recentNarrative(),signal);const existing=posts.flatMap(p=>commentsFor(s,p.id));const raw=await completion([{role:'system',content:prompt('comments')+'\n'+promptIdentity()},{role:'user',content:JSON.stringify({roles:ui.roles,preferredAuthor:picked.id,background,narrative:recentNarrative(),posts:posts.map(p=>({...p,comments:commentsFor(s,p.id)}))})}],signal,config().maxTokens);if(run!==epoch||s!==store())return;const comments=parseComments(raw,posts,ui.roles,existing,{tolerant:true}).filter(c=>!identityConflict(c.authorId,c.text,ui.roles)&&!existing.some(x=>x.postId===c.postId&&x.authorId===c.authorId&&x.text===c.text)).map(c=>({...c,...stamp(s)}));((turn||s).comments??=[]).push(...comments);if(comments.length){render();await persist();ui.notify('朋友圈有 '+comments.length+' 条新评论');}}catch(e){if(e.name!=='AbortError')status('评论暂未生成：'+e.message);}}
async function standaloneComments(s){if(!currentId()||s!==store()||working||generation)return;working=true;const run=epoch;controller=new AbortController();try{await generateComments(s,null,controller.signal,run);}finally{working=false;controller=null;if(pending){pending=false;schedule();}}}
async function publishComment(postId,text,replyTo){const s=store();if(!allPosts(s).some(p=>p.id===postId))throw Error('这条动态已被删除');if(replyTo&&!commentsFor(s,postId).some(c=>c.id===replyTo))throw Error('被回复的评论已删除');(s.comments??=[]).push({...newComment(postId,'me',text,replyTo),...stamp(s)});render();await persist();await standaloneComments(s);}
async function deleteFeedComment(id){const s=store();deleteComment(s,id);invalidate();render();await persist();}
function collectionData(){try{const s=store(),state=world(s),requirements=validateOfferings(config().offeringRequirements??defaultOfferings);return {categories:itemCategories,sections:offeringSections.filter(c=>requirements.some(r=>r.section===c)),items:Object.values(s.catalog||{}),gold:state.gold,bundles:offeringBundles,roomRewards,rewards:s.offeringRewards||[],inventory:state.inventory,requirements:requirements.map(r=>({...r,submitted:offeringProgress(s,r),owned:offeringOwned(state,r)}))};}catch{return {categories:itemCategories,sections:offeringSections,items:[],inventory:[],requirements:[]};}}
async function craftItem(name,quantity){requireSocialIdle();const s=store(),tx=craftTransaction(world(s),name,quantity);appendTransaction(s,world(s),{id:'craft-'+newId(),...tx});render();await persist();}
async function startProject(name){requireSocialIdle();const s=store(),state=world(s),tx=projectTransaction(state,name);appendTransaction(s,state,{id:'project-'+newId(),...tx});const next=world(s);next.farmProjects=next.farmProjects.map(r=>r.name===name?{...r,status:'建设中',started:{...state.calendar}}:r);if(s.turns.length){s.turns.at(-1).state=next;s.turns.at(-1).socialRevision=socialRevision(s);}else{s.base=next;s.baseSocialRevision=socialRevision(s);}render();await persist();}
async function claimOfferingRewards(name){requireSocialIdle();const original=store(),s=clone(original),b=offeringBundles.find(b=>b.name===name);if(!b)throw Error('没有配置这个收集包的奖励');if(s.offeringRewards?.includes(name))throw Error('奖励已经领取');const rows=validateOfferings(config().offeringRequirements??defaultOfferings);if(!b.items.every(x=>rows.some(r=>r.bundle===name&&r.item===x.name&&r.count>=x.n&&offeringProgress(s,r)>=x.n)))throw Error('原定献祭物品还没有收齐');const items=b.reward.map(x=>({name:x.name,count:x.n,kind:x.name.endsWith('种子')?'seed':'item',price:0,priceUnknown:true,days:0}));appendTransaction(s,world(s),{id:'bundle-reward-'+name,items,description:'献祭包 '+name+' 已完成，奖励已领取。'+b.unlock});(s.offeringRewards??=[]).push(name);const section=offeringBundles.filter(x=>x.group===b.group);if(section.every(x=>s.offeringRewards.includes(x.name))){const reward=roomRewards[b.group];if(reward)appendTransaction(s,world(s),{id:'room-reward-'+b.group,items:b.group==='公共基金'?[{name:'社区捐助徽章',count:1,kind:'item',price:0,priceUnknown:true}]:[],description:'献祭分类完成：'+b.group+'。'+reward});}if(offeringBundles.every(x=>s.offeringRewards.includes(x.name)))appendTransaction(s,world(s),{id:'main-offerings-complete',items:[{name:'月亮之心徽章',count:1,kind:'item',price:0,priceUnknown:true}],description:'两类献祭均完成，主线重燃月亮谷完成。开放月之厅与月灵节，每日两次传送，本地商店九折；星井每日可用3星屑砂换5当季种子。'});original.socialEvents=s.socialEvents;original.offeringRewards=s.offeringRewards;render();await persist();}
async function saveItemCategory(name,category){const s=store();if(!s.catalog?.[name]||!itemCategories.includes(category))throw Error('物品分类无效');s.catalog[name].category=category;await persist();render();}
async function saveOfferings(rows){config().offeringRequirements=validateOfferings(rows);context().saveSettingsDebounced();render();}
async function submitOffering(id,count){requireSocialIdle();const s=store(),state=world(s),row=validateOfferings(config().offeringRequirements??defaultOfferings).find(r=>r.id===id),submission=offeringSubmission(s,state,row,count);appendTransaction(s,state,{id:'offering-'+submission.id,...submission.transaction});(s.offerings??=[]).push({id:submission.id,requirementId:submission.requirementId,item:submission.item,count:submission.count,created:submission.created});addSocialAction(s,submission.transaction.description);render();await persist();}

const context=()=>globalThis.SillyTavern.getContext();
const defaults={pluginEnabled:true,enabled:true,proactive:true,stickerVision:false,allowHttp:false,url:'',model:'',maxChars:12000,history:16,maxTokens:6000,mailTokens:8000,repairTokens:12000,feedFrequency:'normal',commentFrequency:'normal',mailPreferences:{},loreChars:18000,boundAvatar:'',requestTimeout:180,left:null,top:70};
let ui,host,panel,badge,statusLine,settingsPanel,settingsTarget,sessionKey='',generation=false,epoch=0,controller=null,working=false,pending=false,timer,booted=false,phoneOpen=false,storeRef,lastStoryKeys=[],lastApiSuccess=false,lastApiInfo=null,reducedRequest=false;
const config=()=>context().extensionSettings[KEY]??(context().extensionSettings[KEY]=clone(defaults));
let stateWatcher;const apiRequests=new Set();
const masterSwitch=createPluginSwitch({settings:config,save:()=>context().saveSettingsDebounced(),stop(){clearTimeout(timer);invalidate();pending=false;for(const request of apiRequests)request.abort();stateWatcher?.disconnect();stateWatcher=null;phoneOpen=false;panel.hidden=true;badge.hidden=false;host.hidden=true;host.style.display='none';installStatePrompt();},start(){host.hidden=false;host.style.removeProperty('display');storeRef=context().chatMetadata;lastStoryKeys=context().chat.map(storyKey);ui.closeRoom();ui.home();stateWatcher=watchStateBlocks();clamp();render();installStatePrompt();schedule();}});
const active=masterSwitch.active;
function requireActive(){if(!active())throw new DOMException('月亮谷手机已关闭','AbortError');}
const currentId=()=>String(context().getCurrentChatId?.()??context().chatId??'');
function store(){requireActive();if(!currentId())throw Error('请先打开一段角色对话');const s=context().chatMetadata[KEY]??(context().chatMetadata[KEY]={version:3,base:clone(ui.initial),turns:[],manual:[],unread:{},draft:null});if(s.version<3){s.legacyBackup=clone({base:s.base,turns:s.turns,manual:s.manual});s.version=3;s.base=clone(ui.initial);s.turns=[];s.started=false;s.draft=null;context().saveMetadataDebounced?.();}if(recoverQuestHistory(s))context().saveMetadataDebounced?.();return s;}
function status(text){if(statusLine)statusLine.textContent=text;ui?.setStatus(text);}
function error(e){if(e.name==='AbortError')return;status('未完成：'+e.message);ui?.toast('未完成，请到设置查看详情');}
async function apiFailure(response,key=''){
  let detail='';try{const body=await response.json();detail=body.error?.message||body.message||'';}catch{}
  if(typeof detail!=='string')detail='';if(key)detail=detail.split(key).join('[Key 已隐藏]');
  const hint=response.status===503?'当前服务或模型渠道暂不可用，请切换模型渠道或稍后重试':response.status===401?'Key 无效或已过期':response.status===429?'请求受限或额度不足':'请检查接口地址和模型';
  return Error('API 返回 HTTP '+response.status+'；'+hint+(detail?'。服务商：'+detail.slice(0,350):''));
}
async function persist(){const c=context();await c.saveMetadata();installStatePrompt();}
function threads(s){const all=allPhoneMessages(s);const out={};for(const m of all)(out[m.roleId]??=[]).push(m);return out;}
function render(){if(!active())return;try{const s=store();let state=world(s);if(syncAnimals(s,state)){state=world(s);context().saveMetadataDebounced?.();}if(discoverItems(s,state))context().saveMetadataDebounced?.();ui.update(state,threads(s),s.unread,s.draft);ui.updateSocial?.(allLetters(s),s.mailQuests||[]);ui.updateCommunity?.();ui.updateCollection?.();badge.classList.toggle('unread',Object.values(s.unread).some(Boolean)||allLetters(s).some(l=>!l.read));}catch{ui.update(ui.initial,{},{});ui.updateSocial?.([],[]);ui.updateCommunity?.();}}
function animalData(){try{const s=store();return {herd:s.herd,animals:animalView(s),presets:animalPresets};}catch{return {animals:[],presets:animalPresets};}}
async function careAnimal(action,id,input={}){requireSocialIdle();const s=store(),state=world(s),result=animalAction(s,state,action,id,{...input,id:newId()}),temp={...s,socialEvents:clone(s.socialEvents||[])};if(result.items.length)appendTransaction(temp,state,{id:'animal-'+newId(),items:result.items,description:result.description});s.socialEvents=temp.socialEvents;s.herd=result.herd;render();await persist();}
function saveDraft(draft){if(!active())return;if(!currentId())return;const s=store();s.draft=draft.actions.length?{...s.draft,...draft}:null;context().saveMetadataDebounced?.();installStatePrompt();}
function compose(text){requireActive();const input=document.querySelector('#send_textarea');if(!input)throw Error('找不到酒馆输入框');input.value=(input.value?input.value+'\n':'')+text;input.dispatchEvent(new Event('input',{bubbles:true}));input.focus();}
function extractNarrative(raw){let text=storyText(raw);if(/<(?:html|body|div|p|style|script)\b/i.test(text)){const doc=new DOMParser().parseFromString(text,'text/html');doc.querySelectorAll('script,style,svg').forEach(el=>el.remove());doc.querySelectorAll('p,div,br,tr,li').forEach(el=>el.append('\n'));text=doc.body.textContent||text;}const limit=reducedRequest?Math.min(4000,config().maxChars):config().maxChars;return text.length<=limit?text:text.slice(0,Math.floor(limit*.4))+'\n[中段超出正文长度上限]\n'+text.slice(-Math.floor(limit*.6));}
function recentNarrative(limit=reducedRequest?Math.min(4000,config().maxChars):config().maxChars){return context().chat.filter(m=>!m.is_system).slice(-8).map(m=>(m.is_user?'用户':'正文')+'：'+storyText(m.mes)).join('\n').slice(-limit);}
async function roleContext(roleName='',narrative='',signal){const c=context(),cfg=config(),run=epoch;const book=await readBoundLore(c,cfg.boundAvatar,signal);if(run!==epoch)throw new DOMException('对话已变化','AbortError');if(!cfg.boundAvatar){cfg.boundAvatar=book.avatar;c.saveSettingsDebounced();}const result=selectLore(book.entries,{roleName,narrative,roles:ui.roles,budget:reducedRequest?Math.min(6000,cfg.loreChars):cfg.loreChars,user:c.name1,character:c.name2});if(!result.selected.length)throw Error('绑定世界书中没有可用的人设或世界规则条目');ui.setLoreStatus('已连接：'+book.name+' · 本次选取 '+result.selected.length+' / '+result.total+' 条'+(result.trimmed?'（部分内容受长度限制）':''));return JSON.stringify({roles:ui.roles,user:c.name1,userIdentity:{authorId:'me',momentsId:store().feedProfile?.id||c.name1,note:'朋友圈ID是用户的公开昵称，改名后仍是同一个用户，历史动态也属于用户'},character:c.name2,birthdays:characterBirthdays,todaysBirthdays:birthdaysToday(world(store()).calendar),worldbook:book.name,entries:result.selected,messageEditingPreferences:messageEditGuidance(store())});}
async function completion(messages,signal,maxTokens=config().maxTokens){
  requireActive();const cfg=config();let sharedNames='';try{sharedNames=groupCardMemory(publicGroupCards(store(),groups(ui.roles,store().customGroups||[]),ui.roles,context().name1));}catch{}const general=knowledgeBoundary+'\n'+sharedNames+'\n'+prompt('general')+'\n用户自定义的内容偏好和语气优先于内置风格；必须保留当前任务要求的输出结构、角色身份和交易约束。';messages=messages.map(m=>({...m}));if(general){if(messages[0]?.role==='system')messages[0].content=general+'\n'+messages[0].content;else messages.unshift({role:'system',content:general});}if(!cfg.url||!cfg.model||!sessionKey)throw Error('请先在手机设置填写 API 地址、模型和本次会话 Key');
  const url=endpoint(cfg.url,cfg.allowHttp);if(location.protocol==='https:'&&url.startsWith('http:'))throw Error('当前酒馆使用 HTTPS，浏览器可能阻止 HTTP 接口。请使用服务商的 HTTPS 地址或自行配置 HTTPS 反向代理。');const timeout=new AbortController();apiRequests.add(timeout);const forward=()=>timeout.abort();signal?.addEventListener('abort',forward,{once:true});if(signal?.aborted)timeout.abort();const started=Date.now(),chars=JSON.stringify(messages).length;let timedOut=false;const id=setTimeout(()=>{timedOut=true;timeout.abort();},(cfg.requestTimeout||180)*1000);lastApiInfo={chars,maxTokens,stream:cfg.apiStream!==false,started,status:'请求中'};
  try{const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+sessionKey},body:JSON.stringify({model:cfg.model,messages,stream:cfg.apiStream!==false,max_tokens:maxTokens,temperature:0.5}),signal:timeout.signal,credentials:'omit',redirect:'error'});if(!response.ok)throw await apiFailure(response,sessionKey);lastApiInfo.response={};const text=decodeCompletion(await response.text(),lastApiInfo.response);lastApiSuccess=true;lastApiInfo={...lastApiInfo,replyPreview:text.split(sessionKey).join('[Key 已隐藏]').slice(0,1200),status:'已收到回复（内容格式另行校验）',seconds:Math.round((Date.now()-started)/1000)};return text;}catch(e){const failure=networkFailure(e,{aborted:signal?.aborted,timedOut,elapsed:Date.now()-started,chars,lastSuccess:lastApiSuccess});lastApiInfo={...lastApiInfo,status:failure.message,seconds:Math.round((Date.now()-started)/1000)};throw failure;}finally{apiRequests.delete(timeout);clearTimeout(id);signal?.removeEventListener('abort',forward);}
}

function installStatePrompt(type='normal'){const c=context();if(!active()){c.setExtensionPrompt?.('junimo_pocket_state','',1,0,false,0);c.setExtensionPrompt?.('junimo_pocket_actions','',1,0,false,1);return;}try{const actionStore=store();c.setExtensionPrompt?.('junimo_pocket_actions',['quiet','impersonate'].includes(type)?'':directActionPrompt(actionStore,world(actionStore)),1,0,false,1);}catch{c.setExtensionPrompt?.('junimo_pocket_actions','',1,0,false,1);}try{resolveBinding(c,config().boundAvatar);const s=store(),base=promptBaseline(s,c.chat,type);let cutoff=c.chat.length;if(['regenerate','swipe'].includes(type)&&c.chat.at(-1)&&!c.chat.at(-1).is_user&&!c.chat.at(-1).is_system)cutoff--;const prior=s.turns.slice(0,cutoff).at(-1),state=world({...s,turns:s.turns.slice(0,cutoff)});const memoryStore={...s,turns:s.turns.slice(0,cutoff)};c.setExtensionPrompt?.('junimo_pocket_state',(config().enabled?statePrompt(state,ui.roles,ui.mapAnchors,base.initial,config().appPrompts)+'\n':'')+groupCardMemory(publicGroupCards(memoryStore,groups(ui.roles,store().customGroups||[]),ui.roles,c.name1))+'\n'+knowledgeBoundary+'\n'+(memoryStore.taskCompletionReceipts?.length?'\n【已完成任务收据，禁止重复领取】'+JSON.stringify(memoryStore.taskCompletionReceipts.slice(-30)):'')+narrativeMemory(memoryStore,ui.roles)+'\n'+messageEditGuidance(memoryStore)+'\n'+publicMemory(memoryStore,ui.roles)+'\n'+(memoryStore.turns.at(-1)?.farmCorrection||'')+'\n'+animalMemory(memoryStore)+'\n'+mailSyncInstruction+bootstrapPrompt(s)+offeringMemory(s)+birthdayMemory(state.calendar),1,0,false,0);}catch{c.setExtensionPrompt?.('junimo_pocket_state','',1,0,false,0);}}
async function signatures(){return Promise.all(context().chat.map(async(m,index)=>({index,message:m,signature:await fingerprint(storyKey(m)),legacySignature:await fingerprint(JSON.stringify([m.is_user,m.is_system,m.name,m.mes,m.swipe_id]))})));}
function contentChanged(){if(!active())return;const keys=context().chat.map(storyKey);if(keys.length===lastStoryKeys.length&&keys.every((k,i)=>k===lastStoryKeys[i]))return;lastStoryKeys=keys;invalidate();schedule();}
async function generateProactive(s,turn,narrative,signal,run){
 if(!config().proactive||turn.phoneDone||!sessionKey||!config().url)return;
 try{const background=await roleContext('',narrative,signal);const raw=await completion([{role:'system',content:prompt('style')+promptStickers()+prompt('images')+promptSocial(world(s))+'\n'+promptCategories()+(config().mailCustomRules?'\n'+prompt('mailPreference',{preferences:JSON.stringify(config().mailCustomRules)})+'\n':'')+prompt('proactive')},{role:'user',content:JSON.stringify({roles:ui.roles,background,narrative,publicPosts:publicPostsData(s,20),sharedTimeline:phoneTimeline(s,{members:ui.roles.map(r=>r.id)},ui.roles,reducedRequest?30:60),state:formatState(world(s),ui.roles),existingMail:allLetters(s).slice(0,15).map(l=>({subject:l.subject,senderId:l.senderId})),commissions:s.mailQuests||[]})}],signal);
 const result=parseResponseJSON(raw);if(!Array.isArray(result.messages)||result.messages.length>2)throw Error('主动消息格式无效');
 const incoming=[];for(const item of result.messages){if(!ui.roles.some(r=>r.id===item.roleId))throw Error('主动消息角色无效');for(const bubble of parseChatReply(JSON.stringify({bubbles:item.bubbles}),ui.roles.find(r=>r.id===item.roleId),ui.roles,stickerCatalog()))incoming.push({roleId:item.roleId,...bubble,from:'role',created:Date.now()+incoming.length,time:world(s).calendar.time});}
 if(run!==epoch)return;const extras=parseSocial(raw,ui.roles,world(s),undefined,{mailPreferences:config().mailPreferences});turn.letters=[...(turn.letters||[]),...extras.letters.map(l=>({...l,...stamp(s)}))];for(const gift of extras.transfers)s.unread[gift.roleId]=true;if(extras.letters.length)ui.notify('收到 '+extras.letters.length+' 封新信');turn.messages.push(...extras.transfers.map(m=>({...m,...stamp(s)})));turn.phoneDone=true;delete turn.phoneError;render();await persist();for(const m of incoming){if(run!==epoch)return;turn.messages.push(m);s.unread[m.roleId]=true;render();await persist();await new Promise(r=>setTimeout(r,450));}if(incoming.length)ui.notify('收到 '+incoming.length+' 条手机消息');
 }catch(e){if(e.name!=='AbortError'){turn.phoneError=e.message;status('变量已更新；主动消息未完成：'+e.message);}}
}
async function syncNarrative(forceLatest=false){
 if(!active())return;if(working){pending=true;return;}if(!currentId()||generation)return;working=true;pending=false;const run=epoch,id=currentId();controller=new AbortController();
 try{const s=store(),rows=await signatures(),latestStory=rows.findLastIndex(r=>!r.message.is_user&&!r.message.is_system);if(run!==epoch)return;lastStoryKeys=context().chat.map(storyKey);if(!s.storySignatureVersion){for(let i=0;i<s.turns.length&&i<rows.length;i++){const t=s.turns[i],m=rows[i].message;t.signature=rows[i].signature;if(!m.is_user&&!m.is_system){try{const p=readStateBlock(storyText(m.mes),t.state,{roles:ui.roles,anchors:ui.mapAnchors,userName:context().name1});if(p){t.state=p.state;t.hasState=true;}}catch{}}}s.storySignatureVersion=1;}for(let i=0;i<s.turns.length;i++)if(s.turns[i].signature===rows[i]?.legacySignature)s.turns[i].signature=rows[i].signature;let {keep,oldTurns}=reconcileForSync(s,rows.map(r=>r.signature));if(!config().enabled&&!forceLatest){installStatePrompt();return;}resolveBinding(context(),config().boundAvatar);
 if(!s.historyBootstrap&&s.started)s.historyBootstrap={version:1,floors:rows.length,pending:true,reference:historyReference(context().chat),readAt:Date.now()};
 if(!s.started){s.started=true;keep=0;s.historyBootstrap={version:1,floors:rows.length,readAt:Date.now(),pending:true,reference:historyReference(context().chat)};}
 for(let i=0;i<keep;i++)syncTurnMail(s,s.turns[i],rows[i]?.message);if(latestStory>=0&&latestStory<keep&&s.turns[latestStory]?.hasState){const t=s.turns[latestStory];s.draft=settleActionDraft(s.draft,t.actionDraft,t.actionBase||s.base,world(s),{consumeNonFarm:false,conflicts:t.actionDraft?farmMismatch(t.actionDraft,t.actionBase||s.base,world(s)):[]});}render();await persist();if(forceLatest){const last=rows.findLastIndex(r=>!r.message.is_user&&!r.message.is_system);if(last>=0){s.turns.splice(last);keep=last;render();}}
 for(let i=keep;i<rows.length;i++){
   if(run!==epoch||id!==currentId()||generation)return;const {message:m,signature}=rows[i];const before=checkpoint(s);const prior=s.turns[i-1],historic=oldTurns[i],old=historic?.signature===signature?historic:null;const applied=old?.socialRevision??(i===latestStory&&!m.is_user&&s.pendingNarrativeRevision!=null?s.pendingNarrativeRevision:prior?.socialRevision??s.baseSocialRevision??0);let state=applySocialEvents(prior?.state||s.base,(s.socialEvents||[]).filter(e=>e.revision<=applied),prior?.socialRevision??s.baseSocialRevision??0),hasState=false,changed=[],warnings=[];
   if(!m.is_user&&!m.is_system&&m.mes?.trim()){
     let parsed;try{parsed=readStateBlock(m.mes,state,{roles:ui.roles,anchors:ui.mapAnchors,userName:context().name1,initial:!s.turns.slice(0,i).some(t=>t.hasState)});}catch(e){if(i===rows.length-1)throw e;warnings.push('历史第'+(i+1)+'楼格式异常，已跳过');}
     if(parsed){state=parsed.state;changed=Object.keys(parsed.patch);warnings=parsed.warnings||[];hasState=true;}else status('本轮正文缺少变量块：请重新生成，手机不会猜测数值');
   }
   const turn={...old,before:historic?.before||before,signature,state,socialRevision:applied,messages:old?.messages||[],hasState};if(!m.is_user&&!m.is_system){turn.actionDraft=clone(old?.actionDraft??(i===latestStory?s.pendingNarrativeDraft??s.draft:historic?.actionDraft??null));turn.actionBase=clone(old?.actionBase??(i===latestStory?s.pendingNarrativeBase??prior?.state??s.base:historic?.actionBase??prior?.state??s.base));if(i===latestStory){delete s.pendingNarrativeDraft;delete s.pendingNarrativeBase;}}if(i===latestStory&&!m.is_user)delete s.pendingNarrativeRevision;s.turns[i]=turn;syncTurnMail(s,turn,m);if(hasState&&s.historyBootstrap?.pending&&i>=s.historyBootstrap.floors)s.historyBootstrap.pending=false;if(hasState&&i===latestStory){const conflicts=turn.actionDraft?farmMismatch(turn.actionDraft,turn.actionBase,state):[];s.draft=settleActionDraft(s.draft,turn.actionDraft,turn.actionBase||s.base,state,{conflicts});if(conflicts.length){ui.notify('正文与手机农田操作不一致：第'+conflicts.join(',')+'格。操作已保留，请在行动篮核对。');}delete s.needsRefresh;}
   if(i===rows.length-1){render();await persist();installStatePrompt();}
   if(hasState){const names={gold:'金币',calendar:'日历',inventory:'背包',plots:'农田',locations:'地图',quests:'任务',calendarEvents:'日程',animals:'动物',buildings:'建筑',relationships:'好感度',notes:'农场记录'};status('正文变量已更新：'+(changed.map(k=>names[k]||k).join('、')||'本轮无变化')+(warnings.length?'；待修正：'+warnings.join('；'):''));if(i===rows.length-1)await generateProactive(s,turn,extractNarrative(m.mes.split(/<junimo-state>|【手机状态】/)[0]),controller.signal,run);if(i===rows.length-1&&!turn.feedDone){turn.feedDone=true;await generatePosts(s,turn,controller.signal,run);if(run===epoch)await persist();}}
 }
 }catch(e){error(e);}finally{working=false;controller=null;if(pending){pending=false;schedule();}}
}
function schedule(){clearTimeout(timer);if(!active())return;timer=setTimeout(()=>syncNarrative(),600);}
function invalidate(){ui?.clearTyping();epoch++;controller?.abort();pending=true;}

function stamp(s){const d=world(s).calendar;return {created:Math.max(Date.now(),(allPhoneMessages(s).at(-1)?.created||0)+1),time:d.time,storyDate:[d.year,d.season,d.day].join('/')};}
async function queueBubble(role,value){const sticker=value?.type==='sticker'?getSticker(value.stickerId):null;if(value?.type==='sticker'&&!sticker)throw Error('表情包已不可用');const media=value?.type==='image'?getImage(value.mediaId):null;if(value?.type==='image'&&!media)throw Error('图片已不可用');const text=media?'[图片/照片/截图] '+(media.description||'未填写说明'):sticker?'[表情包：'+sticker.name+'] '+sticker.description:typeof value==='string'?value:value?.text,type=typeof value==='string'?'text':value?.type||'text';if(typeof text!=='string'||!text.trim())return;if(text.length>4000||!['text','voice','sticker','image'].includes(type))throw Error('消息格式无效或超过4000字');const s=store();const quoteId=value?.quoteId&&allPhoneMessages(s).some(m=>m.id===value.quoteId&&m.roleId===role.id)?value.quoteId:undefined;const mentionIds=validateMentionIds(role,value?.mentionIds||[]);s.manual.push({id:newId(),quoteId,mentionIds,mentions:(Array.isArray(value?.mentions)?value.mentions:[]).filter(m=>m.ids?.some(id=>mentionIds.includes(id))),roleId:role.id,from:'me',text:text.trim(),type,...(media?{mediaId:media.id}:{}),...(sticker?{stickerId:sticker.id,stickerName:sticker.name}:{}),...(type==='voice'?{duration:Math.max(1,Math.min(180,Math.ceil(text.trim().length/4)))}:{}),...stamp(s),status:'queued'});render();await persist();}
async function send(role,text='',reroll=false,instruction=''){
 if(text.trim())await queueBubble(role,text);if(working||generation)throw Error('请等待当前生成结束');
 const s=store(),run=epoch,id=currentId(),cfg=config(),old=reroll?s.chatRound:null;
 if(reroll)assertRerollable(s,old);const threads=pendingThreads(s,ui.roles,old?.inputIds);
 if(!threads.length)throw Error('各个聊天都没有待回复气泡，请先发送消息');
 const queued=threads.flatMap(t=>t.messages),round=old||{id:newId(),inputIds:queued.map(m=>m.id),floor:s.turns.length};
 const memory=withoutRound(s,old),oldStatuses=queued.map(m=>m.status);s.chatRound=round;
 working=true;controller=new AbortController();queued.forEach(m=>m.status='sending');threads.forEach(t=>ui.setTyping(t.role.id,'正在回复…'));render();status('正在回复…');
 try{const background=await roleContext([...new Set(threads.flatMap(t=>t.role.members||[t.role.id]))].map(id=>ui.roles.find(r=>r.id===id)?.name).join('、'),queued.map(m=>m.text).join('\n'),controller.signal);
 const payload=threads.map(({role,messages})=>({threadId:role.id,name:role.name,members:role.members||[role.id],instruction:prompt(role.members?'group':'private',{name:role.name,id:role.id,members:ui.roles.filter(r=>role.members?.includes(r.id)).map(r=>r.name+'（'+r.id+'）').join('、')}),followupInstruction:prompt('followup',{groups:JSON.stringify(groups(ui.roles,store().customGroups||[]))}),timeline:phoneTimeline(memory,role,ui.roles,Math.max(40,cfg.history*3),messages.at(-1).created),letters:allLetters(memory).filter(l=>(role.members||[role.id]).includes(l.senderId)).slice(0,10),pendingMessages:messages.map(m=>({id:m.id,text:m.text,mentionIds:m.mentionIds||[],type:m.type,mediaId:m.mediaId,stickerId:m.stickerId,quote:quotedMessage(memory,m)}))}));
 const allowPosts=shouldPost(cfg.feedFrequency||'normal'),allowComments=shouldPost(cfg.commentFrequency||'normal');
 const raw=await completion([{role:'system',content:prompt('style')+'\n'+prompt('batch')+'\n'+promptStickers()+prompt('images')+promptSocial(world(memory))+'\n'+promptCategories()+'\n'+prompt('context')+'\n'+promptIdentity()+'\n'+(allowPosts?prompt('feed'):'不生成动态。')+'\n'+(allowComments?prompt('comments'):'不生成评论。')+'\n'+prompt('batchFormat')},{role:'user',content:withStickerImages(JSON.stringify({revisionInstruction:instruction,previousReply:reroll?allPhoneMessages(s).filter(m=>m.batchId===old?.id):[],background,narrative:recentNarrative(),threads:payload,publicPosts:publicPostsData(memory),state:formatState(world(memory),ui.roles),allowPosts,allowComments}),payload.flatMap(t=>[...t.timeline,...t.pendingMessages]),cfg.stickerVision)}],controller.signal,cfg.maxTokens);
 const parsed=parseBatch(raw,threads,ui.roles,stickerCatalog());
 const results=parsed.map(p=>({...p,followups:parseFollowups(p.raw,p.role,ui.roles,stickerCatalog(),memory.customGroups||[]),extras:parseSocial(p.raw,ui.roles,world(memory),p.role.members||[p.role.id],{mailPreferences:cfg.mailPreferences})}));
 const output=parseResponseJSON(raw),posts=allowPosts&&output.posts?parsePosts(raw,ui.roles,ui.roles.map(r=>r.id)):[],comments=allowComments&&output.comments?parseComments(raw,allPosts(memory),ui.roles,allPosts(memory).flatMap(p=>commentsFor(memory,p.id)),{tolerant:true}):[];
 if(run!==epoch||id!==currentId())throw new DOMException('对话已变化','AbortError');
 const clean=withoutRound(s,old);for(const key of ['manual','letters','posts','comments'])s[key]=clean[key]||[];
 queued.forEach(m=>m.status='sent');
 for(const {role,bubbles,extras,followups} of results){for(const bubble of bubbles)s.manual.push({id:newId(),roleId:role.id,from:'role',...bubble,...stamp(s),batchId:round.id});for(const gift of extras.transfers)s.manual.push({...gift,roleId:role.id,...stamp(s),batchId:round.id});s.letters.push(...extras.letters.map(l=>({...l,...stamp(s),batchId:round.id})));s.unread[role.id]=true;for(const bubble of followups){s.manual.push({id:newId(),from:'role',...bubble,...stamp(s),batchId:round.id});s.unread[bubble.roleId]=true;}}
 s.posts.push(...posts.map(p=>({...p,...stamp(s),batchId:round.id})));s.comments.push(...comments.filter(c=>!identityConflict(c.authorId,c.text,ui.roles)).map(c=>({...c,...stamp(s),batchId:round.id})));
 round.success=true;render();await persist();status('已用一次请求回复 '+threads.length+' 个聊天');
 }catch(e){queued.forEach((m,i)=>{if(m.status==='sending')m.status=reroll?oldStatuses[i]:'failed';});if(run===epoch){render();await persist();}throw e;}finally{ui.clearTyping();working=false;controller=null;if(pending){pending=false;schedule();}}
}
async function rerollChat(role,instruction=''){return send(role,'',true,instruction);}
async function completeTasks(names){requireSocialIdle();if(!Array.isArray(names)||!names.length||new Set(names).size!==names.length)throw Error('请选择要核对的任务');const s=store(),run=epoch,before=world(s),tasks=names.map(name=>before.quests.find(q=>q.name===name&&!questCompleted(q)));if(tasks.some(q=>!q))throw Error('所选任务已完成或不存在');const snapshot=JSON.stringify(s),narrative=recentNarrative(config().maxChars||12000);working=true;controller=new AbortController();status('正在批量核对 '+tasks.length+' 个任务…');try{const raw=await completion([{role:'system',content:taskBatchInstruction},{role:'user',content:JSON.stringify({selectedTasks:tasks,narrative,gold:before.gold,inventory:before.inventory,settledTasks:s.taskCompletionReceipts||[],transactions:(s.socialEvents||[]).slice(-25).map(e=>({description:e.description,gold:e.gold,items:e.items}))})}],controller.signal,Math.min(config().maxTokens||6000,6000));if(run!==epoch||JSON.stringify(s)!==snapshot)throw Error('手机进度已变化，请重新核对');const decisions=parseTaskBatch(raw,tasks,narrative),result=applyTaskBatch(s,tasks,decisions,'task-check-'+newId());Object.assign(s,result.store);render();await persist();status('任务核对完成：'+result.done.length+'项完成'+(result.pending.length?'；未完成：'+result.pending.map(x=>x.name+'（'+x.reason+'）').join('、'):''));return {done:result.done,pending:result.pending};}finally{working=false;controller=null;if(pending){pending=false;schedule();}}}
async function reviewFarm(){requireSocialIdle();const s=store(),turn=s.turns.at(-1);if(!s.draft?.conflicts?.length||!turn?.actionDraft)throw Error('没有待核对的农田差异');if(JSON.stringify(s.draft.actions)!==JSON.stringify(turn.actionDraft.actions))throw Error('你又安排了新的操作，请先取消新增操作，再核对上一轮');const run=epoch,signature=turn.signature,draftSnapshot=JSON.stringify(s.draft),current=world(s),candidate=reviewedFarmState(turn.actionDraft,turn.actionBase,current);ui.reviewState(formatFarmReview(candidate,current,ui.roles,ui.mapAnchors),'核对正文与手机的差异：第'+s.draft.conflicts.join(',')+'格。此预览按手机安排恢复农田并核算本轮播种用掉的种子；请检查其他物品。确认只校正手机记忆，不改写正文。',async raw=>{requireSocialIdle();if(run!==epoch||s!==store()||s.turns.at(-1)?.signature!==signature||JSON.stringify(world(s))!==JSON.stringify(current)||JSON.stringify(s.draft)!==draftSnapshot)throw Error('进度已变化，请重新核对');const result=readStateBlock(raw,current,{roles:ui.roles,anchors:ui.mapAnchors,userName:context().name1});if(!result)throw Error('请保留状态开始结束标记');turn.state=result.state;turn.socialRevision=socialRevision(s);s.draft=null;turn.farmCorrection='上轮农田摘要有误，用户已核对为手机所选格号；已修正的状态见基线，不要重复播种或再次扣种子。';render();await persist();});}
async function acceptFarmNarrative(){requireSocialIdle();const s=store();if(s.draft?.conflicts?.length){if(JSON.stringify(s.draft.actions)!==JSON.stringify(s.turns.at(-1)?.actionDraft?.actions))throw Error('你又安排了新的操作，请先取消新增操作，再核对上一轮');s.draft=null;render();await persist();}}
async function repairState(scope='全部',instruction=''){
 if(['动物','朋友圈','图鉴'].includes(scope))return repairRecords(scope,instruction);
 const restrict=p=>repairPatch(scope,p);restrict({});
 if(working||generation)throw Error('请等待正文或当前请求结束');const s=store(),run=epoch,id=currentId(),rows=await signatures(),signature=JSON.stringify(rows.map(r=>r.signature)),base=world(s);working=true;controller=new AbortController();status('AI 正在整理变量，尚未应用…');
 try{const narrative=recentNarrative(),background=await roleContext('',narrative,controller.signal);const raw=await completion([{role:'system',content:prompt('repairState')+statePrompt(base,ui.roles,ui.mapAnchors,!s.turns.some(t=>t.hasState),config().appPrompts)},{role:'user',content:'校正范围：'+scope+'；只修正要求涉及的字段；用户明确说不动的项目必须保持原值。修改要求：'+instruction+'\n世界书：'+background+'\n最近正文：'+narrative}],controller.signal,config().repairTokens||12000);if(run!==epoch||id!==currentId())throw new DOMException('对话已变化','AbortError');const parsed=readStateBlock(raw,base,{roles:ui.roles,anchors:ui.mapAnchors,userName:context().name1,initial:!s.turns.some(t=>t.hasState)});if(!parsed)throw Error('AI 没有返回文字状态摘要，未改动变量');const names={calendar:'时间',gold:'金币',inventory:'背包',plots:'农田',locations:'位置',relationships:'好感',quests:'任务',animals:'动物',buildings:'建筑',calendarEvents:'日程',notes:'记录',capacity:'容量',player:'玩家状态',recipes:'图纸',farmProjects:'农场工程'};parsed.patch=restrict(parsed.patch);parsed.state=applyPatch(base,parsed.patch);const changed=Object.keys(parsed.patch).filter(k=>JSON.stringify(base[k])!==JSON.stringify(parsed.state[k])).map(k=>names[k]||k);status('整理完成，等待你核对并确认');
 ui.reviewState(formatState(parsed.state,ui.roles,ui.mapAnchors),'范围：'+scope+'。预计更新：'+(changed.join('、')||'无差异')+'。下方可直接修改；取消不会改变存档。'+(parsed.warnings?.length?'待修正：'+parsed.warnings.join('；'):''),async text=>{if(working||generation)throw Error('请等待当前请求结束再确认');if(run!==epoch||id!==currentId()||signature!==JSON.stringify((await signatures()).map(r=>r.signature)))throw Error('正文或对话已变化，请取消后重新整理');if(JSON.stringify(world(s))!==JSON.stringify(base))throw Error('手机状态已变化，请重新整理');const value=readStateBlock(text,base,{roles:ui.roles,anchors:ui.mapAnchors,userName:context().name1,initial:!s.turns.some(t=>t.hasState)});if(!value)throw Error('请保留手机状态的开始和结束标记');value.state=applyPatch(base,restrict(value.patch));s.backup=clone({base:s.base,turns:s.turns,manual:s.manual,draft:s.draft,baseSocialRevision:s.baseSocialRevision||0,socialEvents:clone(s.socialEvents||[]),mailQuests:clone(s.mailQuests||[]),letters:clone(s.letters||[])});s.turns=rows.map((r,i)=>({...s.turns[i],signature:r.signature,socialRevision:i===rows.length-1?socialRevision(s):s.turns[i]?.socialRevision||0,state:clone(i===rows.length-1?value.state:s.turns[i]?.state||s.base),messages:s.turns[i]?.messages||[],hasState:i===rows.length-1||!!s.turns[i]?.hasState}));if(!rows.length){s.base=value.state;s.baseSocialRevision=socialRevision(s);}const lastTurn=s.turns.findLast(t=>t.actionDraft);s.draft=settleActionDraft(s.draft,lastTurn?.actionDraft,lastTurn?.actionBase||base,value.state,{consumeNonFarm:false});s.started=true;await persist();render();installStatePrompt();status('已按确认结果更新变量');});
 }finally{working=false;controller=null;if(pending){pending=false;schedule();}}
}
async function repairRecords(scope,instruction){requireSocialIdle();const s=store(),run=epoch,source=scope==='动物'?{animals:clone(s.herd?.animals||[])}:scope==='图鉴'?{categories:Object.values(s.catalog||{}).map(x=>({name:x.name,category:x.category}))}:{posts:allPosts(s).filter(p=>p.authorId!=='me'),comments:allPosts(s).flatMap(p=>commentsFor(s,p.id)).filter(c=>c.authorId!=='me')},snapshot=JSON.stringify(s);working=true;controller=new AbortController();try{const background=await roleContext('',recentNarrative(),controller.signal),shape=scope==='动物'?'{animals:[{id,age,friendship,mood,fed,pet,outside}]}':scope==='图鉴'?'{categories:[{name,category}]}':'{posts:[{id,text,imageDescription}],comments:[{id,text}]}';const raw=await completion([{role:'system',content:prompt('repairRecords',{shape,categories:itemCategories.join('、')})},{role:'user',content:JSON.stringify({scope,instruction,source,background,narrative:recentNarrative()})}],controller.signal,config().repairTokens||12000);if(run!==epoch||s!==store())throw Error('对话已变化');correctionPatch(scope,parseResponseJSON(raw),source);ui.reviewState(raw,scope+'修改预览。确认后只应用列出的记录，其他记录保留。',async text=>{requireSocialIdle();if(run!==epoch||s!==store()||JSON.stringify(s)!==snapshot)throw Error('进度已变化，请重新校正');const patch=correctionPatch(scope,parseResponseJSON(text),source);for(const p of patch.posts||[])if(identityConflict(p.authorId,p.text,ui.roles))throw Error('动态职业与作者身份不符');s.recordBackup=clone({herd:s.herd,catalog:s.catalog,posts:s.posts,comments:s.comments,turns:s.turns});if(patch.animals)for(const a of patch.animals){const at=s.herd.animals.findIndex(x=>x.id===a.id);s.herd.animals[at]=a;}if(patch.categories)for(const x of patch.categories)s.catalog[x.name].category=x.category;for(const key of ['posts','comments'])for(const item of patch[key]||[])for(const owner of [s,...s.turns]){const at=owner[key]?.findIndex(x=>x.id===item.id);if(at>=0)owner[key][at]=item;}render();await persist();});}finally{working=false;controller=null;if(pending){pending=false;schedule();}}}
function addSocialAction(s,text){const draft=s.draft||{actions:[],plots:clone(world(s).plots)};draft.actions.push('【手机已结算，请勿重复扣增】'+text);s.draft=draft;}
function requireSocialIdle(){requireActive();if(working||generation)throw Error('请等待当前回复结束再操作');resolveBinding(context(),config().boundAvatar);}
async function sendTransfer(role,{kind,item,count,amount,note='',recipientId}){requireSocialIdle();const s=store(),state=world(s),target=role.members?.includes(recipientId)?recipientId:role.members?null:role.id;if(!target)throw Error('请先选择收礼人');const name=ui.roles.find(r=>r.id===target)?.name;if(!name)throw Error('收礼角色无效');const id=newId();let items=[],gold=0,text;if(kind==='gift'){const owned=state.inventory.find(x=>x.name===item);if(!owned||!Number.isInteger(count)||count<1||count>owned.count)throw Error('背包物品数量不足');items=[{...owned,count:-count}];text='给'+name+'赠送 '+item+' ×'+count;}else if(kind==='redpacket'){if(!Number.isInteger(amount)||amount<1||amount>state.gold)throw Error('红包金额须为不超过余额的正整数');gold=-amount;text='给'+name+'发送 '+amount+' 金币红包';}else throw Error('赠送类型无效');appendTransaction(s,state,{id,gold,items,description:text});s.manual.push({id,roleId:role.id,recipientId:target,from:'me',type:kind,item,count,amount,note:String(note).slice(0,100),text,claimed:true,status:'queued',...stamp(s)});addSocialAction(s,text);render();await persist();}
async function claimTransfer(id){requireSocialIdle();const s=store(),message=allPhoneMessages(s).find(m=>m.id===id);if(!message||message.from!=='role'||!['gift','redpacket'].includes(message.type))throw Error('找不到这份赠送');if(message.claimed||s.socialEvents?.some(e=>e.id==='claim-'+id))return;const name=ui.roles.find(r=>r.id===(message.speakerId||message.roleId))?.name||'角色',text='领取'+name+'的'+(message.type==='gift'?message.item+' ×'+message.count:message.amount+' 金币红包');const owned=world(s).inventory.find(x=>x.name===message.item);appendTransaction(s,world(s),{id:'claim-'+id,gold:message.type==='redpacket'?message.amount:0,items:message.type==='gift'?[{...(owned||{name:message.item,kind:'item',price:0,priceUnknown:true}),count:message.count}]:[],description:text});message.claimed=true;addSocialAction(s,text);render();await persist();}
async function collectMail(reroll=false,instruction=''){requireSocialIdle();const s=store(),run=epoch,id=currentId(),old=reroll?s.mailRound:null;if(reroll)assertRerollable(s,old);const round=old||{id:newId(),floor:s.turns.length};s.mailRound=round;const memory=withoutRound(s,old);working=true;controller=new AbortController();status('正在根据正文和手机聊天生成新信…');try{const background=await roleContext('',recentNarrative(),controller.signal),state=world(s);const raw=await completion([{role:'system',content:prompt('collect')+promptSocial(state,4)+'\n'+promptCategories()+(config().mailCustomRules?'\n'+prompt('mailPreference',{preferences:JSON.stringify(config().mailCustomRules)})+'\n':'')},{role:'user',content:JSON.stringify({revisionInstruction:instruction,previousLetters:reroll?allLetters(s).filter(l=>l.batchId===old?.id):[],roles:ui.roles,background,narrative:recentNarrative(),sharedTimeline:phoneTimeline(s,{members:ui.roles.map(r=>r.id)},ui.roles,100),state,existing:allLetters(memory).slice(0,30).map(l=>({subject:l.subject,body:l.body})),commissions:s.mailQuests||[]})}],controller.signal,config().mailTokens||8000);if(run!==epoch||id!==currentId())throw new DOMException('对话已切换','AbortError');const parsed=parseSocial(raw,ui.roles,state,undefined,{letterLimit:4,mailPreferences:config().mailPreferences});if(!parsed.letters.length)throw Error(parsed.warnings.join('；')||'API 未返回有效信件，请点击重新生成');s.letters=withoutRound(s,old).letters||[];s.letters.push(...parsed.letters.map(l=>({...l,...stamp(s),batchId:round.id})));round.success=true;render();await persist();status(parsed.letters.length?'收到 '+parsed.letters.length+' 封信':'暂时没有新信');ui.toast(parsed.letters.length?'新信已经放进信箱':'暂时没有新信');}finally{working=false;controller=null;if(pending){pending=false;schedule();}}}
async function readMail(id){const s=store(),letter=allLetters(s).find(l=>l.id===id);if(letter){letter.read=true;const learned=letterRecipes(letter);if(learned.length){const state=applyPatch(world(s),{recipes:learned});if(s.turns.length){s.turns.at(-1).state=state;s.turns.at(-1).socialRevision=socialRevision(s);}else{s.base=state;s.baseSocialRevision=socialRevision(s);}}render();await persist();}}
async function acceptMail(id){requireSocialIdle();const s=store(),letter=allLetters(s).find(l=>l.id===id);if(!letter?.quest)throw Error('这封信没有可接取的委托');if(s.mailQuests?.some(q=>q.id===id))return;(s.mailQuests??=[]).push({id,subject:letter.subject,body:letter.body,senderId:letter.senderId,anonymous:letter.anonymous,...letter.quest,status:'active',accepted:Date.now()});addSocialAction(s,'接取邮件委托“'+letter.subject+'”：交付 '+letter.quest.item+' ×'+letter.quest.count+'，报酬 '+letter.quest.rewardGold+' 金币（尚未交付与领奖）');render();await persist();}
async function deliverMail(id){requireSocialIdle();const s=store(),quest=s.mailQuests?.find(q=>q.id===id);if(!quest||quest.status!=='active')throw Error('委托已经完成或尚未接取');const owned=world(s).inventory.find(x=>x.name===quest.item);if(!owned||owned.count<quest.count)throw Error('背包里还没有足够的 '+quest.item);const text='完成邮件委托“'+quest.subject+'”：交付 '+quest.item+' ×'+quest.count+'，获得 '+quest.rewardGold+' 金币';appendTransaction(s,world(s),{id:'quest-'+id,items:[{...owned,count:-quest.count}],gold:quest.rewardGold,description:text});quest.status='completed';quest.completed=Date.now();addSocialAction(s,text);render();await persist();}
function field(label,type,value){const wrap=document.createElement('label');wrap.textContent=label;const input=document.createElement(type==='textarea'?'textarea':'input');if(type!=='textarea')input.type=type;input.value=value??'';if(type==='checkbox')wrap.className='jp-switch';wrap.append(input);(settingsTarget||settingsPanel).append(wrap);return input;}
function button(label,callback){const b=document.createElement('button');b.textContent=label;b.type='button';b.onclick=async()=>{b.disabled=true;try{await callback();}catch(e){error(e);}finally{b.disabled=false;}};(settingsTarget||settingsPanel).append(b);return b;}
function openSettings(){
  settingsPanel.replaceChildren();settingsTarget=null;ui.showSettings();const cfg=config();const heading=document.createElement('div');heading.className='jp-settings-hero';heading.innerHTML='<small>JUNIMO POCKET</small><h3>随身设置</h3><p>让连接、故事和聊天各就各位</p>';settingsPanel.append(heading);
function section(title,subtitle,open=true){const card=document.createElement('details');card.className='jp-settings-card';card.open=open;const summary=document.createElement('summary');summary.textContent=title;const body=document.createElement('div');body.className='jp-card-content';const note=document.createElement('p');note.textContent=subtitle;body.append(note);card.append(summary,body);settingsPanel.append(card);settingsTarget=body;}

  const help=document.createElement('p');help.textContent='正文变量读取末尾的简短文字状态摘要，不消耗独立 API。独立 API 用于手机私聊、群聊和主动消息；也可手动整理变量，核对后确认应用。保存 API 预设后，地址、Key 和模型会保存在本机此浏览器，刷新后可继续使用；不会包含在聊天存档导出中。HTTP 会明文传输 Key 和聊天内容。';help.className='jp-settings-footnote';
  const loreInfo=document.createElement('p');loreInfo.className='jp-lore-info';settingsPanel.append(loreInfo);try{loreInfo.textContent='绑定世界书：'+resolveBinding(context(),cfg.boundAvatar).name+' · 每次请求前重新读取';}catch(e){loreInfo.textContent=e.message;}
  section('01 · API 连接','保存常用渠道，一键切换');const presetStore='junimo_pocket_api_presets_v1';let saved={items:[],active:''};try{const value=JSON.parse(localStorage.getItem(presetStore)||'null');if(Array.isArray(value?.items))saved=value;}catch{}
  const selectField=label=>{const wrap=document.createElement('label');wrap.textContent=label;const el=document.createElement('select');el.style.cssText='display:block;width:100%;padding:8px;border-radius:10px;';wrap.append(el);(settingsTarget||settingsPanel).append(wrap);return el;};
  const preset=selectField('已保存的 API 预设');const presetName=field('预设名称','text','');
  function refreshPresets(){preset.replaceChildren(new Option('选择预设…',''));for(const p of saved.items)preset.add(new Option(p.name,p.id));preset.value=saved.active||'';presetName.value=saved.items.find(p=>p.id===saved.active)?.name||'';}refreshPresets();
  const url=field('API 基础地址（含 /v1，或完整 /chat/completions）','url',cfg.url),model=field('模型名称','text',cfg.model),key=field('API Key','password',sessionKey);key.autocomplete='off';
  const allowHttp=field('允许第三方 HTTP 接口（Key 和聊天内容将明文传输）','checkbox','');allowHttp.checked=!!cfg.allowHttp;
  const apiStream=field('流式接收回复（推荐；兼容非流式空回复的渠道）','checkbox','');apiStream.checked=cfg.apiStream!==false;
  const models=selectField('可用模型（保留服务商完整渠道名称）');models.add(new Option('点击下方拉取模型；也可手填模型名称',''));models.onchange=()=>{if(models.value)model.value=models.value;};
  let modelRequest=0;function clearModels(){modelRequest++;models.replaceChildren(new Option('地址或 Key 已变化，请重新拉取模型',''));}url.addEventListener('input',clearModels);key.addEventListener('input',clearModels);
  button('拉取模型',async()=>{requireActive();const base=endpoint(url.value.trim(),allowHttp.checked).replace(/\/chat\/completions$/,'/models');const token=key.value.trim();if(!token)throw Error('请先填写 API Key');const run=++modelRequest;const abort=new AbortController();apiRequests.add(abort);const timer=setTimeout(()=>abort.abort(),30000);try{status('正在拉取模型…');const response=await fetch(base,{headers:{Authorization:'Bearer '+token},credentials:'omit',redirect:'error',signal:abort.signal});if(!response.ok)throw await apiFailure(response,token);const data=await response.json();const ids=[...new Set((Array.isArray(data.data)?data.data:Array.isArray(data)?data:[]).map(x=>typeof x==='string'?x:x?.id).filter(x=>typeof x==='string'&&x.trim()))];if(run!==modelRequest||!models.isConnected)return;if(!ids.length)throw Error('接口未返回模型列表，请手动填写服务商的完整模型名称');models.replaceChildren(new Option('请选择模型',''));for(const id of ids)models.add(new Option(id,id));models.value=ids.includes(model.value)?model.value:'';status('已拉取 '+ids.length+' 个模型，请选择渠道后保存');}catch(e){if(e.name==='AbortError')throw Error('拉取模型超时');if(e.name==='TypeError')throw Error('无法拉取模型，请检查网络及服务商跨域设置');throw e;}finally{apiRequests.delete(abort);clearTimeout(timer);}});
  function writePresets(){localStorage.setItem(presetStore,JSON.stringify(saved));}
  preset.onchange=()=>{const p=saved.items.find(x=>x.id===preset.value);if(!p)return;invalidate();url.value=p.url;model.value=p.model;key.value=p.key;allowHttp.checked=!!p.allowHttp;apiStream.checked=p.apiStream!==false;presetName.value=p.name;clearModels();Object.assign(cfg,{url:p.url,model:p.model,allowHttp:!!p.allowHttp,apiStream:p.apiStream!==false});sessionKey=p.key;saved.active=p.id;writePresets();context().saveSettingsDebounced();status('已切换 API 预设：'+p.name);};
  button('保存 API 预设',async()=>{const name=presetName.value.trim();if(!name)throw Error('请填写预设名称');if(!key.value.trim())throw Error('请填写 API Key');await save();const existing=saved.items.find(p=>p.name===name);const p={id:existing?.id||newId(),name,url:cfg.url,model:cfg.model,key:sessionKey,allowHttp:!!cfg.allowHttp,apiStream:cfg.apiStream!==false};saved.items=saved.items.filter(x=>x.id!==p.id);saved.items.push(p);saved.active=p.id;writePresets();refreshPresets();status('API 预设已保存，下次打开会自动恢复');});
  section('手机外观','壁纸与APP图标',false);button('自定义壁纸与APP图标',()=>ui.openAppearance('phone'));
  section('02 · 聊天与同步','按你的节奏接收消息');const vision=field('图片与表情包视觉识别（需支持图片的模型）','checkbox','');vision.checked=!!cfg.stickerVision;const enabled=field('正文变量同步','checkbox','');enabled.checked=cfg.enabled;const proactive=field('允许角色随正文主动发消息','checkbox','');proactive.checked=cfg.proactive;
  section('03 · 上下文用量','调整阅读范围和回复长度');const chars=field('单轮正文最多携带字符','number',cfg.maxChars),history=field('手机上下文消息条数','number',cfg.history),tokens=field('单次输出 token 上限','number',cfg.maxTokens);
  const mailTokens=field('信件生成输出 token 上限','number',cfg.mailTokens||8000);
  const repairTokens=field('重 roll 整理输出 token 上限','number',cfg.repairTokens||12000);
  const loreChars=field('世界书内容上限（字符）','number',cfg.loreChars),requestTimeout=field('手机 API 最多等待秒数','number',cfg.requestTimeout||180);
  button('查看将发送给正文的手机记忆',()=>ui.showMemory(narrativeMemory(store(),ui.roles)+'\n'+publicMemory(store(),ui.roles)+actionMemory(store(),world(store()))));
  button('检查世界书连接',async()=>{await roleContext('',recentNarrative());status('世界书已读取，下次请求自动使用最新内容');});
  async function save(){if(url.value.trim())endpoint(url.value.trim(),allowHttp.checked);if(url.value.trim()&&!model.value.trim())throw Error('请填写模型');for(const [input,min,max] of [[chars,1000,40000],[history,0,60],[tokens,300,32768],[mailTokens,1000,32768],[repairTokens,1000,32768],[loreChars,2000,40000],[requestTimeout,30,600]])if(!Number.isInteger(+input.value)||+input.value<min||+input.value>max)throw Error('上下文或输出上限超出范围');invalidate();Object.assign(cfg,{url:url.value.trim(),allowHttp:allowHttp.checked,apiStream:apiStream.checked,model:model.value.trim(),enabled:enabled.checked,proactive:proactive.checked,stickerVision:vision.checked,maxChars:+chars.value,history:+history.value,maxTokens:+tokens.value,mailTokens:+mailTokens.value,repairTokens:+repairTokens.value,loreChars:+loreChars.value,requestTimeout:+requestTimeout.value});delete cfg.persona;delete cfg.profiles;sessionKey=key.value.trim();context().saveSettingsDebounced();installStatePrompt();status('设置已保存');}
  settingsTarget=null;const saveButton=button('保存设置',async()=>{await save();ui.home();schedule();});saveButton.className='jp-settings-save';section('04 · 同步工具','格式异常时，可先检查或重新整理');
  button('测试连接（会发送一条简短测试）',async()=>{await save();const value=await completion([{role:'user',content:'请只回复：连接成功'}]);status('API 已连接：'+value.slice(0,60));});
  button('查看最近手机请求诊断',()=>ui.showMemory(lastApiInfo?JSON.stringify(lastApiInfo,null,2):'本次打开尚未请求手机 API'));
  button('预设提示词 · 查看与编辑',()=>ui.openPromptPresets());
  button('带指令重 roll · 先预览',()=>ui.openReroll('全部'));
  section('高级同步修复','只在格式错误或网络中断时使用',false);
  button('精简重试本楼主动消息',async()=>{if(working||generation)throw Error('请等待当前生成结束');const s=store(),turn=s.turns.at(-1);if(!turn||turn.phoneDone)throw Error('本楼没有失败或待生成的主动消息');const run=epoch;working=true;controller=new AbortController();reducedRequest=true;try{await generateProactive(s,turn,extractNarrative(context().chat.at(-1)?.mes||''),controller.signal,run);if(run===epoch)await persist();}finally{reducedRequest=false;working=false;controller=null;if(pending){pending=false;schedule();}}});
  button('重新读取正文变量',async()=>{if(working||generation)throw Error('请等待正文或当前同步结束');await save();await syncNarrative(true);});

  const restoreInput=field('恢复手机聊天记录（导出的JSON存档）','file','');restoreInput.accept='.json,application/json';restoreInput.onchange=async()=>{const file=restoreInput.files[0];if(!file)return;try{requireSocialIdle();if(file.size>20*1024*1024)throw Error('存档文件过大');const original=JSON.parse((await file.text()).replace(/^\uFEFF/,'')),s=store(),run=epoch,candidates=recoveryCandidates(s,original,ui.roles);if(!candidates.length)throw Error('这份存档没有可恢复的新文字或语音记录');const snapshot=JSON.stringify(s);ui.reviewState(candidates.map(c=>c.message.text).join('\n\n'),'将恢复 '+candidates.length+' 条文字或语音气泡。仅补入缺失记录，金币、背包和当前日期不变。',async()=>{requireSocialIdle();if(run!==epoch||s!==store()||JSON.stringify(s)!==snapshot)throw Error('进度已变化，请重新选择存档');applyRecoveredMessages(s,candidates);render();await persist();status('已恢复 '+candidates.length+' 条手机气泡');},{title:'恢复聊天记录',readOnly:true});}catch(e){error(e);}finally{restoreInput.value='';}};
  button('导出本聊天存档',()=>{const blob=new Blob([JSON.stringify(store(),null,2)],{type:'application/json'});const a=document.createElement('a'),u=URL.createObjectURL(blob);a.href=u;a.download='junimo-pocket-save.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);});
  section('05 · 存档维护','手动校正或恢复备份',false);const edit=field('当前状态 JSON（可校正初始金币、日期、物品等）','textarea',JSON.stringify(currentId()?world(store()):ui.initial,null,2));
  button('应用校正并设为当前进度基线',async()=>{if(working)throw Error('请等待当前请求结束');const state=applyPatch(ui.initial,validatePatch(JSON.parse(edit.value)));invalidate();const s=store(),rows=await signatures();s.backup={base:s.base,turns:s.turns,manual:s.manual,draft:s.draft};s.base=state;s.baseSocialRevision=socialRevision(s);s.turns=rows.map(r=>({signature:r.signature,socialRevision:socialRevision(s),state:clone(state),messages:[]}));s.draft=null;await persist();render();status('已校正；旧状态已保留为上一次备份');});
  button('恢复上一次校正前的备份',async()=>{if(working)throw Error('请等待当前请求结束');const s=store();if(!s.backup)throw Error('没有备份');invalidate();const backup=s.backup;delete s.backup;Object.assign(s,backup);await persist();render();status('已恢复备份');});
  settingsTarget=null;settingsPanel.append(help);button('返回桌面',()=>ui.home());
}
let lastPhoneLayout,keyboardRestingTop,devicePreferences;
function resetBadgePosition(){requireActive();devicePreferences.reset(innerWidth);if(!phoneOpen)clamp();ui.toast('图标已归位 · 收起后回到右侧');}
function setNightMode(value){requireActive();devicePreferences.setNight(value);ui.updateTheme();}
function clamp(){if(!phoneOpen&&devicePreferences){const p=clampBadgePosition(devicePreferences.position(innerWidth),innerWidth,innerHeight);host.style.left=p.left+'px';host.style.top=p.top+'px';}const input=deepActiveElement(host),focused=!!input?.matches('input:not([type=checkbox]):not([type=radio]):not([type=file]):not([type=range]),textarea,[contenteditable=true]'),previous=lastPhoneLayout;lastPhoneLayout=phoneLayout({width:innerWidth,height:innerHeight,visibleHeight:globalThis.visualViewport?.height||innerHeight,focused},previous);const {scale,screenHeight,phoneHeight,availableHeight,keyboard}=lastPhoneLayout;if(keyboard&&!previous?.keyboard)keyboardRestingTop=parseFloat(host.style.top)||70;panel.style.setProperty('--jp-scale',scale);panel.style.setProperty('--jp-screen-height',screenHeight+'px');panel.style.height=(phoneOpen?phoneHeight:680*scale)+'px';const width=phoneOpen?350*scale:58;host.style.left=Math.max(6,Math.min(parseFloat(host.style.left)||innerWidth-width-18,innerWidth-width-6))+'px';const restingTop=keyboardRestingTop??(parseFloat(host.style.top)||70);
 const relativeBottom=focused?input.getBoundingClientRect().bottom-host.getBoundingClientRect().top:phoneHeight;host.style.top=(phoneOpen?phoneTop(lastPhoneLayout,restingTop,{offsetTop:globalThis.visualViewport?.offsetTop||0,focusedBottom:relativeBottom}):Math.max(6,Math.min(restingTop,availableHeight-64)))+'px';if(!keyboard)keyboardRestingTop=undefined;}
async function editPhoneMessage(id,text,reason){const s=store();editMessage(s,id,text,reason);invalidate();render();await persist();status('消息已编辑，手机记忆与编辑偏好已更新');}
async function recallPhoneMessage(id){const s=store();recallMessage(s,id);invalidate();render();await persist();status('消息已撤回');}
async function deletePhoneMessage(id){const s=store();if(!removeMessage(s,id))return;invalidate();render();await persist();status('消息已删除，手机记忆已更新');}
async function deleteFeedPost(id){const s=store();if(!removePost(s,id))return;invalidate();render();await persist();status('动态已删除，手机记忆已更新');}
function toggle(){if(!active())return;phoneOpen=!phoneOpen;panel.hidden=!phoneOpen;badge.hidden=phoneOpen;keyboardRestingTop=undefined;const p=devicePreferences.position(innerWidth);host.style.left=p.left+'px';host.style.top=p.top+'px';clamp();if(phoneOpen)render();}
function boot(){
  if(booted)return;booted=true;Object.assign(config(),{...defaults,...config()});
  if(!config().offeringSchemaVersion){const old=config().offeringRequirements||[];config().offeringRequirements=[...defaultOfferings,...old.filter(r=>!defaultOfferings.some(d=>d.bundle===r.bundle&&d.item===r.item))];config().offeringSchemaVersion=1;context().saveSettingsDebounced();}
  if(migrateOutputLimits(config()))context().saveSettingsDebounced();
  try{const saved=JSON.parse(localStorage.getItem('junimo_pocket_api_presets_v1')||'null');const p=saved?.items?.find(x=>x.id===saved.active);if(p){Object.assign(config(),{url:p.url,model:p.model,allowHttp:!!p.allowHttp,...(p.apiStream===undefined?{}:{apiStream:p.apiStream})});sessionKey=p.key||'';}}catch{}
  devicePreferences=createDevicePreferences(localStorage,config(),()=>context().saveSettingsDebounced());
  const badgeStart=devicePreferences.position(innerWidth);
  host=document.createElement('div');host.id='junimo-pocket-extension';host.style.cssText='position:fixed;z-index:2147483000;left:'+badgeStart.left+'px;top:'+badgeStart.top+'px';const shell=host.attachShadow({mode:'open'});
  shell.innerHTML='<style>:host{font:13px Microsoft YaHei,sans-serif}[hidden]{display:none!important}.panel{position:relative;width:calc(350px * var(--jp-scale,1));height:calc(680px * var(--jp-scale,1));background:transparent;border:0;padding:0;box-shadow:none}.phone{width:350px;transform:scale(var(--jp-scale,1));transform-origin:top left}.badge{position:relative;display:block;width:58px;height:58px;padding:0;border:0;background:transparent;cursor:grab;touch-action:none;filter:drop-shadow(0 4px 6px #52364155)}.badge img{display:block;width:100%;height:100%;object-fit:contain;pointer-events:none}.badge.unread:after{content:"";position:absolute;right:2px;top:3px;width:9px;height:9px;border-radius:50%;background:#e87698;border:2px solid white}.badge:active{transform:scale(.94)}</style><button class="badge" aria-label="打开月亮谷手机" title="点击打开 · 按住拖动"><img src="https://iili.io/ndvIRsV.png" alt=""></button><div class="panel" hidden><div class="phone"></div></div>';
  document.body.append(host);panel=shell.querySelector('.panel');badge=shell.querySelector('.badge');const root=shell.querySelector('.phone').attachShadow({mode:'open'});
  ui=mountPhone(root,{resetBadgePosition,setNightMode,nightMode:()=>devicePreferences.night(),async cropAvatar(source,owner){requireActive();const abort=new AbortController();apiRequests.add(abort);try{return await openAvatarCrop({root,source,owner,signal:abort.signal});}finally{apiRequests.delete(abort);}},completeTasks,questRows,questCompleted,createGroup,saveAppearance,saveChatCss,effectiveCssPresetId,scopedChatCss:(css,kind)=>scopedChatCss(css,document,kind),selectedMentionIds,newId,importPromptPreset,exportPromptPreset,calendarWithBirthdays,birthdaysToday,chatDisplayName,shouldMarkChatRead,isPhoneOpen:()=>phoneOpen,letterAttachments,saveChatNames,repairState,craftItem,startProject,claimOfferingRewards,animalData,careAnimal,reviewFarm,acceptFarmNarrative,collectionData,saveItemCategory,saveOfferings,submitOffering,publishComment,deleteFeedComment,editPhoneMessage,recallPhoneMessage,deletePhoneMessage,deleteFeedPost,communityData,publishPost,saveCommunitySettings,saveAvatar,saveFeedProfile,sendTransfer,claimTransfer,collectMail,readMail,acceptMail,deliverMail,getSocialState:()=>world(store()),getImage,saveImage,validateImageSource,stickerCatalog,getSticker,saveSticker,prepareSticker,async describeSticker(dataUrl,kind='sticker'){if(!config().stickerVision)throw Error('请先在设置开启图片与表情包视觉识别，并选择支持图片的模型');return completion([{role:'user',content:[{type:'text',text:prompt(kind==='image'?'describeImage':'describeSticker')},{type:'image_url',image_url:{url:dataUrl,detail:'low'}}]}]);},send,rerollChat,queueBubble,compose,openSettings,collapse:toggle,draftChanged:saveDraft,read(id){if(!currentId())return;const s=store();if(s.unread[id]){s.unread[id]=false;context().saveMetadataDebounced?.();badge.classList.toggle('unread',Object.values(s.unread).some(Boolean)||allLetters(s).some(l=>!l.read));}}});settingsPanel=ui.settingsBody;statusLine=ui.statusLine;
  let moved=false,drag;badge.onclick=()=>{if(!moved)toggle();};
  for(const handle of [badge,...ui.dragHandles]){handle.addEventListener('pointerdown',e=>{if(e.button!==0||e.target.closest('button:not(.badge)'))return;if(handle.classList.contains('device')&&e.target!==handle)return;moved=false;drag={x:e.clientX,y:e.clientY,left:parseFloat(host.style.left),top:parseFloat(host.style.top)};handle.setPointerCapture(e.pointerId);});handle.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.abs(dx)+Math.abs(dy)>4)moved=true;if(moved){host.style.left=drag.left+dx+'px';host.style.top=drag.top+dy+'px';if(!phoneOpen)devicePreferences.savePosition(clampBadgePosition({left:drag.left+dx,top:drag.top+dy},innerWidth,innerHeight));clamp();}});handle.addEventListener('pointerup',()=>{if(drag){if(moved&&!phoneOpen)devicePreferences.savePosition({left:parseFloat(host.style.left),top:parseFloat(host.style.top)});drag=null;}});handle.addEventListener('pointercancel',()=>{drag=null;});}
  mountExtensionSwitch({document,active,set:masterSwitch.set,openSettings(){if(!phoneOpen)toggle();openSettings();}});if(active())stateWatcher=watchStateBlocks();else{host.hidden=true;host.style.display='none';}loadStickers().then(()=>render()).catch(e=>status(e.message));addEventListener('resize',clamp);globalThis.visualViewport?.addEventListener('resize',clamp);globalThis.visualViewport?.addEventListener('scroll',clamp);host.shadowRoot.addEventListener('focusin',clamp);host.shadowRoot.addEventListener('focusout',()=>requestAnimationFrame(clamp));clamp();render();storeRef=context().chatMetadata;
  const c=context(),events=c.eventTypes??c.event_types;const on=(name,fn)=>{if(events[name])c.eventSource.on(events[name],(...args)=>{if(active()||name.startsWith('GENERATION_'))fn(...args);});};
  on('CHAT_CHANGED',()=>{invalidate();generation=false;storeRef=context().chatMetadata;lastStoryKeys=context().chat.map(storyKey);ui.closeRoom();ui.home();render();status('已切换对话');ui.setLoreStatus('下次请求将检查当前卡的世界书绑定');installStatePrompt();schedule();});
  for(const name of ['WORLDINFO_UPDATED','WORLDINFO_SETTINGS_UPDATED','CHARACTER_EDITED'])on(name,()=>{ui.setLoreStatus('设定已变化，下次请求读取更新后的世界书');});
  on('GENERATION_AFTER_COMMANDS',(type,options,dryRun)=>{if(!dryRun)installStatePrompt(type);});
  on('GENERATION_STARTED',(type,options,dryRun)=>{if(!active()){if(!dryRun&&type!=='quiet'&&type!=='impersonate')generation=true;installStatePrompt(type);return;}if(dryRun||type==='quiet'||type==='impersonate'){installStatePrompt(type);return;}invalidate();generation=true;try{const s=store();if(['regenerate','swipe'].includes(type)&&!context().chat.at(-1)?.is_user){rollback(s,context().chat.length-1);render();context().saveMetadataDebounced?.();}s.pendingNarrativeRevision=socialRevision(s);s.pendingNarrativeDraft=clone(s.draft);s.pendingNarrativeBase=world(s);}catch{}installStatePrompt(type);status('正文正在生成，完成后自动同步');});on('GENERATION_ENDED',()=>{generation=false;schedule();});on('GENERATION_STOPPED',()=>{generation=false;schedule();});
  for(const name of ['MESSAGE_EDITED','MESSAGE_UPDATED','MESSAGE_DELETED'])on(name,contentChanged);
  on('MESSAGE_SWIPED',index=>{if(!generation){try{const id=Number(index);if(Number.isInteger(id)&&id>=0){rollback(store(),id);render();}}catch{}}contentChanged();});
  on('CHARACTER_MESSAGE_RENDERED',()=>{if(!generation)contentChanged();schedule();});on('MESSAGE_RECEIVED',schedule);installStatePrompt();schedule();
}
if(globalThis.SillyTavern?.getContext){const c=context(),e=c.eventTypes??c.event_types;if(e.APP_READY)c.eventSource.on(e.APP_READY,()=>{setTimeout(boot,0);});else boot();}
