import {allPhoneMessages,phoneTimeline,followupInstruction} from './phone-memory.js';
import {formatState} from './text-state.js';
import {chatInstruction,parseChatReply,parseFollowups,textingStyle} from './chat-protocol.js';
import {readStateBlock,statePrompt,parseBubbles} from './protocol.js';
import {mountPhone} from './phone.js';
import {readBoundLore,resolveBinding,selectLore} from './lore.js';
import {clone,applyPatch,validatePatch,parseResult,fingerprint,reconcile,world,endpoint,migrateDemo} from './core.js';
const KEY='junimo_pocket_v1';
const context=()=>globalThis.SillyTavern.getContext();
const defaults={enabled:true,proactive:true,allowHttp:false,url:'',model:'',maxChars:12000,history:16,maxTokens:2200,loreChars:18000,boundAvatar:'',left:null,top:70};
let ui,host,panel,badge,statusLine,settingsPanel,sessionKey='',generation=false,epoch=0,controller=null,working=false,pending=false,timer,booted=false,phoneOpen=false,storeRef;
const config=()=>context().extensionSettings[KEY]??(context().extensionSettings[KEY]=clone(defaults));
const currentId=()=>String(context().getCurrentChatId?.()??context().chatId??'');
function store(){if(!currentId())throw Error('请先打开一段角色对话');const s=context().chatMetadata[KEY]??(context().chatMetadata[KEY]={version:3,base:clone(ui.initial),turns:[],manual:[],unread:{},draft:null});if(s.version<3){s.legacyBackup=clone({base:s.base,turns:s.turns,manual:s.manual});s.version=3;s.base=clone(ui.initial);s.turns=[];s.started=false;s.draft=null;context().saveMetadataDebounced?.();}return s;}
function status(text){if(statusLine)statusLine.textContent=text;ui?.setStatus(text);}
function error(e){if(e.name==='AbortError')return;status('未完成：'+e.message);ui?.toast(e.message);}
async function apiFailure(response,key=''){
  let detail='';try{const body=await response.json();detail=body.error?.message||body.message||'';}catch{}
  if(typeof detail!=='string')detail='';if(key)detail=detail.split(key).join('[Key 已隐藏]');
  const hint=response.status===503?'当前服务或模型渠道暂不可用，请切换模型渠道或稍后重试':response.status===401?'Key 无效或已过期':response.status===429?'请求受限或额度不足':'请检查接口地址和模型';
  return Error('API 返回 HTTP '+response.status+'；'+hint+(detail?'。服务商：'+detail.slice(0,350):''));
}
async function persist(){const c=context();await c.saveMetadata();}
function threads(s){const all=allPhoneMessages(s);const out={};for(const m of all)(out[m.roleId]??=[]).push(m);return out;}
function render(){try{const s=store();ui.update(world(s),threads(s),s.unread,s.draft);badge.classList.toggle('unread',Object.values(s.unread).some(Boolean));}catch{ui.update(ui.initial,{},{});}}
function saveDraft(draft){if(!currentId())return;const s=store();s.draft=draft.actions.length?draft:null;context().saveMetadataDebounced?.();}
function compose(text){const input=document.querySelector('#send_textarea');if(!input)throw Error('找不到酒馆输入框');input.value=(input.value?input.value+'\n':'')+text;input.dispatchEvent(new Event('input',{bubbles:true}));input.focus();}
function extractNarrative(raw){let text=String(raw||'');if(/<(?:html|body|div|p|style|script)\b/i.test(text)){const doc=new DOMParser().parseFromString(text,'text/html');doc.querySelectorAll('script,style,svg').forEach(el=>el.remove());doc.querySelectorAll('p,div,br,tr,li').forEach(el=>el.append('\n'));text=doc.body.textContent||text;}const limit=config().maxChars;return text.length<=limit?text:text.slice(0,Math.floor(limit*.4))+'\n[中段超出正文长度上限]\n'+text.slice(-Math.floor(limit*.6));}
function recentNarrative(limit=config().maxChars){return context().chat.filter(m=>!m.is_system).slice(-8).map(m=>(m.is_user?'用户':'正文')+'：'+m.mes).join('\n').slice(-limit);}
async function roleContext(roleName='',narrative='',signal){const c=context(),cfg=config(),run=epoch;const book=await readBoundLore(c,cfg.boundAvatar,signal);if(run!==epoch)throw new DOMException('对话已变化','AbortError');if(!cfg.boundAvatar){cfg.boundAvatar=book.avatar;c.saveSettingsDebounced();}const result=selectLore(book.entries,{roleName,narrative,roles:ui.roles,budget:cfg.loreChars,user:c.name1,character:c.name2});if(!result.selected.length)throw Error('绑定世界书中没有可用的人设或世界规则条目');ui.setLoreStatus('已连接：'+book.name+' · 本次选取 '+result.selected.length+' / '+result.total+' 条'+(result.trimmed?'（部分内容受长度限制）':''));return JSON.stringify({user:c.name1,character:c.name2,worldbook:book.name,entries:result.selected});}
async function completion(messages,signal){
  const cfg=config();if(!cfg.url||!cfg.model||!sessionKey)throw Error('请先在手机设置填写 API 地址、模型和本次会话 Key');
  const url=endpoint(cfg.url,cfg.allowHttp);if(location.protocol==='https:'&&url.startsWith('http:'))throw Error('当前酒馆使用 HTTPS，浏览器可能阻止 HTTP 接口。请使用服务商的 HTTPS 地址或自行配置 HTTPS 反向代理。');const timeout=new AbortController();const forward=()=>timeout.abort();signal?.addEventListener('abort',forward,{once:true});if(signal?.aborted)timeout.abort();const id=setTimeout(()=>timeout.abort(),90000);
  try{const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+sessionKey},body:JSON.stringify({model:cfg.model,messages,stream:false,max_tokens:cfg.maxTokens,temperature:0.5}),signal:timeout.signal,credentials:'omit',redirect:'error'});if(!response.ok)throw await apiFailure(response,sessionKey);const data=await response.json();if(data.choices?.[0]?.finish_reason==='length')throw Error('回复被截断，请增加输出上限或缩小状态');const text=data.choices?.[0]?.message?.content;if(typeof text!=='string'||!text.trim())throw Error('API 返回了空回复');return text;}catch(e){if(e.name==='TypeError')throw Error('无法连接 API（网络或 CORS 限制）。服务商需允许酒馆网页跨域访问。');if(e.name==='AbortError'&&!signal?.aborted)throw Error('API 请求超时，未改动状态');throw e;}finally{clearTimeout(id);signal?.removeEventListener('abort',forward);}
}

function installStatePrompt(){const c=context();try{resolveBinding(c,config().boundAvatar);const state=currentId()?world(store()):ui.initial;c.setExtensionPrompt?.('junimo_pocket_state',config().enabled?statePrompt(state,ui.roles,ui.mapAnchors,!store().turns.some(t=>t.hasState)):'',1,0,false,0);}catch{c.setExtensionPrompt?.('junimo_pocket_state','',1,0,false,0);}}
async function signatures(){return Promise.all(context().chat.map(async(m,index)=>({index,message:m,signature:await fingerprint(JSON.stringify([m.is_user,m.is_system,m.name,m.mes,m.swipe_id]))})));}
async function proactive(s,turn,narrative,signal,run){
 if(!config().proactive||turn.phoneDone||!sessionKey||!config().url)return;
 try{const background=await roleContext('',narrative,signal);const raw=await completion([{role:'system',content:textingStyle+'你是手机聊天消息调度员。角色正在用手机给用户发消息，不是面对面说话。依据本轮正文与人设，最多让两位有合理联系理由的角色发消息。每条消息只能是对应roleId角色本人发言，私聊禁止混入其他角色署名台词，莱恩与莱尔必须独立。每人可发1到4个短气泡，线上聊天口吻自然随意，按人设和心情使用标点，不必每个气泡末尾加句号，可以不带结尾标点；禁止旁白、动作、替用户说话。没有理由则messages为空。只能返回JSON：{"messages":[{"roleId":"01","bubbles":["短消息","补充一句"]}]}。按共享时间线的order先后阅读，visibleTo标明谁看过消息，不能把他人私聊当作自己的记忆。不要修改世界状态。'},{role:'user',content:JSON.stringify({roles:ui.roles,background,narrative,sharedTimeline:phoneTimeline(s,{members:ui.roles.map(r=>r.id)},ui.roles,80),state:world(s)})}],signal);
 const result=JSON.parse(raw.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,''));if(!Array.isArray(result.messages)||result.messages.length>2)throw Error('主动消息格式无效');
 const incoming=[];for(const item of result.messages){if(!ui.roles.some(r=>r.id===item.roleId))throw Error('主动消息角色无效');for(const bubble of parseChatReply(JSON.stringify({bubbles:item.bubbles}),ui.roles.find(r=>r.id===item.roleId),ui.roles))incoming.push({roleId:item.roleId,...bubble,from:'role',created:Date.now()+incoming.length,time:world(s).calendar.time});}
 if(run!==epoch)return;turn.phoneDone=true;for(const m of incoming){if(run!==epoch)return;turn.messages.push(m);s.unread[m.roleId]=true;render();await persist();await new Promise(r=>setTimeout(r,450));}if(incoming.length)ui.notify('收到 '+incoming.length+' 条手机消息');
 }catch(e){if(e.name!=='AbortError'){turn.phoneError=e.message;status('变量已更新；主动消息未完成：'+e.message);}}
}
async function syncNarrative(forceLatest=false){
 if(working){pending=true;return;}if(!currentId()||generation)return;working=true;pending=false;const run=epoch,id=currentId();controller=new AbortController();
 try{const s=store(),rows=await signatures();if(run!==epoch)return;let keep=reconcile(s,rows.map(r=>r.signature));if(!config().enabled&&!forceLatest){installStatePrompt();return;}resolveBinding(context(),config().boundAvatar);
 if(!s.started){const last=rows.findLastIndex(r=>!r.message.is_user&&!r.message.is_system);for(let i=0;i<Math.max(last,0);i++)s.turns.push({signature:rows[i].signature,state:clone(s.base),messages:[],hasState:false});s.started=true;keep=s.turns.length;}
 if(forceLatest){const last=rows.findLastIndex(r=>!r.message.is_user&&!r.message.is_system);if(last>=0){s.turns.splice(last);keep=last;}}
 for(let i=keep;i<rows.length;i++){
   if(run!==epoch||id!==currentId()||generation)return;const {message:m,signature}=rows[i];let state=world(s),hasState=false,changed=[],warnings=[];
   if(!m.is_user&&!m.is_system&&m.mes?.trim()){
     const parsed=readStateBlock(m.mes,state,{roles:ui.roles,anchors:ui.mapAnchors,initial:!s.turns.some(t=>t.hasState)});
     if(parsed){state=parsed.state;changed=Object.keys(parsed.patch);warnings=parsed.warnings||[];hasState=true;}else status('本轮正文缺少变量块：请重新生成，手机不会猜测数值');
   }
   const turn={signature,state,messages:[],hasState};s.turns.push(turn);if(hasState){s.draft=null;delete s.needsRefresh;}
   render();await persist();installStatePrompt();
   if(hasState){const names={gold:'金币',calendar:'日历',inventory:'背包',plots:'农田',locations:'地图',quests:'任务',calendarEvents:'日程',animals:'动物',buildings:'建筑',relationships:'好感度',notes:'农场记录'};status('正文变量已更新：'+(changed.map(k=>names[k]||k).join('、')||'本轮无变化')+(warnings.length?'；待修正：'+warnings.join('；'):''));await proactive(s,turn,extractNarrative(m.mes.split(/<junimo-state>|【手机状态】/)[0]),controller.signal,run);}
 }
 }catch(e){error(e);}finally{working=false;controller=null;if(pending){pending=false;schedule();}}
}
function schedule(){clearTimeout(timer);timer=setTimeout(()=>syncNarrative(),600);}
function invalidate(){ui?.clearTyping();epoch++;controller?.abort();pending=true;}

function stamp(s){const d=world(s).calendar;return {created:Math.max(Date.now(),(allPhoneMessages(s).at(-1)?.created||0)+1),time:d.time,storyDate:[d.year,d.season,d.day].join('/')};}
async function queueBubble(role,value){const text=typeof value==='string'?value:value?.text,type=typeof value==='string'?'text':value?.type||'text';if(typeof text!=='string'||!text.trim())return;if(text.length>4000||!['text','voice'].includes(type))throw Error('消息格式无效或超过4000字');const s=store();s.manual.push({id:crypto.randomUUID(),roleId:role.id,from:'me',text:text.trim(),type,...(type==='voice'?{duration:Math.max(1,Math.min(180,Math.ceil(text.trim().length/4)))}:{}),...stamp(s),status:'queued'});render();await persist();}
async function send(role,text=''){
 if(text.trim())await queueBubble(role,text);if(working)throw Error('正在处理手机消息，请稍后点击发送');
 const s=store(),run=epoch,id=currentId(),cfg=config();const queued=s.manual.filter(m=>m.roleId===role.id&&m.from==='me'&&['queued','failed'].includes(m.status));if(!queued.length)throw Error('请先发一条消息');
 working=true;controller=new AbortController();queued.forEach(m=>m.status='sending');ui.setTyping(role.id,role.members?'群友正在输入':'对方正在输入');render();status(role.name+' 正在输入…');
 try{const limit=queued.at(-1).created,timeline=phoneTimeline(s,role,ui.roles,Math.max(80,(cfg.history||16)*4),limit),narrative=recentNarrative();const background=await roleContext(role.members?role.members.map(id=>ui.roles.find(r=>r.id===id)?.name).join('、'):role.name,queued.map(m=>m.text).join('\n'),controller.signal);
 const response=await completion([{role:'system',content:chatInstruction(role,ui.roles)+'\n'+followupInstruction(role,ui.roles)+'\n双方可能不在同一个地方，不能知道自己无理由知道的事。综合当前用户连续气泡一起回复。已完成的旧消息只作记忆，不要重新回复。世界书：'+background+'\n当前正文：'+narrative},{role:'user',content:JSON.stringify({currentThread:role.id,sharedTimeline:timeline,pendingMessages:queued.map(m=>({type:m.type||'text',text:m.text,order:m.created})),request:'回复当前聊天待回复消息，可按合理动机额外发跨聊天主动消息。'})}],controller.signal);
 const bubbles=parseChatReply(response,role,ui.roles);let followups=[],followupError='';try{followups=parseFollowups(response,role,ui.roles);}catch(e){followupError=e.message;}if(run!==epoch||id!==currentId())throw new DOMException('对话已切换','AbortError');queued.forEach(m=>m.status='sent');
 for(const bubble of bubbles){if(run!==epoch)break;ui.setTyping(role.id,bubble.type==='voice'?'对方正在录制语音':'对方正在输入');await new Promise(r=>setTimeout(r,Math.min(1200,350+bubble.text.length*15)));if(run!==epoch)break;s.manual.push({id:crypto.randomUUID(),roleId:role.id,from:'role',...bubble,...stamp(s)});render();await persist();}
 ui.setTyping(role.id,'');for(const bubble of followups){if(run!==epoch)break;ui.setTyping(bubble.roleId,bubble.type==='voice'?'正在录制语音':'正在输入');await new Promise(r=>setTimeout(r,500));ui.setTyping(bubble.roleId,'');if(run!==epoch)break;s.manual.push({id:crypto.randomUUID(),from:'role',...bubble,...stamp(s)});s.unread[bubble.roleId]=true;render();await persist();}if(followups.length)ui.notify('其他聊天收到 '+followups.length+' 条消息');status('手机消息已保存'+(followupError?'；跨聊天消息未发送：'+followupError:''));
 }catch(e){queued.forEach(m=>{if(m.status==='sending')m.status='failed';});if(run===epoch){render();await persist();}throw e;}finally{ui.clearTyping();working=false;controller=null;if(pending){pending=false;schedule();}}
}
async function repairState(){
 if(working||generation)throw Error('请等待正文或当前请求结束');const s=store(),run=epoch,id=currentId(),rows=await signatures(),signature=JSON.stringify(rows.map(r=>r.signature)),base=world(s);working=true;controller=new AbortController();status('AI 正在整理变量，尚未应用…');
 try{const narrative=recentNarrative(),background=await roleContext('',narrative,controller.signal);const raw=await completion([{role:'system',content:'你是游戏存档校对员。根据正文与世界书修复手机变量，不写故事，只输出手机文字状态摘要。谨慎区分计划与已执行，播种与成熟，不得凭空增加物品。'+statePrompt(base,ui.roles,ui.mapAnchors,!s.turns.some(t=>t.hasState))},{role:'user',content:'世界书：'+background+'\n最近正文：'+narrative}],controller.signal);if(run!==epoch||id!==currentId())throw new DOMException('对话已变化','AbortError');const parsed=readStateBlock(raw,base,{roles:ui.roles,anchors:ui.mapAnchors,initial:!s.turns.some(t=>t.hasState)});if(!parsed)throw Error('AI 没有返回文字状态摘要，未改动变量');const names={calendar:'时间',gold:'金币',inventory:'背包',plots:'农田',locations:'位置',relationships:'好感',quests:'任务',animals:'动物',buildings:'建筑',calendarEvents:'日程',notes:'记录',capacity:'容量'};const changed=Object.keys(parsed.patch).filter(k=>JSON.stringify(base[k])!==JSON.stringify(parsed.state[k])).map(k=>names[k]||k);status('整理完成，等待你核对并确认');
 ui.reviewState(raw,'预计更新：'+(changed.join('、')||'无差异')+'。下方可直接修改；取消不会改变存档。'+(parsed.warnings?.length?'待修正：'+parsed.warnings.join('；'):''),async text=>{if(working||generation)throw Error('请等待当前请求结束再确认');if(run!==epoch||id!==currentId()||signature!==JSON.stringify((await signatures()).map(r=>r.signature)))throw Error('正文或对话已变化，请取消后重新整理');if(JSON.stringify(world(s))!==JSON.stringify(base))throw Error('手机状态已变化，请重新整理');const value=readStateBlock(text,base,{roles:ui.roles,anchors:ui.mapAnchors,initial:!s.turns.some(t=>t.hasState)});if(!value)throw Error('请保留手机状态的开始和结束标记');s.backup=clone({base:s.base,turns:s.turns,manual:s.manual,draft:s.draft});s.turns=rows.map((r,i)=>({...s.turns[i],signature:r.signature,state:clone(i===rows.length-1?value.state:s.turns[i]?.state||s.base),messages:s.turns[i]?.messages||[],hasState:i===rows.length-1||!!s.turns[i]?.hasState}));if(!rows.length)s.base=value.state;s.draft=null;s.started=true;await persist();render();installStatePrompt();status('已按确认结果更新变量');});
 }finally{working=false;controller=null;if(pending){pending=false;schedule();}}
}
function field(label,type,value){const wrap=document.createElement('label');wrap.textContent=label;const input=document.createElement(type==='textarea'?'textarea':'input');if(type!=='textarea')input.type=type;input.value=value??'';wrap.append(input);settingsPanel.append(wrap);return input;}
function button(label,callback){const b=document.createElement('button');b.textContent=label;b.type='button';b.onclick=async()=>{b.disabled=true;try{await callback();}catch(e){error(e);}finally{b.disabled=false;}};settingsPanel.append(b);return b;}
function openSettings(){
  settingsPanel.replaceChildren();ui.showSettings();const cfg=config();const heading=document.createElement('h3');heading.textContent='连接与同步';settingsPanel.append(heading);
  const help=document.createElement('p');help.textContent='正文变量读取末尾的简短文字状态摘要，不消耗独立 API。独立 API 用于手机私聊、群聊和主动消息；也可手动整理变量，核对后确认应用。保存 API 预设后，地址、Key 和模型会保存在本机此浏览器，刷新后可继续使用；不会包含在聊天存档导出中。HTTP 会明文传输 Key 和聊天内容。';settingsPanel.append(help);
  const loreInfo=document.createElement('p');loreInfo.className='jp-lore-info';settingsPanel.append(loreInfo);try{loreInfo.textContent='绑定世界书：'+resolveBinding(context(),cfg.boundAvatar).name+' · 每次请求前重新读取';}catch(e){loreInfo.textContent=e.message;}
  const presetStore='junimo_pocket_api_presets_v1';let saved={items:[],active:''};try{const value=JSON.parse(localStorage.getItem(presetStore)||'null');if(Array.isArray(value?.items))saved=value;}catch{}
  const selectField=label=>{const wrap=document.createElement('label');wrap.textContent=label;const el=document.createElement('select');el.style.cssText='display:block;width:100%;padding:8px;border-radius:10px;';wrap.append(el);settingsPanel.append(wrap);return el;};
  const preset=selectField('已保存的 API 预设');const presetName=field('预设名称','text','');
  function refreshPresets(){preset.replaceChildren(new Option('选择预设…',''));for(const p of saved.items)preset.add(new Option(p.name,p.id));preset.value=saved.active||'';presetName.value=saved.items.find(p=>p.id===saved.active)?.name||'';}refreshPresets();
  const url=field('API 基础地址（含 /v1，或完整 /chat/completions）','url',cfg.url),model=field('模型名称','text',cfg.model),key=field('API Key','password',sessionKey);key.autocomplete='off';
  const allowHttp=field('允许第三方 HTTP 接口（Key 和聊天内容将明文传输）','checkbox','');allowHttp.checked=!!cfg.allowHttp;
  const models=selectField('可用模型（保留服务商完整渠道名称）');models.add(new Option('点击下方拉取模型；也可手填模型名称',''));models.onchange=()=>{if(models.value)model.value=models.value;};
  let modelRequest=0;function clearModels(){modelRequest++;models.replaceChildren(new Option('地址或 Key 已变化，请重新拉取模型',''));}url.addEventListener('input',clearModels);key.addEventListener('input',clearModels);
  button('拉取模型',async()=>{const base=endpoint(url.value.trim(),allowHttp.checked).replace(/\/chat\/completions$/,'/models');const token=key.value.trim();if(!token)throw Error('请先填写 API Key');const run=++modelRequest;const abort=new AbortController(),timer=setTimeout(()=>abort.abort(),30000);try{status('正在拉取模型…');const response=await fetch(base,{headers:{Authorization:'Bearer '+token},credentials:'omit',redirect:'error',signal:abort.signal});if(!response.ok)throw await apiFailure(response,token);const data=await response.json();const ids=[...new Set((Array.isArray(data.data)?data.data:Array.isArray(data)?data:[]).map(x=>typeof x==='string'?x:x?.id).filter(x=>typeof x==='string'&&x.trim()))];if(run!==modelRequest||!models.isConnected)return;if(!ids.length)throw Error('接口未返回模型列表，请手动填写服务商的完整模型名称');models.replaceChildren(new Option('请选择模型',''));for(const id of ids)models.add(new Option(id,id));models.value=ids.includes(model.value)?model.value:'';status('已拉取 '+ids.length+' 个模型，请选择渠道后保存');}catch(e){if(e.name==='AbortError')throw Error('拉取模型超时');if(e.name==='TypeError')throw Error('无法拉取模型，请检查网络及服务商跨域设置');throw e;}finally{clearTimeout(timer);}});
  function writePresets(){localStorage.setItem(presetStore,JSON.stringify(saved));}
  preset.onchange=()=>{const p=saved.items.find(x=>x.id===preset.value);if(!p)return;invalidate();url.value=p.url;model.value=p.model;key.value=p.key;allowHttp.checked=!!p.allowHttp;presetName.value=p.name;clearModels();Object.assign(cfg,{url:p.url,model:p.model,allowHttp:!!p.allowHttp});sessionKey=p.key;saved.active=p.id;writePresets();context().saveSettingsDebounced();status('已切换 API 预设：'+p.name);};
  button('保存 API 预设',async()=>{const name=presetName.value.trim();if(!name)throw Error('请填写预设名称');if(!key.value.trim())throw Error('请填写 API Key');await save();const existing=saved.items.find(p=>p.name===name);const p={id:existing?.id||crypto.randomUUID(),name,url:cfg.url,model:cfg.model,key:sessionKey,allowHttp:!!cfg.allowHttp};saved.items=saved.items.filter(x=>x.id!==p.id);saved.items.push(p);saved.active=p.id;writePresets();refreshPresets();status('API 预设已保存，下次打开会自动恢复');});
  const enabled=field('正文变量同步','checkbox','');enabled.checked=cfg.enabled;const proactive=field('允许角色随正文主动发消息','checkbox','');proactive.checked=cfg.proactive;
  const chars=field('单轮正文最多携带字符','number',cfg.maxChars),history=field('手机上下文消息条数','number',cfg.history),tokens=field('单次输出 token 上限','number',cfg.maxTokens);
  const loreChars=field('世界书内容上限（字符）','number',cfg.loreChars);
  button('检查世界书连接',async()=>{await roleContext('',recentNarrative());status('世界书已读取，下次请求自动使用最新内容');});
  async function save(){if(url.value.trim())endpoint(url.value.trim(),allowHttp.checked);if(url.value.trim()&&!model.value.trim())throw Error('请填写模型');for(const [input,min,max] of [[chars,1000,40000],[history,0,60],[tokens,300,12000],[loreChars,2000,40000]])if(!Number.isInteger(+input.value)||+input.value<min||+input.value>max)throw Error('上下文或输出上限超出范围');invalidate();Object.assign(cfg,{url:url.value.trim(),allowHttp:allowHttp.checked,model:model.value.trim(),enabled:enabled.checked,proactive:proactive.checked,maxChars:+chars.value,history:+history.value,maxTokens:+tokens.value,loreChars:+loreChars.value});delete cfg.persona;delete cfg.profiles;sessionKey=key.value.trim();context().saveSettingsDebounced();installStatePrompt();status('设置已保存');}
  button('保存设置',async()=>{await save();ui.home();schedule();});
  button('测试连接（会发送一条简短测试）',async()=>{await save();const value=await completion([{role:'user',content:'请只回复：连接成功'}]);status('API 已连接：'+value.slice(0,60));});
  button('重新读取正文变量',async()=>{if(working||generation)throw Error('请等待正文或当前同步结束');await save();await syncNarrative(true);});
  button('AI 重新整理变量（先预览）',async()=>{await save();await repairState();});
  button('导出本聊天存档',()=>{const blob=new Blob([JSON.stringify(store(),null,2)],{type:'application/json'});const a=document.createElement('a'),u=URL.createObjectURL(blob);a.href=u;a.download='junimo-pocket-save.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);});
  const edit=field('当前状态 JSON（可校正初始金币、日期、物品等）','textarea',JSON.stringify(currentId()?world(store()):ui.initial,null,2));
  button('应用校正并设为当前进度基线',async()=>{if(working)throw Error('请等待当前请求结束');const state=applyPatch(ui.initial,validatePatch(JSON.parse(edit.value)));invalidate();const s=store(),rows=await signatures();s.backup={base:s.base,turns:s.turns,manual:s.manual,draft:s.draft};s.base=state;s.turns=rows.map(r=>({signature:r.signature,state:clone(state),messages:[]}));s.draft=null;await persist();render();status('已校正；旧状态已保留为上一次备份');});
  button('恢复上一次校正前的备份',async()=>{if(working)throw Error('请等待当前请求结束');const s=store();if(!s.backup)throw Error('没有备份');invalidate();const backup=s.backup;delete s.backup;Object.assign(s,backup);await persist();render();status('已恢复备份');});
  button('返回桌面',()=>ui.home());
}
function clamp(){const scale=Math.max(.2,Math.min(1,(innerHeight-24)/680,(innerWidth-24)/350));panel.style.setProperty('--jp-scale',scale);const width=phoneOpen?350*scale:58,height=phoneOpen?680*scale:58;host.style.left=Math.max(6,Math.min(parseFloat(host.style.left)||innerWidth-width-18,innerWidth-width-6))+'px';host.style.top=Math.max(6,Math.min(parseFloat(host.style.top)||70,innerHeight-height-6))+'px';}
function toggle(){phoneOpen=!phoneOpen;panel.hidden=!phoneOpen;badge.hidden=phoneOpen;clamp();}
function boot(){
  if(booted)return;booted=true;Object.assign(config(),{...defaults,...config()});
  try{const saved=JSON.parse(localStorage.getItem('junimo_pocket_api_presets_v1')||'null');const p=saved?.items?.find(x=>x.id===saved.active);if(p){Object.assign(config(),{url:p.url,model:p.model,allowHttp:!!p.allowHttp});sessionKey=p.key||'';}}catch{}
  host=document.createElement('div');host.id='junimo-pocket-extension';host.style.cssText='position:fixed;z-index:2147483000;left:'+(config().left??Math.max(6,innerWidth-76))+'px;top:'+config().top+'px';const shell=host.attachShadow({mode:'open'});
  shell.innerHTML='<style>:host{font:13px Microsoft YaHei,sans-serif}[hidden]{display:none!important}.panel{position:relative;width:calc(350px * var(--jp-scale,1));height:calc(680px * var(--jp-scale,1));background:transparent;border:0;padding:0;box-shadow:none}.phone{width:350px;transform:scale(var(--jp-scale,1));transform-origin:top left}.badge{position:relative;display:block;width:58px;height:58px;padding:0;border:0;background:transparent;cursor:grab;touch-action:none;filter:drop-shadow(0 4px 6px #52364155)}.badge img{display:block;width:100%;height:100%;object-fit:contain;pointer-events:none}.badge.unread:after{content:"";position:absolute;right:2px;top:3px;width:9px;height:9px;border-radius:50%;background:#e87698;border:2px solid white}.badge:active{transform:scale(.94)}</style><button class="badge" aria-label="打开月亮谷手机" title="点击打开 · 按住拖动"><img src="https://iili.io/ndvIRsV.png" alt=""></button><div class="panel" hidden><div class="phone"></div></div>';
  document.body.append(host);panel=shell.querySelector('.panel');badge=shell.querySelector('.badge');const root=shell.querySelector('.phone').attachShadow({mode:'open'});
  ui=mountPhone(root,{send,queueBubble,compose,openSettings,collapse:toggle,draftChanged:saveDraft,read(id){if(!currentId())return;const s=store();if(s.unread[id]){s.unread[id]=false;context().saveMetadataDebounced?.();}}});settingsPanel=ui.settingsBody;statusLine=ui.statusLine;
  let moved=false,drag;badge.onclick=()=>{if(!moved)toggle();};
  for(const handle of [badge,...ui.dragHandles]){handle.addEventListener('pointerdown',e=>{if(e.button!==0||e.target.closest('button:not(.badge)'))return;if(handle.classList.contains('device')&&e.target!==handle)return;moved=false;drag={x:e.clientX,y:e.clientY,left:parseFloat(host.style.left),top:parseFloat(host.style.top)};handle.setPointerCapture(e.pointerId);});handle.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.abs(dx)+Math.abs(dy)>4)moved=true;if(moved){host.style.left=drag.left+dx+'px';host.style.top=drag.top+dy+'px';clamp();}});handle.addEventListener('pointerup',()=>{if(drag){drag=null;Object.assign(config(),{left:parseFloat(host.style.left),top:parseFloat(host.style.top)});context().saveSettingsDebounced();}});handle.addEventListener('pointercancel',()=>{drag=null;});}
  addEventListener('resize',clamp);clamp();render();storeRef=context().chatMetadata;
  const c=context(),events=c.eventTypes??c.event_types;const on=(name,fn)=>{if(events[name])c.eventSource.on(events[name],fn);};
  on('CHAT_CHANGED',()=>{invalidate();generation=false;storeRef=context().chatMetadata;ui.closeRoom();ui.home();render();status('已切换对话');ui.setLoreStatus('下次请求将检查当前卡的世界书绑定');installStatePrompt();schedule();});
  for(const name of ['WORLDINFO_UPDATED','WORLDINFO_SETTINGS_UPDATED','CHARACTER_EDITED'])on(name,()=>{ui.setLoreStatus('设定已变化，下次请求读取更新后的世界书');});
  on('GENERATION_STARTED',(type,options,dryRun)=>{installStatePrompt();if(dryRun||type==='quiet'||type==='impersonate')return;generation=true;invalidate();status('正文正在生成，完成后自动同步');});on('GENERATION_ENDED',()=>{generation=false;schedule();});on('GENERATION_STOPPED',()=>{generation=false;schedule();});
  for(const name of ['MESSAGE_EDITED','MESSAGE_DELETED','MESSAGE_SWIPED'])on(name,()=>{invalidate();schedule();});
  on('CHARACTER_MESSAGE_RENDERED',schedule);on('MESSAGE_RECEIVED',schedule);installStatePrompt();schedule();
}
if(globalThis.SillyTavern?.getContext){const c=context(),e=c.eventTypes??c.event_types;if(e.APP_READY)c.eventSource.on(e.APP_READY,()=>{setTimeout(boot,0);});else boot();}
