import test from 'node:test';import assert from 'node:assert/strict';import {parseResponseJSON} from './json-response.js';import {parseChatReply} from './chat-protocol.js';import {parseSocial} from './social.js';
const roles=[{id:'11',name:'莱恩'}];
test('actual literal newlines and tabs inside JSON strings are recovered',()=>{const raw='{"bubbles":[{"type":"text","text":"第一行\n第二行\t嗯"},],}';assert.equal(parseResponseJSON(raw).bubbles[0].text,'第一行\n第二行\t嗯');assert.equal(parseChatReply(raw,roles[0],roles)[0].text,'第一行\n第二行\t嗯');});
test('fenced and valid escaped JSON work without changing quoted commas',()=>{const raw='```json\n{"bubbles":["嗯,]\\n再说一句"]}\n```';assert.equal(parseResponseJSON(raw).bubbles[0],'嗯,]\n再说一句');});
test('broken JSON cannot become a raw chat bubble or execute code',()=>{assert.throws(()=>parseChatReply('```json\n{"bubbles":["unfinished',roles[0],roles));assert.throws(()=>parseResponseJSON('{"x":undefined}'));assert.throws(()=>parseResponseJSON('alert(1)'));});
test('mail API handles real newlines in body through the same parser',()=>{const raw='{"letters":[{"senderId":"11","kind":"letter","subject":"晚安","body":"第一行\n第二行"}]}';const s={gold:100,inventory:[],plots:[]};assert.equal(parseSocial(raw,roles,s).letters[0].body,'第一行\n第二行');});

import {decodeCompletion} from './json-response.js';
const chunk=x=>'data: '+JSON.stringify(x)+'\r\n\r\n';
test('stream chunks accumulate Unicode JSON without exposing reasoning',()=>{const d={};const raw=': heartbeat\r\n\r\n'+chunk({choices:[{index:0,delta:{reasoning_content:'secret'}}]})+chunk({choices:[{index:0,delta:{content:'{"消息":"你'}}]})+chunk({choices:[{index:0,delta:{content:'好"}'},finish_reason:'stop'}]})+chunk({choices:[],usage:{completion_tokens:20}})+'data: [DONE]\r\n\r\n';assert.equal(decodeCompletion(raw,d),'{"消息":"你好"}');assert.equal(d.reasoningChars,6);assert.equal(d.usage.outputTokens,20);assert(!JSON.stringify(d).includes('secret'));});
test('nonstream JSON and text content arrays remain supported',()=>{for(const content of ['hello',[{type:'thinking',text:'secret'},{type:'text',text:'hello'}]])assert.equal(decodeCompletion(JSON.stringify({choices:[{message:{content},finish_reason:'stop'}]})),'hello');});
test('empty provider choices diagnosed rather than falsely successful',()=>{const d={};assert.throws(()=>decodeCompletion(JSON.stringify({choices:[],usage:{prompt_tokens:80,completion_tokens:0}}),d),/空候选/);assert.equal(d.choices,0);assert.equal(d.usage.outputTokens,0);});
test('reasoning-only, filtered and truncated responses are never accepted',()=>{assert.throws(()=>decodeCompletion(JSON.stringify({choices:[{message:{content:'',reasoning_content:'secret'},finish_reason:'stop'}]})),/只返回思考/);assert.throws(()=>decodeCompletion(JSON.stringify({choices:[{message:{content:'partial'},finish_reason:'length'}]})),/达到上限/);assert.throws(()=>decodeCompletion(JSON.stringify({choices:[{message:{content:''},finish_reason:'content_filter'}]})),/拒绝/);});
test('stream cutoff and malformed events do not commit partial replies',()=>{assert.throws(()=>decodeCompletion(chunk({choices:[{delta:{content:'{"messages":[]}'}}]})),/提前结束/);assert.throws(()=>decodeCompletion('data: {broken}\n\ndata: [DONE]\n\n'),/不完整/);assert.throws(()=>decodeCompletion('<html>gateway error</html>'),/不是有效/);});
test('tool calls and provider error envelopes are not mistaken for text',()=>{assert.throws(()=>decodeCompletion(JSON.stringify({choices:[{message:{tool_calls:[{id:'x'}]}}]})),/工具调用/);assert.throws(()=>decodeCompletion(JSON.stringify({error:{message:'upstream secret'}})),/服务商返回错误/);});
test('provider text refusal is reported as policy rejection, not malformed game JSON',()=>{const d={};assert.throws(()=>decodeCompletion(JSON.stringify({choices:[{message:{content:"The prompt could not be submitted. The prompt contains sensitive words that violate Google's Generative AI Prohibited Use policy."},finish_reason:'stop'}]}),d),/内容规则限制/);assert.equal(d.providerRejected,true);});
