import test from 'node:test';import assert from 'node:assert/strict';import {readStateBlock} from './protocol.js';import {formatState} from './text-state.js';import {applyPatch} from './core.js';import {appendTransaction,applySocialEvents} from './social.js';import {mergeInventorySnapshot,inventoryRecoveryCandidates} from './list-state.js';import {formatFarmReview} from './story-sync.js';
const item=(name,count,kind='item')=>({name,count,kind,price:10,priceUnknown:false,days:kind==='seed'?4:0});const state={gold:650,capacity:24,calendar:{season:'春季',day:1,year:1,time:'12:00',weather:'晴'},inventory:[item('锄头',1),item('木材',20),item('防风草种子',30,'seed')],plots:Array.from({length:24},()=>({crop:'',wet:false,days:null,fertilizer:''})),quests:[{name:'微风的秘密',status:'进行中'}],locations:{},relationships:{},animals:[{name:'小牛',status:'幼崽'}],buildings:[{name:'鸡舍',status:'已建成'}],calendarEvents:[{name:'集市',season:'春季',day:5,detail:'购物'}],notes:''};
const footer=text=>'【手机状态】\n'+text+'\n【状态结束】';
test('reported partial potion reward footer preserves old items, all 18 plots and ongoing task',()=>{const raw=footer('时间：春季|1日|星期一|13:00|晴|第1年\n金币：950\n背包：回复药水|2|物品|未知|未知\n农田：1-15|防风草|播种|4|已浇|无\n农田：16|草莓|播种|8|已浇|无\n农田：17|胡萝卜|播种|3|已浇|无\n农田：18|郁金香|播种|6|已浇|无\n位置：哈兰|邮局\n好感：哈兰|18\n任务：贴身农时|已结算|1|完成任务|300金币、回复药水×2|今日|奖励已领取\n任务：微风的秘密|进行中|0|购买物品|400金币|明日|任务详情');const next=readStateBlock(raw,state,{roles:[{id:'13',name:'哈兰'}],anchors:{邮局:{region:'center',x:25,y:55}}}).state;assert.equal(next.inventory.length,4);assert.equal(next.inventory.find(x=>x.name==='木材').count,20);assert.equal(next.inventory.find(x=>x.name==='回复药水').count,2);assert.equal(next.plots.filter(x=>x.crop).length,18);assert.equal(next.gold,950);assert.equal(next.relationships['13'],18);});
test('absolute quantity updates do not sum; used-up items need explicit zero and never return on reread',()=>{const p=readStateBlock(footer('背包：防风草种子|0|种子|未知|未知\n背包：木材|5|物品|未知|未知'),state);assert.equal(p.state.inventory.some(x=>x.name==='防风草种子'),false);assert.equal(p.state.inventory.find(x=>x.name==='木材').count,5);assert.equal(p.state.inventory.find(x=>x.name==='木材').price,10);assert.deepEqual(readStateBlock(footer('背包：木材|5|物品|未知|未知'),p.state).state.inventory,p.state.inventory);assert.deepEqual(readStateBlock(footer('背包：无'),p.state).state.inventory,p.state.inventory);});
test('empty JSON lists and partial animal building calendar snapshots preserve omitted records',()=>{const p=readStateBlock('<junimo-state>'+JSON.stringify({version:1,patch:{inventory:[],animals:[],buildings:[],calendarEvents:[]}})+'</junimo-state>',state);for(const key of ['inventory','animals','buildings','calendarEvents'])assert.deepEqual(p.state[key],state[key]);const added=readStateBlock(footer('建筑：谷仓|建设中|20\n动物：小鸡|幼崽\n日程：舞会|春季|10|跳舞|无'),state).state;assert.equal(added.buildings.length,2);assert.equal(added.animals.length,2);assert.equal(added.calendarEvents.length,2);const removed=readStateBlock(footer('建筑：鸡舍|已拆除\n动物：小牛|已售出\n日程：集市|春季|5|已取消|无'),added).state;assert.equal(removed.buildings.length,1);assert.equal(removed.animals.length,1);assert.equal(removed.calendarEvents.length,1);});
test('real crafting gifting and feeding transactions still remove the last item exactly once',()=>{const s={socialEvents:[]};appendTransaction(s,state,{id:'consume',items:[{name:'锄头',count:-1},{name:'木材',count:-20}]});const next=applySocialEvents(state,s.socialEvents);assert.equal(next.inventory.length,1);assert.deepEqual(readStateBlock(footer('背包：回复药水|2|物品|未知|未知'),next).state.inventory.map(x=>x.name),['防风草种子','回复药水']);assert.deepEqual(applyPatch(state,{inventory:[]}).inventory,[]);});
test('state and farm confirmation previews retain explicit zeros so removed materials cannot reappear',()=>{const candidate={...state,inventory:[state.inventory[0]]};for(const preview of [formatState(candidate,[],{},{inventoryBaseline:state.inventory}),formatFarmReview(candidate,state)]){assert(preview.includes('背包：木材|0|'));assert.deepEqual(readStateBlock(preview,state).state.inventory,candidate.inventory);}});
test('historical recovery returns review candidates without restoring consumed items or touching progress',()=>{const current={...state,inventory:[item('回复药水',2)]},s={base:state,turns:[{state:current}]},before=structuredClone(s);const candidates=inventoryRecoveryCandidates(s,current);assert.equal(candidates.length,3);assert.deepEqual(s,before);assert.deepEqual(inventoryRecoveryCandidates({base:current,turns:[]},current),[]);assert.throws(()=>mergeInventorySnapshot(state.inventory,[item('木材',1),item('木材',2)]));});
