import test from 'node:test';
import assert from 'node:assert/strict';
import {EXPECTED_BOOK,resolveBinding,readBoundLore,selectLore} from './lore.js';
const ctx={characterId:0,name1:'农场主',characters:[{avatar:'moon.png',data:{extensions:{world:EXPECTED_BOOK}}}],getRequestHeaders:()=>({'Content-Type':'application/json'})};
test('only the named book linked to the bound card is read',()=>{assert.equal(resolveBinding(ctx).name,EXPECTED_BOOK);assert.throws(()=>resolveBinding(ctx,'other.png'));assert.throws(()=>resolveBinding({...ctx,groupId:'g'}));assert.throws(()=>resolveBinding({...ctx,characters:[{avatar:'x',data:{extensions:{world:'其他书'}}}]}));});
test('same card follows its linked book rename',()=>assert.equal(resolveBinding({...ctx,characters:[{avatar:'moon.png',data:{extensions:{world:'重命名后的书'}}}]},'moon.png').name,'重命名后的书'));
test('reread latest content on every request, with no global books',async()=>{let version=1;const mock=async(url,init)=>{assert.equal(url,'/api/worldinfo/get');assert.deepEqual(JSON.parse(init.body),{name:EXPECTED_BOOK});assert.equal(init.cache,'no-store');return {ok:true,json:async()=>({entries:{0:{content:'v'+version}}})};};assert.equal((await readBoundLore(ctx,'',undefined,mock)).entries[0].content,'v1');version=2;assert.equal((await readBoundLore(ctx,'',undefined,mock)).entries[0].content,'v2');});
test('prioritize chosen character, common rules, skip disabled and UI scripts',()=>{const entries=[{comment:'世界观',constant:true,content:'春日{{user}}'},{comment:'阿德里安',key:['阿德里安'],content:'镇长人设'},{comment:'塞勒斯',constant:true,content:'木匠人设'},{comment:'停用',constant:true,disable:true,content:'不读'},{comment:'顶部状态栏',constant:true,content:'<script>bad()</script>'}];const result=selectLore(entries,{roleName:'阿德里安',roles:[{name:'阿德里安'},{name:'塞勒斯'}],user:'小林'});assert.deepEqual(result.selected.map(e=>e.title),['阿德里安','世界观']);assert.equal(result.selected[1].content,'春日小林');});
test('bounds long lore and fails closed on missing server data',async()=>{const result=selectLore([{comment:'世界观',content:'x'.repeat(5000)}],{budget:200});assert(result.trimmed);assert(result.selected[0].content.length<300);await assert.rejects(readBoundLore(ctx,'',undefined,async()=>({ok:false,status:404})),/读取失败/);});
