import test from 'node:test';import assert from 'node:assert/strict';import {visibleMessages,quotedMessage,removeMessage,removePost} from './phone-records.js';import {phoneTimeline} from './phone-memory.js';import {narrativeMemory} from './social.js';import {allPosts,publicMemory} from './community.js';
const roles=[{id:'11',name:'莱恩'}];
function sample(){return {manual:[{id:'a',roleId:'11',from:'role',text:'SECRET',created:1},{id:'b',roleId:'11',from:'me',text:'回答',quoteId:'a',created:2}],turns:[],posts:[{id:'p',authorId:'me',text:'POSTSECRET',created:1}],socialEvents:[]};}
test('deleting a quoted message removes its text from every phone memory surface',()=>{const s=sample();assert.equal(quotedMessage(s,s.manual[1]).text,'SECRET');assert(removeMessage(s,'a'));assert.equal(quotedMessage(s,s.manual[0]),undefined);assert(!JSON.stringify(phoneTimeline(s,roles[0],roles)).includes('SECRET'));assert(!narrativeMemory(s,roles).includes('SECRET'));assert.equal(s.manual[0].text,'回答');assert(!removeMessage(s,'a'));});
test('legacy IDs survive JSON reload and deletion also scrubs backups',()=>{const s=sample();delete s.manual[0].id;s.backup=structuredClone(s);const id=visibleMessages(s)[0].id;assert.equal(visibleMessages(JSON.parse(JSON.stringify(s)))[0].id,id);removeMessage(s,id);assert(!JSON.stringify([s.manual,s.backup.manual]).includes('SECRET'));});
test('ledger balances survive bubble deletion while transaction prose is removed',()=>{const s=sample();s.socialEvents=[{id:'a',gold:-50,description:'SECRET',created:1},{id:'claim-a',gold:20,description:'领取SECRET',created:2}];s.draft={actions:['【手机已结算，请勿重复扣增】SECRET','其他行动']};removeMessage(s,'a');assert.deepEqual(s.socialEvents.map(e=>e.gold),[-50,20]);assert(!narrativeMemory(s,roles).includes('SECRET'));assert.deepEqual(s.draft.actions,['其他行动']);});
test('both author types and turn posts can be deleted without resurrection',()=>{const s=sample();s.turns=[{posts:[{id:'r',authorId:'11',text:'ROLESECRET',created:2}]}];s.backup=structuredClone(s);removePost(s,'p');removePost(s,'r');assert.deepEqual(allPosts(s),[]);assert(!publicMemory(s,roles).includes('SECRET'));s.posts=[{id:'p',text:'POSTSECRET'}];assert.deepEqual(allPosts(s),[]);});
test('quotes cannot expose another private thread and deletion stays in its chat',()=>{const s=sample(),other=structuredClone(s);s.manual[1].roleId='10';assert.equal(quotedMessage(s,s.manual[1]),undefined);removeMessage(s,'a');assert.equal(visibleMessages(other).length,2);});

