import test from 'node:test';import assert from 'node:assert/strict';import {visibleMessages,quotedMessage,removeMessage,removePost} from './phone-records.js';import {phoneTimeline} from './phone-memory.js';import {narrativeMemory} from './social.js';import {allPosts,publicMemory} from './community.js';
const roles=[{id:'11',name:'莱恩'}];
function sample(){return {manual:[{id:'a',roleId:'11',from:'role',text:'SECRET',created:1},{id:'b',roleId:'11',from:'me',text:'回答',quoteId:'a',created:2}],turns:[],posts:[{id:'p',authorId:'me',text:'POSTSECRET',created:1}],socialEvents:[]};}
test('deleting a quoted message removes its text from every phone memory surface',()=>{const s=sample();assert.equal(quotedMessage(s,s.manual[1]).text,'SECRET');assert(removeMessage(s,'a'));assert.equal(quotedMessage(s,s.manual[0]),undefined);assert(!JSON.stringify(phoneTimeline(s,roles[0],roles)).includes('SECRET'));assert(!narrativeMemory(s,roles).includes('SECRET'));assert.equal(s.manual[0].text,'回答');assert(!removeMessage(s,'a'));});
test('legacy IDs survive JSON reload and deletion also scrubs backups',()=>{const s=sample();delete s.manual[0].id;s.backup=structuredClone(s);const id=visibleMessages(s)[0].id;assert.equal(visibleMessages(JSON.parse(JSON.stringify(s)))[0].id,id);removeMessage(s,id);assert(!JSON.stringify([s.manual,s.backup.manual]).includes('SECRET'));});
test('ledger balances survive bubble deletion while transaction prose is removed',()=>{const s=sample();s.socialEvents=[{id:'a',gold:-50,description:'SECRET',created:1},{id:'claim-a',gold:20,description:'领取SECRET',created:2}];s.draft={actions:['【手机已结算，请勿重复扣增】SECRET','其他行动']};removeMessage(s,'a');assert.deepEqual(s.socialEvents.map(e=>e.gold),[-50,20]);assert(!narrativeMemory(s,roles).includes('SECRET'));assert.deepEqual(s.draft.actions,['其他行动']);});
test('both author types and turn posts can be deleted without resurrection',()=>{const s=sample();s.turns=[{posts:[{id:'r',authorId:'11',text:'ROLESECRET',created:2}]}];s.backup=structuredClone(s);removePost(s,'p');removePost(s,'r');assert.deepEqual(allPosts(s),[]);assert(!publicMemory(s,roles).includes('SECRET'));s.posts=[{id:'p',text:'POSTSECRET'}];assert.deepEqual(allPosts(s),[]);});
test('quotes cannot expose another private thread and deletion stays in its chat',()=>{const s=sample(),other=structuredClone(s);s.manual[1].roleId='10';assert.equal(quotedMessage(s,s.manual[1]),undefined);removeMessage(s,'a');assert.equal(visibleMessages(other).length,2);});

import {editMessage,messageEditGuidance} from './phone-records.js';
import {checkpoint,rollback} from './round-sync.js';
test('editing role and user text updates quotes, memories and rollback copies',()=>{const s=sample();s.turns.push({messages:[],before:checkpoint(s)});s.backup=structuredClone(s);editMessage(s,'a','晚安。','不要使用幼稚称呼');assert.equal(quotedMessage(s,s.manual[1]).text,'晚安。');assert(!JSON.stringify(s).includes('"text":"SECRET"'));assert(narrativeMemory(s,roles).includes('晚安。'));assert(phoneTimeline(s,roles[0],roles)[0].text==='晚安。');assert(messageEditGuidance(s).includes('不要使用幼稚称呼'));editMessage(s,'b','明天见');assert.equal(s.manual[1].text,'明天见');rollback(s,0);assert.equal(s.manual[0].text,'晚安。');assert.equal(s.manual[0].editReason,'不要使用幼稚称呼');});
test('legacy edits keep stable IDs and persist through JSON reload',()=>{const s=sample();delete s.manual[0].id;s.backup=structuredClone(s);const id=visibleMessages(s)[0].id;editMessage(s,id,'你好');const loaded=JSON.parse(JSON.stringify(s));assert.equal(loaded.backup.manual[0].id,id);assert.equal(visibleMessages(loaded)[0].id,id);assert(!JSON.stringify(s).includes('"text":"SECRET"'));});
test('edit reasons can be cleared and deleted records leave no guidance',()=>{const s=sample();editMessage(s,'a','你好','不要调侃');assert(messageEditGuidance(s).includes('不要调侃'));editMessage(s,'a','你好','');assert.equal(messageEditGuidance(s),'');editMessage(s,'a','你好','不要调侃');removeMessage(s,'a');assert.equal(messageEditGuidance(s),'');});
test('invalid edits are atomic; transactions and recalled messages cannot be edited',()=>{const s=sample(),before=JSON.stringify(s);assert.throws(()=>editMessage(s,'a','  '));assert.throws(()=>editMessage(s,'a','好','a'.repeat(601)));assert.equal(JSON.stringify(s),before);s.manual[0].type='redpacket';assert.throws(()=>editMessage(s,'a','改金额'));s.manual[0].type='text';s.manual[0].recalled={seen:true};assert.throws(()=>editMessage(s,'a','恢复'));});
test('voice transcript edits preserve type/status and update duration',()=>{const s=sample();Object.assign(s.manual[1],{type:'voice',duration:10,status:'sent'});editMessage(s,'b','再见。');assert.equal(s.manual[1].type,'voice');assert.equal(s.manual[1].duration,1);assert.equal(s.manual[1].status,'sent');});
