let recipeFilter='工业';
$('#craft .tip').textContent='图纸随故事学习；点击配方查看材料并制作。';
Array.from($$('#farm .farm-group-title')).at(-1).textContent='故事里的新工程';
function openReroll(scope='全部',kind='state'){
 const role=activeRole,chatId=uiCommunity().chatId;const scopeChoice=scope==='全部'?'<label class="jp-form-label">校正范围<select aria-label="校正范围">'+['全部','背包','农田','农场','制作','动物','日历','地图','任务','图鉴','朋友圈','聊天'].map(n=>'<option>'+n+'</option>').join('')+'</select></label>':'';
 const d=sheet('带指令重 roll','<div class="jp-page-intro"><small>A LITTLE REVISION</small><h2>把这一处，改得更好。</h2></div><p class="jp-sheet-caption">范围：'+esc(scope)+'。说明哪里有误，以及哪些内容需要保留。'+(kind==='state'?'生成后先预览，确认才应用。':'会替换最近一轮结果，失败保留旧内容。')+'</p>'+scopeChoice+'<label class="jp-form-label">修改要求<textarea aria-label="重roll修改要求" maxlength="3000" placeholder="例如：只改错种的作物，金币、日期和其他田格不要动。"></textarea></label><button class="jp-primary" data-run>按要求重新整理</button>');
 d.querySelector('[data-run]').onclick=async e=>{const b=e.currentTarget;b.disabled=true;try{if(chatId!==uiCommunity().chatId)throw Error('对话已切换，请重新打开');const text=d.querySelector('textarea').value.trim();if(!text)throw Error('请先写下修改要求');if(kind==='chat')await bridge.rerollChat(role,text);else if(kind==='mail')await bridge.collectMail(true,text);else await bridge.repairState(d.querySelector('select')?.value||scope,text);d.remove();}catch(err){d.querySelector('.jp-review-error').textContent=err.message;b.disabled=false;}};
}
function drawWorkshop(){
 const state=liveState,count=name=>state.inventory.filter(x=>x.name===name).reduce((n,x)=>n+x.count,0);
 const recipes=state.recipes||[];$('#craft .app-head span').textContent='已学会 '+recipes.filter(r=>r.learned).length+' 张图纸';
 $('#craft .recipe-grid').innerHTML='<div class="jp-work-tabs">'+['工业','食物','家具'].map(c=>'<button data-category="'+c+'" aria-pressed="'+(c===recipeFilter)+'">'+c+'</button>').join('')+'</div>'+recipes.filter(r=>r.category===recipeFilter).map((r,i)=>'<button class="jp-work-card" data-learned-recipe="'+esc(r.name)+'"><small>'+esc(r.source||'故事中获得')+'</small><h3>'+esc(r.name)+'</h3><p>'+r.materials.map(m=>esc(m.name)+' '+count(m.name)+' / '+m.count).join(' · ')+'</p><b>'+(r.learned?'已学习 · '+esc(r.product)+' ×'+r.quantity:'尚未学习')+'</b></button>').join('')+(!recipes.some(r=>r.category===recipeFilter)?'<p class="jp-sheet-caption">还没有这类图纸。收到食谱、角色传授或探索发现后，会记录在这里。</p>':'');
 $('#craft .recipe-grid').querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{recipeFilter=b.dataset.category;drawWorkshop();});
 $$('[data-learned-recipe]').forEach(b=>b.onclick=()=>{const r=recipes.find(r=>r.name===b.dataset.learnedRecipe);const d=sheet(r.name,'<p>'+esc(r.description||'')+'</p><p class="jp-sheet-caption">每批：'+r.materials.map(m=>esc(m.name)+' ×'+m.count).join('、')+' · '+(r.gold||0)+' 金币</p><label class="jp-form-label">制作批数<input aria-label="制作批数" type="number" min="1" max="99" value="1"></label><button class="jp-primary" data-craft '+(r.learned?'':'disabled')+'>制作并收入背包</button>');d.querySelector('[data-craft]').onclick=async e=>{e.currentTarget.disabled=true;try{await bridge.craftItem(r.name,+d.querySelector('input').value);d.remove();toast('制作完成，材料已扣除');}catch(err){d.querySelector('.jp-review-error').textContent=err.message;e.currentTarget.disabled=false;}};});
 const list=$$('#farm .farm-text-list')[1];list.innerHTML=(state.farmProjects||[]).map(r=>'<section class="jp-work-card"><small>'+esc(r.source||'农场建设')+' · '+esc(r.status)+'</small><h3>'+esc(r.name)+'</h3><p>'+esc(r.description||'')+'</p><p>'+r.materials.map(m=>esc(m.name)+' '+count(m.name)+' / '+m.count).join(' · ')+'</p><b>'+(r.gold||0)+' 金币 · '+r.days+' 天</b>'+(r.status==='推荐'?'<button class="jp-primary" data-project="'+esc(r.name)+'">提交材料并开工</button>':'')+'</section>').join('')||'<p class="jp-sheet-caption">角色推荐的新工程会出现在这里。</p>';list.querySelectorAll('[data-project]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await bridge.startProject(b.dataset.project);toast('已开工，材料和费用已结算');}catch(e){toast(e.message);b.disabled=false;}});
}
function playerStatus(){const player=liveState.player||{},thresholds=[0,100,380,770,1300,2150,3300,4800,6900,10000,15000],names=['耕种','采矿','采集','钓鱼','战斗'];sheet('我的农场手记','<div class="jp-player-hero"><small>YOUR FARMER JOURNAL</small><span>✿</span><h2>'+esc(uiCommunity().userName||'农场主')+'</h2><p>把每一天的小进步，收进手记。</p></div><section class="jp-outfit"><small>今日穿着</small><p>'+esc(player.outfit||'等待正文确认当前穿着')+'</p></section><div class="jp-skills">'+names.map((name,i)=>{const xp=player.skills?.[name]||0,level=thresholds.findLastIndex(n=>xp>=n),next=thresholds[Math.min(10,level+1)],percent=level===10?100:(xp-thresholds[level])/(next-thresholds[level])*100;return '<section><div><b>'+['✿','◇','♧','≈','⚔'][i]+' '+name+'</b><span>Lv. '+level+'</span></div><progress max="100" value="'+percent+'"></progress><small>'+xp+' / '+next+' XP'+(level===10?' · 满级':'')+'</small></section>';}).join('')+'</div><p class="jp-sheet-caption">随正文完成的劳动累计经验；最高10级。重读同一楼不会重复增加。</p>','jp-page');}
const playerButton=smallButton('查看我的状态','✿ 状态',playerStatus);$('#bag .app-head').append(playerButton);
for(const [id,name] of [['bag','背包'],['quest','任务'],['dateApp','日历'],['farm','农场'],['fieldApp','农田'],['animal','动物'],['craft','制作'],['mapApp','地图'],['jpFeedApp','朋友圈'],['jpCollectionApp','图鉴'],['chatApp','聊天']]){const head=$('#'+id+' .app-head');if(head)head.append(smallButton('重 roll '+name,'↻',()=>openReroll(name)));}
extra.textContent+=`.jp-work-tabs{grid-column:1/-1;display:flex;gap:8px;margin:8px 0}.jp-work-tabs button{flex:1;padding:9px;border:0;border-radius:12px;background:#eee6d9;color:#8b7862}.jp-work-tabs button[aria-pressed=true]{background:#8ca58b;color:white}.jp-work-card{display:block;box-sizing:border-box;text-align:left;width:100%;border:1px solid #e2dbc8;border-radius:16px;padding:15px;background:#fffdf3;color:#675f4c;margin:7px 0}.jp-work-card small{font-size:10px;color:#9b947f}.jp-work-card h3{font-size:15px;margin:8px 0}.jp-work-card p{font-size:11px;line-height:1.8}.jp-work-card b{font-size:11px;color:#7f9a75}#craft .recipe-grid{display:block}#craft .action-bar{display:none}.jp-player-hero{text-align:center;padding:10px 0;color:#657e6d}.jp-player-hero small{font-size:9px;letter-spacing:2px}.jp-player-hero>span{display:block;font-size:32px;margin:6px;color:#c9989e}.jp-player-hero h2{margin:8px}.jp-player-hero p{font-size:11px;color:#a3988b}.jp-outfit{padding:16px;border-radius:16px;background:#f0e7e3;color:#89746c}.jp-outfit small{font-size:10px;letter-spacing:2px}.jp-outfit p{font-size:13px;line-height:1.8;white-space:pre-wrap}.jp-skills{display:grid;gap:10px;margin:16px 0}.jp-skills section{padding:12px 15px;background:#f0f2e9;border-radius:14px}.jp-skills section>div{display:flex;justify-content:space-between;color:#698170}.jp-skills progress{width:100%;height:6px;accent-color:#98b394;border:0;margin:10px 0 4px}.jp-skills small{font-size:10px;color:#a2a58e}.app-head .jp-icon-btn{flex-shrink:0}`;

extra.textContent+='.jp-skills progress{appearance:none;border-radius:6px;overflow:hidden}.jp-skills progress::-webkit-progress-bar{background:#e0e6d8;border-radius:6px}.jp-skills progress::-webkit-progress-value{background:#99b395;border-radius:6px}';
