import {readFileSync} from 'node:fs';
import test from 'node:test';import assert from 'node:assert/strict';import {mergeQuests,recoverQuestHistory} from './quest-state.js';import {applyPatch,world} from './core.js';import {readStateBlock} from './protocol.js';import {questRows} from './round-settlement.js';
const a={name:'春之始',status:'进行中',goal:'播种5格',reward:'150金币',deadline:'无'},b={name:'镜前首秀',status:'进行中',goal:'穿戴衣服',reward:'100金币'},state={gold:500,inventory:[],plots:[],quests:[a,b],calendar:{season:'春季',day:1,year:1}};
const footer=text=>'【手机状态】\n'+text+'\n【状态结束】';
test('next narrative with task none cannot erase active quests or other state',()=>{const parsed=readStateBlock(footer('金币：650\n任务：无'),state);const next=applyPatch(state,parsed.patch);assert.deepEqual(next.quests,[a,b]);assert.equal(next.gold,650);assert.deepEqual(state.quests,[a,b]);});
test('partial completion updates only its name, hides completed and retains other active task',()=>{const parsed=readStateBlock(footer('任务：春之始|已结算|100||||'),state);const next=applyPatch(state,parsed.patch);assert.equal(next.quests.length,2);assert.deepEqual(questRows(next.quests).active.map(x=>x.q.name),[b.name]);assert.equal(next.quests[0].reward,'150金币');assert.equal(next.quests[0].goal,a.goal);const later=applyPatch(next,{quests:[{name:a.name,status:'进行中'}]});assert.equal(later.quests[0].status,'已结算');assert.equal(later.gold,500);});
test('new tasks append without wiping old ones; empty JSON and repairs also preserve tasks',()=>{const next=applyPatch(state,{quests:[{name:'新任务',status:'进行中'}]});assert.equal(next.quests.length,3);assert.deepEqual(applyPatch(next,{quests:[]}).quests,next.quests);assert.equal(mergeQuests([a],[{...a,progress:70}])[0].progress,70);});
test('migration recovers disappeared tasks from saved floors and preserves completion without awarding twice',()=>{const s={base:structuredClone(state),turns:[{state:{...structuredClone(state),quests:[{...a,status:'已结算'}]}},{state:{...structuredClone(state),quests:[]}}]};assert(recoverQuestHistory(s));assert.equal(s.turns[1].state.quests.length,2);assert.equal(s.turns[1].state.gold,500);assert.deepEqual(questRows(world(s).quests).active.map(x=>x.q.name),[b.name]);assert(s.questRecoveryBackup);assert.equal(recoverQuestHistory(s),false);s.turns=[];assert.deepEqual(questRows(world(s).quests).active.map(x=>x.q.name),[a.name,b.name]);});
test('fresh chats stay empty and recovery cannot restore tasks from other chats',()=>{const fresh={base:{...structuredClone(state),quests:[]},turns:[]};recoverQuestHistory(fresh);assert.deepEqual(world(fresh).quests,[]);assert.equal(fresh.questRecoveryBackup,undefined);});

test('actual narrative sync keeps unfinished quests over new floors while completing only the named quest',async()=>{const vm=await import('node:vm'),source=readFileSync('index.js','utf8'),imported={};for(const match of source.matchAll(/^import \{([^}]+)\} from '([^']+)';/gm)){const module=await import(new URL(match[2],import.meta.url));for(const name of match[1].split(',').map(n=>n.trim()))imported[name]=module[name];}const initial={...structuredClone(state),capacity:24,relationships:{},locations:{},animals:[],buildings:[],calendarEvents:[],notes:''},s={version:3,base:structuredClone(initial),turns:[],manual:[],unread:{},draft:null,started:true,storySignatureVersion:1};const c={extensionSettings:{junimo_pocket_v1:{enabled:true,proactive:false,feedFrequency:'off',commentFrequency:'off'}},chatMetadata:{junimo_pocket_v1:s},chat:[{is_user:true,mes:'做完春之始'},{mes:footer('任务：春之始|已结算|100|播种5格|150金币|无|完成')}],name1:'玩家',getCurrentChatId:()=> 'quest-test',saveMetadata:async()=>{},saveMetadataDebounced(){},setExtensionPrompt(){},eventTypes:{APP_READY:'ready'},eventSource:{on(){}}};const sandbox={...imported,resolveBinding(){},SillyTavern:{getContext:()=>c},structuredClone,AbortController,DOMException,console,setTimeout(){},clearTimeout(){}};vm.default.createContext(sandbox);vm.default.runInContext(source.replace(/^import .*?;\r?\n/gm,'')+'\nglobalThis.runSync=syncNarrative;globalThis.setup=()=>{ui={initial:globalThis.fixtureInitial,roles:[],mapAnchors:{},update(){},setStatus(){},notify(){},toast(){}};badge={classList:{toggle(){}}};};',sandbox);sandbox.fixtureInitial=initial;sandbox.setup();await sandbox.runSync();assert.deepEqual(questRows(imported.world(s).quests).active.map(x=>x.q.name),[b.name]);c.chat.push({is_user:true,mes:'去广场'},{mes:footer('任务：无\n金币：500')});await sandbox.runSync();assert.equal(imported.world(s).quests.length,2);assert.deepEqual(questRows(imported.world(s).quests).active.map(x=>x.q.name),[b.name]);assert.equal(imported.world(s).gold,500);});
