import {parseResponseJSON} from './json-response.js';
import {parseChatReply} from './chat-protocol.js';
import {groups} from './phone-memory.js';

const progressKeys=['manual','letters','mailQuests','socialEvents','posts','comments','catalog','offerings','draft','unread','chatRound','mailRound'];
export function checkpoint(s){return Object.fromEntries(progressKeys.map(k=>[k,structuredClone(s[k]??null)]));}
export function rollback(s,index){const turn=s.turns[index];if(!turn)return false;if(turn.before)for(const k of progressKeys){if(turn.before[k]===null)delete s[k];else s[k]=structuredClone(turn.before[k]);}s.manual??=[];s.unread??={};s.pendingNarrativeRevision=turn.socialRevision??0;s.turns.splice(index);return true;}
export function reconcileRounds(s,signatures){let i=0;while(i<s.turns.length&&s.turns[i].signature===signatures[i])i++;if(i<s.turns.length)rollback(s,i);return i;}
export function pendingThreads(s,roles,ids){const records=s.manual||[],allowed=[...roles,...groups(roles)];const pending=records.filter(m=>!(s.deletedMessageIds||[]).includes(m.id)&&m.from==='me'&&(ids?ids.includes(m.id):['queued','failed'].includes(m.status)));return allowed.map(role=>({role,messages:pending.filter(m=>m.roleId===role.id)})).filter(t=>t.messages.length);}
export function parseBatch(raw,threads,roles,stickers=[]){const data=parseResponseJSON(raw);const rows=data.replies||(threads.length===1?[{threadId:threads[0].role.id,...data}]:null);if(!Array.isArray(rows)||rows.length!==threads.length)throw Error('合并回复缺少聊天，请重 roll；本轮未写入');const seen=new Set();return rows.map(row=>{const thread=threads.find(t=>t.role.id===row.threadId);if(!thread||seen.has(row.threadId))throw Error('回复包含重复或未知聊天');seen.add(row.threadId);return {role:thread.role,raw:JSON.stringify(row),bubbles:parseChatReply(JSON.stringify(row),thread.role,roles,stickers)};});}
export function withoutRound(s,round){if(!round)return s;return {...s,manual:(s.manual||[]).filter(m=>m.batchId!==round.id),letters:(s.letters||[]).filter(m=>m.batchId!==round.id),posts:(s.posts||[]).filter(m=>m.batchId!==round.id),comments:(s.comments||[]).filter(m=>m.batchId!==round.id)};}
export function assertRerollable(s,round){if(!round)throw Error('本聊天还没有可重 roll 的请求');if((s.manual||[]).some(m=>m.batchId===round.id&&m.claimed)||(s.mailQuests||[]).some(q=>(s.letters||[]).some(l=>l.id===q.id&&l.batchId===round.id)))throw Error('本轮有已领取的赠送或已接取的委托，请保留结算后再发起新一轮');if(s.turns.length!==round.floor)throw Error('正文已经推进，本轮已进入故事记忆；请先回到对应正文楼层');}
export function ranges(values){const rows=[...new Set(values)].sort((a,b)=>a-b),out=[];for(let i=0;i<rows.length;i++){let end=rows[i],start=end;while(rows[i+1]===end+1)end=rows[++i];out.push(start===end?String(start):start+'-'+end);}return out.join(',');}
export function compactActions(actions=[]){const out=[];let group=null;const flush=()=>{if(group){out.push(group.a+'第'+ranges(group.ids)+'格'+group.b);group=null;}};for(const value of actions){const m=value.match(/^(.*?)第\s*(\d+)\s*格(.*)$/);if(!m){flush();out.push(value);continue;}if(group&&(group.a!==m[1]||group.b!==m[3]||group.ids.includes(+m[2])))flush();group??={a:m[1],b:m[3],ids:[]};group.ids.push(+m[2]);}flush();return out;}
export function actionMemory(s,state){const draft=s.draft;if(!draft?.actions?.length)return '';const grouped=new Map();for(let i=0;i<(draft.plots||[]).length;i++){const p=draft.plots[i];if(JSON.stringify(p)===JSON.stringify(state.plots?.[i]))continue;const k=JSON.stringify(p);if(!grouped.has(k))grouped.set(k,[]);grouped.get(k).push(i+1);}return '\n【手机行动同步（自动，不必用户粘贴）】\n'+JSON.stringify({actions:compactActions(draft.actions),plannedPlots:[...grouped].map(([p,ids])=>({plots:ranges(ids),...JSON.parse(p)})),rule:'已结算的领取红包、赠礼、提交委托和献祭已经计入当前金币与背包，禁止重复扣增；其他行动是待演绎计划，按本轮正文实际执行后更新变量。连续格号表示同一操作，不必在正文逐格复述。'})+'\n';}

// Only rendered DOM is hidden. Original chat messages and parser input are untouched.
export function hideStateBlocks(root=document){for(const el of root.querySelectorAll('.mes_text')){el.querySelectorAll('junimo-state').forEach(n=>{n.hidden=true;});const doc=el.ownerDocument,walker=doc.createTreeWalker(el,4);let n,nodes=[],text='';while(n=walker.nextNode()){if(n.parentElement.closest('[data-jp-sync-hidden],junimo-state'))continue;nodes.push({node:n,start:text.length});text+=n.textContent;}const pattern=/【手机状态】[\s\S]*?【状态结束】|<junimo-state>[\s\S]*?<\/junimo-state>/g;const matches=[...text.matchAll(pattern)];for(const match of matches.reverse()){const start=match.index,end=start+match[0].length,a=nodes.findLast(x=>x.start<=start),b=nodes.findLast(x=>x.start<end);if(!a||!b)continue;const range=doc.createRange();range.setStart(a.node,start-a.start);range.setEnd(b.node,end-b.start);const hidden=doc.createElement('span');hidden.dataset.jpSyncHidden='true';hidden.hidden=true;hidden.style.display='none';hidden.append(range.extractContents());range.insertNode(hidden);}}}
export function watchStateBlocks(){let scheduled=false;const run=()=>{scheduled=false;observer.disconnect();try{hideStateBlocks();}finally{observer.observe(document.body,{childList:true,subtree:true,characterData:true});}};const observer=new MutationObserver(()=>{if(!scheduled){scheduled=true;queueMicrotask(run);}});run();return observer;}
