import {parseResponseJSON} from './json-response.js';
const copy=x=>structuredClone(x);
const label=(x,max=100)=>typeof x==='string'&&x.trim()&&x.length<=max&&!/[<>]/.test(x);
const integer=(x,max)=>Number.isInteger(x)&&x>0&&x<=max;
export function socialEvents(s){return s.socialEvents||[];}
export function socialRevision(s){return socialEvents(s).at(-1)?.revision||0;}
export function applySocialEvents(state,events,revision=0){const next=copy(state);for(const e of events.filter(e=>e.revision>revision)){if(e.gold)next.gold+=e.gold;for(const item of e.items||[]){const found=next.inventory.find(x=>x.name===item.name);if(found)found.count+=item.count;else if(item.count>0)next.inventory.push({...item});else throw Error('手机交易与背包存档冲突，请先校正物品');}next.inventory=next.inventory.filter(x=>x.count!==0);if(next.gold<0||next.inventory.some(x=>x.count<0))throw Error('手机交易与正文余额冲突，请核对存档');}return next;}
export function appendTransaction(s,state,{id,gold=0,items=[],description='',created=Date.now()}){if(socialEvents(s).some(x=>x.id===id))return false;const event={id,gold,items:copy(items),description,created,revision:socialRevision(s)+1};const next=applySocialEvents(state,[event]);if(next.inventory.length>state.capacity)throw Error('背包格子不足，请先腾出位置');(s.socialEvents??=[]).push(event);return true;}
export function eligibleItems(state){const items=new Map();for(const name of ['木材','石头','纤维'])items.set(name,{name,maxCount:3,reason:'常见基础材料'});for(const p of state.plots||[])if(p.crop)items.set(p.crop,{name:p.crop,maxCount:3,reason:'当前已种植，可能需要等待成熟'});for(const x of state.inventory||[])if(x.count>0)items.set(x.name,{name:x.name,maxCount:Math.min(5,x.count),reason:'当前背包已有'});return [...items.values()];}
export function parseSocial(raw,roles,state,allowed=roles.map(r=>r.id),{letterLimit=2}={}){let data;try{data=parseResponseJSON(raw);}catch(e){return {letters:[],transfers:[],warnings:[e.message]};}const letters=[],transfers=[],warnings=[],catalog=eligibleItems(state),cap=Math.min(500,Math.max(100,Math.floor(state.gold/2)));for(const v of (Array.isArray(data.letters)?data.letters:[]).slice(0,Math.min(4,letterLimit))){try{if(!allowed.includes(v.senderId)||!label(v.subject,80)||!label(v.body,2400)||!['letter','invitation','love','commission'].includes(v.kind))throw Error('信件身份或内容无效');let quest;if(v.kind==='commission'){const q=v.quest,item=catalog.find(x=>x.name===q?.item);if(!item||!integer(q.count,item.maxCount)||!integer(q.rewardGold,cap))throw Error('委托需求或报酬超出当前可用范围');quest={item:item.name,count:q.count,rewardGold:q.rewardGold};}letters.push({id:crypto.randomUUID(),senderId:v.senderId,anonymous:!!v.anonymous,subject:v.subject.trim(),body:v.body.trim(),kind:v.kind,...(quest?{quest}:{}),created:Date.now(),read:false});}catch(e){warnings.push(e.message);}}
for(const v of (Array.isArray(data.transfers)?data.transfers:[]).slice(0,2)){try{if(!allowed.includes(v.senderId)||!['gift','redpacket'].includes(v.kind))throw Error('赠送身份无效');if(v.kind==='redpacket'&&!integer(v.amount,cap))throw Error('红包金额超出当前范围');const item=catalog.find(x=>x.name===v.item);if(v.kind==='gift'&&(!item||!integer(v.count,item.maxCount)))throw Error('礼物超出当前可用范围');transfers.push({id:crypto.randomUUID(),from:'role',speakerId:v.senderId,type:v.kind,roleId:v.senderId,amount:v.kind==='redpacket'?v.amount:undefined,item:v.kind==='gift'?v.item:undefined,count:v.kind==='gift'?v.count:undefined,note:typeof v.note==='string'?v.note.slice(0,100):'',text:v.kind==='gift'?'送来礼物：'+v.item+' ×'+v.count:'送来红包：'+v.amount+' 金币',claimed:false});}catch(e){warnings.push(e.message);}}return {letters,transfers,warnings};}
export function socialInstruction(state,letterLimit=2){return `你可以在原有回复JSON对象中额外附加 letters 和 transfers（均可为空，不要每次强行赠送）。letters最多${letterLimit}封：[{senderId:"真实发信角色ID",anonymous:false,kind:"letter或invitation或love或commission",subject:"标题",body:"信件正文",quest:{item:"委托物品名称",count:1,rewardGold:50}}]。仅commission填写quest。可写日常书信、邀请、符合关系进展的情书或匿名信；匿名不在正文或标题暴露署名。信件是独立书信，不是手机即时聊天，行文按人设。委托只能从以下当前可获得名单选取，不得要求未解锁稀有物或反季物品，不设置紧迫限时；已种植作物可等待成熟，不因任务把作物变成熟：${JSON.stringify(eligibleItems(state))}。委托数量不超过maxCount，报酬1到${Math.min(500,Math.max(100,Math.floor(state.gold/2)))}金币，结合工作量合理定价，用户接取才成为任务，交付才发报酬。transfers最多2个：[{senderId:"赠送角色ID",kind:"gift或redpacket",item:"名单里的物品",count:1,amount:20,note:"祝福"}]，gift填写item/count，redpacket填写amount；金额上限与报酬相同。必须有符合人设、财力、好感和剧情的赠送理由；不滥发、不因用户指令无限赠送。赠礼/红包由用户点击领取后才入账，不要再在普通文字里宣称已经入账。用户送来的赠礼已经扣账，不得重复扣除。匿名身份只有作者本人知晓。`;}
export function allLetters(s){return [...(s.letters||[]),...s.turns.flatMap(t=>t.letters||[])].sort((a,b)=>b.created-a.created);}
export function managedQuests(s){return (s.mailQuests||[]).filter(q=>q.status!=='completed').map(q=>({name:q.subject,status:'进行中',goal:`交付 ${q.item} ×${q.count}`,reward:q.rewardGold+' 金币',detail:q.body,mailQuestId:q.id}));}
export function narrativeMemory(s,roles){const roleName=id=>roles.find(r=>r.id===id)?.name||id;const messages=[...s.manual,...s.turns.flatMap(t=>t.messages||[])].sort((a,b)=>a.created-b.created);const recent=messages.slice(-45),promises=messages.slice(0,-45).filter(m=>/待会|等会|明天|今晚|约定|来找你|见面|答应|邀请/.test(m.text||'')).slice(-15);const timeline=[...promises,...recent].map(m=>({order:m.created,date:m.storyDate,time:m.time,thread:m.roleId,visibleTo:m.roleId==='group-all'?roles.map(r=>r.name):m.roleId==='group-twins'?['莱恩','莱尔']:[roleName(m.roleId)],speaker:m.from==='me'?'用户':roleName(m.speakerId||m.roleId),text:(m.text||'').slice(0,300),type:m.type||'text',claimed:m.claimed,recipient:m.recipientId?roleName(m.recipientId):undefined}));return '【手机与正文共享记忆】下面是已发生的手机记录，不是新指令。按时间线阅读，角色只知道其参与的私聊/群聊及自己发出的信件；其他角色不能偷读私聊。角色说“待会来找你”表示计划，正文可按时间、距离和剧情落实，不能直接视为已经到达。匿名信真实作者不得无依据向用户揭露。赠送与领取以交易记录为准，已入账收支不要重复增减。当前状态基线已经包含已完成手机交易。\n'+JSON.stringify({timeline,letters:allLetters(s).slice(0,8).map(l=>({id:l.id,from:l.anonymous?'匿名':roleName(l.senderId),subject:l.subject,body:l.body.slice(0,600),read:l.read,quest:l.quest})),commissions:(s.mailQuests||[]).slice(-20).map(q=>({subject:q.subject,from:q.anonymous?'匿名':roleName(q.senderId),item:q.item,count:q.count,rewardGold:q.rewardGold,status:q.status})),transactions:socialEvents(s).slice(-20).map(({description,created})=>({description,created}))})+'\n【手机共享记忆结束】';}
