let dbPromise,cache=[];
function database(){return dbPromise??=new Promise((resolve,reject)=>{const req=indexedDB.open('junimo_pocket_stickers',1);req.onupgradeneeded=()=>req.result.createObjectStore('stickers',{keyPath:'id'});req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(Error('无法打开本地表情包库'));});}
async function transaction(mode,action){const db=await database();return new Promise((resolve,reject)=>{const tx=db.transaction('stickers',mode),req=action(tx.objectStore('stickers'));tx.oncomplete=()=>resolve(req.result);tx.onerror=()=>reject(Error('表情包保存失败，可能是本机存储已满'));tx.onabort=()=>reject(Error('表情包保存已取消'));});}
export async function loadStickers(){cache=await transaction('readonly',s=>s.getAll());return cache;}
export function stickerCatalog(){return cache.map(({id,name,description})=>({id,name,description}));}
export function getSticker(id){return cache.find(s=>s.id===id);}
export async function saveSticker({name,description='',dataUrl}){name=name.trim();description=description.trim();if(!name||name.length>40)throw Error('请给表情包起一个40字以内的名字');if(description.length>300)throw Error('表情说明最多300字');if(!/^data:image\/(?:png|jpeg|webp|gif);base64,/.test(dataUrl)||dataUrl.length>3000000)throw Error('图片格式或大小不支持');if(cache.length>=100)throw Error('本机表情包最多100个，请先整理');const item={id:crypto.randomUUID(),name,description,dataUrl,created:Date.now()};await transaction('readwrite',s=>s.put(item));cache.push(item);return item;}
export async function deleteSticker(id){await transaction('readwrite',s=>s.delete(id));cache=cache.filter(s=>s.id!==id);}
export async function prepareSticker(file){if(!file||!/^image\/(png|jpeg|webp|gif)$/.test(file.type))throw Error('请选择 PNG、JPG、WebP 或 GIF 图片');if(file.size>10*1024*1024)throw Error('图片请小于10MB');const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(Error('图片读取失败'));r.readAsDataURL(file);});if(file.type==='image/gif'){if(data.length>2800000)throw Error('GIF 请控制在2MB以内');return data;}const img=new Image();img.src=data;await img.decode();const scale=Math.min(1,768/Math.max(img.naturalWidth,img.naturalHeight)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.naturalWidth*scale));canvas.height=Math.max(1,Math.round(img.naturalHeight*scale));canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/webp',.85);}
export function stickerPrompt(){return '可用表情包目录：'+JSON.stringify(stickerCatalog())+'。可按心情选择已有表情包，返回气泡 {type:"sticker",stickerId:"目录中的ID"}；不要编造ID。不能识图时依据名字和说明理解。';}
export function withStickerImages(text,messages,enabled){if(!enabled)return text;const images=[...new Set(messages.filter(m=>m.type==='sticker').map(m=>m.stickerId))].slice(-4).map(getSticker).filter(Boolean);if(!images.length)return text;return [{type:'text',text},...images.flatMap(s=>[{type:'text',text:'表情包 '+s.name+'：'+s.description},{type:'image_url',image_url:{url:s.dataUrl,detail:'low'}}])];}
