import {formatState} from './text-state.js';
// Image prompt edits and image delivery are presentation changes, not new story turns.
export function storyText(raw){let text=String(raw??'');const tokens=[...text.matchAll(/<\/?bbi_image\b[^>]*>/gi)],stack=[],cuts=[];for(const token of tokens){if(token[0][1]!=='/')stack.push(token);else{const open=stack.pop();cuts.push([open?.index??token.index,token.index+token[0].length]);}}for(const token of stack)cuts.push([token.index,token.index+token[0].length]);cuts.sort((a,b)=>a[0]-b[0]);let out='',cursor=0;for(const [a,b] of cuts){if(a<cursor)continue;out+=text.slice(cursor,a);cursor=b;}out+=text.slice(cursor);return out.replace(/<img\b[^>]*>/gi,'').replace(/!\[[^\]]*\]\([^\n]*?\)/g,'').replace(/\r\n?/g,'\n').replace(/[ \t]+\n/g,'\n').replace(/\n{2,}/g,'\n').trim();}
export function storyKey(m){return JSON.stringify([!!m.is_user,!!m.is_system,m.name||'',storyText(m.mes),m.swipe_id??0]);}
export const plotView=p=>({crop:p?.crop||'',days:p?.days??null,wet:!!p?.wet,fertilizer:p?.fertilizer||''});
export function changedPlots(draft,state){return (draft?.plots||[]).flatMap((p,i)=>JSON.stringify(plotView(p))===JSON.stringify(plotView(state.plots?.[i]))?[]:[{index:i+1,...plotView(p)}]);}
export function farmMismatch(draft,before,after){if(!draft?.actions?.some(a=>/农田|浇水|收获|铲除|耕地/.test(a)))return [];const changed=new Set(changedPlots(draft,before).map(p=>p.index));return Array.from({length:Math.max(draft.plots.length,after.plots.length)},(_,i)=>i).filter(i=>{const wanted=plotView(draft.plots[i]),actual=plotView(after.plots[i]);return wanted.crop!==actual.crop||(changed.has(i+1)&&(wanted.wet!==actual.wet||wanted.fertilizer!==actual.fertilizer));}).map(i=>i+1);}
export function reviewedFarmState(draft,before,after){const state=structuredClone(after);state.plots=draft.plots.map((p,i)=>({...plotView(p),stage:!p.crop?'empty':p.crop===before.plots[i]?.crop?(after.plots[i]?.stage||before.plots[i]?.stage||'growing'):'seeded'}));const used=new Map();for(const p of changedPlots(draft,before))if(p.crop&&p.crop!==before.plots[p.index-1]?.crop)used.set(p.crop+'种子',(used.get(p.crop+'种子')||0)+1);for(const [name,count] of used){const owned=before.inventory.find(x=>x.name===name);if(!owned||owned.count<count)throw Error('无法核对'+name+'的可用数量，请在预览中手动修正背包');state.inventory=state.inventory.filter(x=>x.name!==name);if(owned.count>count)state.inventory.push({...owned,count:owned.count-count});}return state;}
export function formatFarmReview(candidate,current,roles=[],anchors={}){const clear=candidate.plots.some(p=>p.crop)?candidate.plots.flatMap((p,i)=>!p.crop&&current.plots[i]?.crop?['农田：'+(i+1)+'|无|空地|未知|未浇|无']:[]):[];return formatState(candidate,roles,anchors).replace('【状态结束】',clear.join('\n')+(clear.length?'\n':'')+'【状态结束】');}
export function networkFailure(error,{aborted=false,timedOut=false,elapsed=0,chars=0,lastSuccess=false}={}){if(aborted)return new DOMException('当前请求已因正文或聊天变化而取消','AbortError');if(timedOut)return Error('手机 API 等待超时（'+Math.round(elapsed/1000)+' 秒），旧消息保留。可增加请求等待时间或精简上下文后重试。');if(error.name==='TypeError')return Error('手机 API 连接中断，浏览器未提供 HTTP 状态（等待 '+Math.round(elapsed/1000)+' 秒，请求约 '+chars+' 字符）。'+(lastSuccess?'本次会话曾连接成功，不能据此认定是 CORS；可能是大请求、服务商网关或移动网络中断。':'可能涉及网络、服务商网关或跨域限制，暂时不能确定。')+' 可在设置中精简重试本楼；不会自动重复扣费请求。');return error;}
