import {world,clone,applyPatch} from './core.js';
import {appendTransaction,socialRevision} from './social.js';
import {parseResponseJSON} from './json-response.js';
import {questCompleted,settleActionDraft} from './round-settlement.js';
export const taskBatchInstruction='只核对用户选中的任务，不整理全部正文变量。用户点完成不等于已完成，依据最近正文、任务目标、当前背包/金币和已结算记录判断。一次核对全部selectedTasks，每个任务返回一项。只输出JSON：{decisions:[{name,completed:true或false,rewardState:"already_received或grant或pending",gold:0,items:[{name,count}],evidence:"对应正文原句",reason:"简短说明"}]}。未完成返回false且gold=0/items=[]；正文奖励已经计入当前状态返回already_received且不重复给奖；确有漏发的明确奖励返回grant，仅填写还未入账的金币和物品；不明或未领取返回pending且不猜奖励。不得新增任务、不得返回patch、农田、位置或其他变量。不能因为缺少摘要就否认正文明确完成的任务。';
export function parseTaskBatch(raw,tasks,narrative){const data=parseResponseJSON(raw);if(Object.keys(data).some(k=>k!=='decisions')||!Array.isArray(data.decisions)||data.decisions.length!==tasks.length)throw Error('批量核对必须逐项返回所选任务');const seen=new Set();return data.decisions.map(row=>{const q=tasks.find(q=>q.name===row.name);if(!q||seen.has(row.name)||typeof row.completed!=='boolean'||!['already_received','grant','pending'].includes(row.rewardState))throw Error('任务核对包含未知或重复任务');seen.add(row.name);if(Object.keys(row).some(k=>!['name','completed','rewardState','gold','items','evidence','reason'].includes(k)))throw Error('任务核对不能修改其他变量');const gold=row.gold??0,items=row.items||[];if(!Number.isInteger(gold)||gold<0||gold>1000000||!Array.isArray(items)||items.length>30||items.some(i=>typeof i.name!=='string'||!i.name.trim()||i.name.length>80||!Number.isInteger(i.count)||i.count<1||i.count>1000000)||new Set(items.map(i=>i.name)).size!==items.length)throw Error('任务奖励数量无效');if((!row.completed||row.rewardState!=='grant')&&(gold||items.length))throw Error('未完成或已入账任务不能再次发奖');if(typeof row.evidence!=='string'||!row.evidence.trim()||row.evidence.length>1200)throw Error('请给出任务核对的正文依据');const normalize=s=>s.replace(/<[^>]*>/g,'').replace(/\s+/g,'');if(narrative!==undefined&&!normalize(narrative).includes(normalize(row.evidence)))throw Error('任务核对依据没有出现在正文中');if(row.rewardState==='grant'){const proof=(q.reward||'')+' '+row.evidence,coins=[...proof.matchAll(/(\d+)\s*(?:金币|金|g\b)/gi)].map(m=>+m[1]);if(gold&&(!coins.length||gold>Math.max(...coins)))throw Error('奖励金币超出明确的任务报酬');if(items.some(item=>!proof.includes(item.name)))throw Error('奖励物品缺少明确依据');}return {...row,gold,items};});}
export function applyTaskBatch(original,tasks,decisions,batchId){const s=clone(original),done=[],pending=[];for(const [i,input] of decisions.entries()){let row={...input};const state=world(s),q=state.quests.find(q=>q.name===row.name);if(!q||questCompleted(q))throw Error('任务已变化，请重新选择');const questKey=JSON.stringify([q.name,q.goal||'',q.deadline||'',state.calendar.year,state.calendar.season,state.calendar.day]);if(row.completed&&s.taskCompletionReceipts?.some(r=>r.questKey===questKey))row={...row,rewardState:'already_received',gold:0,items:[]};if(!row.completed){pending.push({name:q.name,reason:row.reason||'正文尚未确认完成'});continue;}if(row.rewardState==='grant'){const items=row.items.map(item=>({...state.inventory.find(x=>x.name===item.name)||{kind:item.name.endsWith('种子')?'seed':'item',price:0,priceUnknown:true},name:item.name,count:item.count}));appendTransaction(s,state,{id:batchId+'-'+i,gold:row.gold,items,description:'任务“'+q.name+'”已完成，本次补齐奖励：'+row.gold+'金币'+items.map(x=>'、'+x.name+'×'+x.count).join('')});}
 const current=world(s),quests=current.quests.map(x=>x.name===q.name?{...x,status:row.rewardState==='pending'?'已完成（待领取）':'已结算'}:x);if(q.mailQuestId){const mail=s.mailQuests.find(x=>x.id===q.mailQuestId);mail.status='completed';mail.completed=Date.now();}const stateAfter=applyPatch(world(s),{quests});if(s.turns.length){s.turns.at(-1).state=stateAfter;s.turns.at(-1).socialRevision=socialRevision(s);}else{s.base=stateAfter;s.baseSocialRevision=socialRevision(s);}(s.taskCompletionReceipts??=[]).push({name:q.name,questKey,goal:q.goal,calendar:clone(state.calendar),batchId,rewardState:row.rewardState,gold:row.gold,items:row.items,evidence:row.evidence});done.push(q.name);}
 const last=s.turns.findLast(t=>t.actionDraft);s.draft=settleActionDraft(s.draft,last?.actionDraft,last?.actionBase||s.base,world(s),{consumeNonFarm:false});return {store:s,done,pending};}
