import test from 'node:test';import assert from 'node:assert/strict';import {readStateBlock,statePrompt} from './protocol.js';import {formatState} from './text-state.js';import {parseChatReply,chatInstruction} from './chat-protocol.js';
const roles=[{id:'10',name:'莱尔'},{id:'11',name:'莱恩'},{id:'13',name:'哈兰'}],anchors={邮局:{region:'center',x:25,y:55}};
const base={gold:0,capacity:24,calendar:{season:'春季',day:1,year:1,time:'06:00',weather:'晴',weekday:''},inventory:[],plots:Array.from({length:24},()=>({crop:'',days:null,wet:false,fertilizer:''})),relationships:{},locations:{},quests:[],animals:[],buildings:[],calendarEvents:[],notes:''};const wrap=x=>'【手机状态】\n'+x+'\n【状态结束】';
test('repeated dash placeholders preserve all inventory and user position does not masquerade as NPC',()=>{const p=readStateBlock(wrap('背包：种子|3|种子|20|4\n背包：衬衫|1|物品|--|--\n背包：药水|1|物品|N/A|——\n位置：林娇|你的牧场'),base,{roles,anchors,userName:'林娇',initial:true});assert.equal(p.state.inventory.length,3);assert(p.state.inventory[1].priceUnknown);assert(!p.warnings.some(x=>x.includes('未收录')));assert(p.warnings.some(x=>x.includes('待补位置')));assert(statePrompt(p.state,roles,anchors,false).includes('当前还没有地图位置的角色：莱尔、莱恩、哈兰'));});
test('unknown price, role alias, parenthesized floor and extra system role do not block valid state',()=>{const p=readStateBlock(wrap('时间：春季|1|星期一|06:15|晴\n背包：衬衫|1|服饰|未知|未知\n位置：维克托|PM超市\n位置：莱恩|家具服装店(二楼)\n位置：小爱(系统)|老屋'),base,{roles:[...roles,{id:'07',name:'维克多'}],anchors:{PM超市:{region:'south',x:27,y:25},家具服装店:{region:'east',x:24,y:23}}});assert.equal(p.state.inventory[0].priceUnknown,true);assert.equal(p.state.locations['07'].region,'south');assert.equal(p.state.locations['11'].region,'east');assert(p.warnings.some(x=>x.includes('小爱')));assert.equal(p.state.calendar.time,'06:15');});
test('malformed list is kept intact while unrelated valid fields update',()=>{const state={...base,inventory:[{name:'保留物品',count:2}]};const p=readStateBlock(wrap('金币：500\n背包：物品A|2\n背包：物品B|不详'),state);assert.deepEqual(p.state.inventory,state.inventory);assert.equal(p.state.gold,500);assert(p.warnings.length);});
test('model format variations: omitted year, weekday, floor suffix and unknown progress',()=>{const p=readStateBlock(wrap('时间：春季|1|星期一|06:15|晴朗\n位置：莱恩|家具服装店二楼\n任务：收礼|进行中|未知|开包裹|未知|今天|详情'),base,{roles,anchors:{家具服装店:{region:'east',x:24,y:23}}});assert.equal(p.state.calendar.year,1);assert.equal(p.state.calendar.weekday,'星期一');assert.equal(p.state.calendar.time,'06:15');assert.equal(p.state.locations['11'].region,'east');assert.equal(p.state.quests[0].progress,undefined);});
test('comma-separated inventory entries and unit-bearing numbers parse without losing items',()=>{const p=readStateBlock(wrap('背包：防风草种子|4, 春日微风内衣|1\n好感：莱恩|15点\n时间：春季|第1日|星期一|6:15|晴|第2年'),base,{roles});assert.deepEqual(p.state.inventory.map(x=>[x.name,x.count]),[['防风草种子',4],['春日微风内衣',1]]);assert.equal(p.state.relationships['11'],15);assert.equal(p.state.calendar.year,2);assert.throws(()=>readStateBlock(wrap('金币：4,含糊描述'),base));});
test('text footer updates time friendship and named location with empty farm in one line',()=>{const parsed=readStateBlock(wrap('时间：春季|1|1|06:20|晴\n背包：无\n农田：无\n位置：哈兰|邮局\n好感：哈兰|15'),base,{roles,anchors});assert.equal(parsed.state.calendar.time,'06:20');assert.equal(parsed.state.relationships['13'],15);assert.deepEqual(parsed.state.locations['13'],{region:'center',x:25,y:55});assert.equal(parsed.state.plots.length,24);assert(!formatState(base,roles,anchors).includes('index'));});
test('text deltas preserve other crops, stage validation fails closed',()=>{const p=readStateBlock(wrap('农田：1|草莓|播种|未知|已浇|无'),base,{roles,anchors});assert.equal(p.state.plots[0].days,null);assert.equal(p.state.plots[1].crop,'');assert.throws(()=>readStateBlock(wrap('农田：1|草莓|播种|0|已浇|无'),base,{roles,anchors}));assert.throws(()=>readStateBlock(wrap('位置：莱恩|不存在'),base,{roles,anchors}));assert.throws(()=>readStateBlock(wrap('时间：春季|1|1|26:90|晴'),base));});
test('text formatter roundtrips full known state and prompt emphasizes time friendship',()=>{const s={...base,locations:{'13':anchors.邮局},relationships:{'13':15}};const parsed=readStateBlock(formatState(s,roles,anchors),base,{roles,anchors});assert.deepEqual(parsed.state.locations,s.locations);assert.equal(parsed.state.relationships['13'],15);const prompt=statePrompt(base,roles,anchors,true);assert(prompt.includes('每一轮都必须复核'));assert(prompt.includes('好感变化'));});
test('private chat rejects twins switching speakers and groups validate member identity',()=>{assert.throws(()=>parseChatReply('{"bubbles":["[莱尔]：你好"]}',roles[1],roles));assert.deepEqual(parseChatReply('{"bubbles":["[莱恩]：你好"]}',roles[1],roles),[{speakerId:'11',text:'你好'}]);const group={id:'group-twins',name:'三人群',members:['11','10']};assert(chatInstruction(group,roles).includes('手机群聊'));assert.equal(parseChatReply('{"messages":[{"roleId":"10","text":"你好"},{"roleId":"11","text":"早"}]}',group,roles).length,2);assert.throws(()=>parseChatReply('{"messages":[{"roleId":"13","text":"你好"}]}',group,roles));});

test('actual 15 planted plots survive empty crop with unknown stage',()=>{const rows=Array.from({length:24},(_,i)=>'农田：'+(i+1)+'|'+(i<14||i===15?'防风草|播种|未知|未浇|无':'空地|未知|未知|未浇|无'));const p=readStateBlock(wrap('时间：春季|1日|星期一|06:40|晴|第1年\n背包：无\n'+rows.join('\n')),base);assert.equal(p.state.plots.filter(x=>x.crop==='防风草').length,15);assert.equal(p.state.plots[14].stage,'empty');assert.equal(p.state.plots[15].stage,'seeded');assert(p.state.plots.filter(x=>x.crop).every(x=>x.days===null&&x.stage==='seeded'));assert.deepEqual(p.warnings,[]);});
test('compact farm range and invalid range do not silently corrupt plots',()=>{const p=readStateBlock(wrap('农田：1-15|防风草|播种|4|已浇|无'),base);assert.equal(p.state.plots.filter(x=>x.crop).length,15);assert.throws(()=>readStateBlock(wrap('农田：1-121|防风草|播种|4|已浇|无'),base));assert.throws(()=>readStateBlock(wrap('农田：1|防风草|空地|未知|未浇|无'),base));assert.throws(()=>readStateBlock(wrap('农田：1|防风草|播种|0|未浇|无'),base));});
