function openTransfer(kind){
 if(!activeRole)return;const role=activeRole,state=bridge.getSocialState(),gift=kind==='gift',items=state.inventory.filter(x=>x.count>0),members=role.members?chatRoles.filter(r=>role.members.includes(r.id)):[role];
 const dialog=uiDocument.createElement('div');dialog.className='jp-review jp-transfer-compose jp-transfer-page '+(gift?'jp-gift-page':'');dialog.setAttribute('role','dialog');dialog.setAttribute('aria-label',gift?'送礼物':'发红包');
 dialog.innerHTML='<section class="jp-review-card"><header class="jp-sheet-head"><button class="jp-icon-button jp-cancel" aria-label="取消赠送">‹</button><h3>'+(gift?'送一份礼物':'发红包')+'</h3></header><p class="jp-transfer-kicker">'+(gift?'A LITTLE GIFT · 一点心意':'LUCKY POCKET · 普通红包')+'</p><label class="jp-transfer-row"><span>送给</span><select aria-label="收礼人">'+members.map(r=>'<option value="'+esc(r.id)+'">'+esc(r.name)+'</option>').join('')+'</select></label>'+(gift?'<label class="jp-transfer-row"><span>背包好物</span><select aria-label="赠送物品">'+(items.length?items.map(x=>'<option value="'+esc(x.name)+'">'+esc(x.name)+' · '+x.count+' 件</option>').join(''):'<option value="">背包里还没有礼物</option>')+'</select></label><label class="jp-transfer-row"><span>赠送数量</span><input type="number" min="1" step="1" value="1" aria-label="礼物数量"><small>份</small></label>':'<label class="jp-transfer-row"><span>单个金额</span><input type="number" inputmode="numeric" min="1" step="1" max="'+state.gold+'" placeholder="0" aria-label="红包金额"><small>金币</small></label>')+'<label class="jp-transfer-row"><input maxlength="100" aria-label="赠送留言" placeholder="'+(gift?'想把这份喜欢送给你':'愿你今天，也有好心情')+'"><span>✎</span></label><div class="jp-packet-art"><small>'+(gift?'FROM MY GARDEN':'MOON VALLEY')+'</small><strong>'+(gift?'把心意，系成礼物。':'花开有时，好运有你。')+'</strong><p>'+(gift?'从背包挑选，送给惦记的人':'月亮谷限定 · 花间祝福')+'</p></div><div class="jp-transfer-total" aria-live="polite"></div><p class="jp-review-error" role="status"></p><button class="jp-confirm">'+(gift?'系好丝带，送给你':'塞进红包')+'</button><p class="jp-transfer-foot">'+(gift?'赠送后将从背包扣除相应数量':'可用余额 '+state.gold+' 金币 · 仅使用游戏金币')+'<br>送出后，点击聊天回复按钮等待对方回应</p></section>';
 $('.screen').append(dialog);const confirm=dialog.querySelector('.jp-confirm'),total=dialog.querySelector('.jp-transfer-total');
 function updateTotal(){if(gift){const item=items.find(x=>x.name===dialog.querySelector('[aria-label="赠送物品"]').value),input=dialog.querySelector('[aria-label="礼物数量"]'),n=Number(input.value);input.max=item?.count||0;total.innerHTML=esc(item?.name||'等待一份好物')+'<small>× '+esc(input.value||'0')+' 份心意</small>';confirm.disabled=!item||!Number.isSafeInteger(n)||n<1||n>item.count;}else{const n=Number(dialog.querySelector('[aria-label="红包金额"]').value);total.innerHTML=esc(Number.isFinite(n)?n:0)+'<small>金币</small>';confirm.disabled=!Number.isSafeInteger(n)||n<1||n>state.gold;}}
 dialog.querySelectorAll('input,select').forEach(e=>e.addEventListener('input',updateTotal));updateTotal();dialog.querySelector('.jp-cancel').onclick=()=>dialog.remove();dialog.addEventListener('keydown',e=>{if(e.key==='Escape')dialog.remove();});
 const run=uiCommunity().chatId;confirm.onclick=async()=>{confirm.disabled=true;try{if(run!==uiCommunity().chatId)throw Error('对话已切换，请重新打开赠送页面');await bridge.sendTransfer(role,{kind,recipientId:dialog.querySelector('[aria-label="收礼人"]').value,item:dialog.querySelector('[aria-label="赠送物品"]')?.value,count:+dialog.querySelector('[aria-label="礼物数量"]')?.value,amount:+dialog.querySelector('[aria-label="红包金额"]')?.value,note:dialog.querySelector('[aria-label="赠送留言"]').value});dialog.remove();}catch(err){dialog.querySelector('.jp-review-error').textContent=err.message;updateTotal();}};
}
